### ISSUE TITLE
Replace all in selection only replaces first match

### ISSUE THREAD

**Issue by Arcanemagus** [atom/find-and-replace#1005]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When doing a replacement on a selection of text only the first match is actually replaced, meaning there is currently no difference between "Replace" and "Replace All" when searching in a selection.

Atom v1.24.1 (working):
![2018-03-20_11-39-05](https://user-images.githubusercontent.com/427137/37676097-37776a42-2c34-11e8-9ec0-bb3069acf989.gif)

Atom v1.25.0 (broken):
![2018-03-20_11-40-32](https://user-images.githubusercontent.com/427137/37676106-3ee2d3c0-2c34-11e8-8b97-4bf397726b5a.gif)

### Steps to Reproduce

1. Open Atom in safe mode
2. Open a document and search for something
3. Enable "only within selection" mode on a selection that has multiple results within it
4. "Replace All" on the selection

**Expected behavior:** All matches are replaced.

**Actual behavior:** Only the first match is replaced.

**Reproduces how often:** 100% of the time.

### Versions

OS: Windows 10 Enterprise x64

```
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### Additional Information

This regressed since Atom v1.24.1 ([v0.215.0](https://github.com/atom/find-and-replace/releases/tag/v0.215.0))

Relevant changes:
https://github.com/atom/find-and-replace/compare/v0.215.0...v0.215.5

**Comment by Arcanemagus** [comment]
This looks suspicious within the range this broke within, but I haven't confirmed anything yet: https://github.com/atom/find-and-replace/pull/982.

**Comment by jameswilliamknight** [comment]
I am experiencing this issue, Atom v1.25.1 x64
Reproduced with multiple carets/cursors (lines in between selections), without using regex match.

**Comment by ricardograca** [comment]
If anyone else is still seeing this with versions greater than 1.27.0 check out #1010 for possible workarounds until the issue is completely fixed.
