### ISSUE TITLE
"Replace All - Within Current Selection" only replaces a single match

### ISSUE THREAD

**Issue by WiliTest** [atom/find-and-replace#1010]
*Edit by @rsese*

Reproduced on macOS 10.12.6 with 1.39.0-nightly11:

1. create a new file
2. Enter:

```
hello
hello
```

3. Select all the text
4. `Find And Replace: Show`
5. Enable `Only in Selection`
6. Set search text to `hello` and replace text to `bye`
7. Click `Find All`
8. Click `Replace All`

2 results are reported after step 7 and then after step 8, only the second `hello` is replaced:

![in-selection](https://user-images.githubusercontent.com/734194/58213933-90b3b080-7cb9-11e9-872a-9e3304d789c4.gif)

---

### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

"replace all" only replace a single one **whithin selection** 

### Steps to Reproduce

1. in styles.less select this text: syntax--punctuation syntax--section syntax--property-list 
2. trigger the find and replace
3. replace all within the current selection `--syntax` by `.`

**Expected behavior:** [What you expect to happen]

all --syntax should be replaced by `.`

**Actual behavior:** [What actually happens]
only one --syntax is replaced

**Reproduces how often:** [What percentage of the time does it reproduce?]
5 times

### Versions
windows 10
1.25.0
(by the way `atom --version` don't output anything in the cmd. And `apm --version`  throw an error)
![cmd_2018-04-03_23-18-04](https://user-images.githubusercontent.com/24194840/38276483-71701106-3795-11e8-991a-cd96666413ad.png)

### Additional Information

screenshot: 
![2018-04-03_22-58-57](https://user-images.githubusercontent.com/24194840/38276259-b08f4b96-3794-11e8-8e70-3ea27367214c.gif)

**Comment by philgyford** [comment]
This has been driving me nuts too. Finding within a selection has been buggy for years (e.g. #298). Here's an example of a way in which this works sometimes, and not others.

## Working

1. Select text
2. Hit `cmd-F`
3. Click 'Only in Selection' button
4. Enter find/replace text
5. Click 'Replace All' button.

Result: All matches in selection are replaced

![works](https://user-images.githubusercontent.com/66670/39991034-22f39fde-5766-11e8-929e-6f4cb988c54b.gif)

## Not Working

(Note, the steps are identical except steps 3 and 4 are reversed.)

1. Select text
2. Hit `cmd-F`
3. Enter find/replace text
4. Click 'Only in Selection' button
5. Click 'Replace All' button.

Result: Only the final match (in the order the selection was made) is replaced. 

![fail](https://user-images.githubusercontent.com/66670/39991042-279a62a2-5766-11e8-8aae-3d8afcb643aa.gif)

**Comment by philgyford** [comment]
Another example, and one that is sporadic and hard to reproduce reliably...

1. With Regex and Within Current Selection already 'on'...
2. Select text
3. Hit `cmd-F`
4. The selected area shrinks to only include the first match, and "1 result" is listed.
5. Click 'Replace All'
6. All of the matches in the originally-selected text are replaced, not just that first one.

![sort of](https://user-images.githubusercontent.com/66670/39992414-a02f6d58-576a-11e8-892e-d723cdf8f29c.gif)

So, the correct result, in the end, but an odd intermediate stage.

However, sometimes it *only* replaces that first match, and not the others within the selection.

And, sometimes, the selected area is displayed correctly.

**Comment by philgyford** [comment]
One more example of a slightly different oddness...

1. Select text containing what will be 2 matches (the find and replace fields are already populated in the search panel).
2. Hit `cmd-F`
3. '4 results' is displayed, as expected.
4. Click 'Within Current Selection' button.
5. '2 results' is displayed, as expected.
6. Unclick 'Within Current Selection' button.
7. '4 results' is displayed, as expected.
8. Click 'Within Current Selection' button again.
9. '1 result' is displayed, and the selection has been reduced to that single matching result; the original selection has been lost.

![2018-05-14 11 35 38](https://user-images.githubusercontent.com/66670/39992629-51be15ba-576b-11e8-932c-c32ed28f29e4.gif)

**Comment by alisonketz** [comment]
I am having this exact same problem and it is driving me nuts. I write in R, and was hoping to use atom instead of R-studio (hate) or sublime. Please fix this! It's a deal-breaker and pretty appalling for a text editor. This is the point of having a text editor! Ubuntu 16.04

**Comment by gnthackray1978** [comment]
I'm still seeing this as well I'm on 1.34 on windows

**Comment by ZosoDerGoldene** [comment]
Still an issue in 1.34.0 on Linux

**Comment by Cloudixx** [comment]
Still an issue on 1.35.1 on OSX

**Comment by rsese** [comment]
Reproduced on macOS 10.12.6 with 1.39.0-nightly11:

1. create a new file
2. Enter:

```
hello
hello
```

3. Select all the text
4. `Find And Replace: Show`
5. Enable `Only in Selection`
6. Set search text to `hello` and replace text to `bye`
7. Click `Find All` (
8. Click `Replace All`

2 results are reported after step 7 and then after step 8, only the second `hello` is replaced:

![in-selection](https://user-images.githubusercontent.com/734194/58213933-90b3b080-7cb9-11e9-872a-9e3304d789c4.gif)
