### ISSUE TITLE
Select-next doesn't respect whole-word when set in find bar

### ISSUE THREAD

**Issue by kylebarron** [atom/find-and-replace#1011]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I've read https://github.com/atom/find-and-replace/issues/521 and https://github.com/atom/find-and-replace/pull/482. 

To my understanding from those issues, <kbd>ctrl</kbd>-<kbd>d</kbd> is supposed to see if the "whole word" setting is checked, and if so, `select-next` selects the next full word. 

Here are two gifs, the latter in safe mode, where you can see that the find and replace toolbar respects "whole word" but not `select-next`. 

![peek 2018-04-03 17-56](https://user-images.githubusercontent.com/15164633/38278246-44753536-3769-11e8-9217-a94dabb235ca.gif)
![peek 2018-04-03 17-59](https://user-images.githubusercontent.com/15164633/38278247-46fd3542-3769-11e8-83eb-9f0f003a2eb9.gif)

### Steps to Reproduce

1. Paste the following text:
```
1 test
2 test
3 test1
4 test2
```
2. Double click on `test` after the number 1.
3. Press <kbd>ctrl</kbd>-<kbd>d</kbd> three times

**Expected behavior:**

I expect `test1` and `test2` to not be highlighted, since `test` is not a whole word in those cases.

**Actual behavior:**

`test1` and `test2` are highlighted with `select-next`.

**Reproduces how often:**

100%

### Versions

```
> atom --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

```
> uname -a
Linux desktop 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by DenaByte** [comment]
I have the same issue, any info on a possible fix? Windows 10 Pro here

**Comment by rsese** [comment]
Hmmm, I think this is expected behavior?

> I've read #521 and #482.

I poked around and see #482 was then reverted in #606.

I think the behavior is described by the pull request author in this comment:

https://github.com/atom/find-and-replace/pull/606#issuecomment-195428369

So if you click on a word and then use `Find And Replace: Select Next` to select that word, further `ctrl-d`s will only select whole words (so `test1` and `test2` won't be selected in your example).  They then mention that:

> If you make the initial selection any other way (double-click, click-drag, shift-right-right-right, shift-option-left), or if the existing selection is not a whole word, then pressing cmd-d will add any string match to your selection.

This matches your step 2 where you double click to select the word.

Going to go ahead and close but let me know if if I'm mis-understanding anything.

**Comment by kylebarron** [comment]
It just seems like a very arbitrary decision, and it would be nice if there were a setting somewhere where we could change this behavior. For example, double-clicking always selects the entire word, right? Then it seems very unintuitive for a method that always selects the entire word not to trigger <kbd>CTRL</kbd>+<kbd>D</kbd> to select the next whole word.

After all, @benogle [said](https://github.com/atom/find-and-replace/issues/521#issuecomment-153541278):
> > If you originally have no selection (just a cursor in a word somewhere), and you use cmd-d to select that whole word, then the following presses of cmd-d will match only whole words.
> >
> > If you created your initial selection by any other means (e.g. clicking and dragging to highlight a whole word), then the following presses of cmd-d will match anything (not just whole words).
>
> Atom used to do that, and people didnt expect it.

I agree and find this behavior in general very unintuitive.
