### ISSUE TITLE
`Only in Selection` option with no open files throws an error

### ISSUE THREAD

**Issue by rsese** [atom/find-and-replace#1012]
If you open a project and there are no open buffers, enabling `Only in Selection` in file find will generate the error below.

[Enter steps to reproduce:]

1. Open atom/atom in safe mode `atom --safe .`
2. Close any open buffers
3. `Find and Replace: Show`
4. Enable `Only in Selection`

Doesn't reproduce in 1.26.0-beta0, https://github.com/atom/find-and-replace/pull/1007 maybe related?

**Atom**: 1.27.0-dev-8ef1a05f2 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRanges' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:712

TypeError: Cannot read property 'getSelectedBufferRanges' of null
    at FindView.toggleSelectionOption (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:712:37)
```

### Commands

```
     -0:05.8.0 core:close (input.hidden-input)
     -0:05.1.0 find-and-replace:show (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
```

### Non-Core Packages

```

```

**Comment by thomasjo** [comment]
Good guess, @rsese. That is definitely the culprint. Specifically, [this change](https://github.com/atom/find-and-replace/pull/1007/files#diff-031d2cf6de79608fdbf0fde30f0fc2f8R701) which doesn't do any null checking is the cause of this bug.

/cc @smashwilson

**Comment by lee-dohm** [comment]
@smashwilson Can you take a look at this?
