### ISSUE TITLE
Find and Replace throws an invalid regex escape, even when regex is turned off

### ISSUE THREAD

**Issue by DenaByte** [atom/find-and-replace#1022]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When searching for a row that contains "- " aka. "dash" or any other symbol that should be otherwise escaped in RegEx, with RegEx toggled off, the Find and Replace in project and Find and Replace in file throw an "Invalid regular expression: ..." error stating that there is an "invalid escape /" 

![atom_find_replace_bug](https://user-images.githubusercontent.com/26298592/40227691-dd91d69c-5a97-11e8-99e7-2f2c2862eb77.png)

### Steps to Reproduce

1. Open find and replace
2. Enter a piece of code that contains regularexpression symbols that should be escaped if you would otherwise be using RegEx serach
3. Catch the thrown error above the search tab in the Find and Replace block

**Expected behavior:**

Get result set, considering RegEx is turned off

**Actual behavior:** Thrown error above the search tab in the Find and Replace block about escaping symbols when using regex, while it is turned off and no result set displayed. The search is not initiated.

**Reproduces how often:** 100% of the time

### Versions

Windows 10 Pro Build 16299.431 Version 1709

Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python
git
visual studio

### Additional Information

No incomaptibilities or depricated packages/commands are being indicated and no other error gets throwng, except for the one mentioned above.

**Comment by 50Wliu** [comment]
Reproduced.  Minimal example: `ö-`

Looks like it happens for any non-ASCII character?

**Comment by DenaByte** [comment]
Even a simple </div> brakes it

**Comment by lee-dohm** [comment]
@maxbrunsfeld Can you take a quick look at this?

**Comment by amayer5125** [comment]
I can reproduce this just by searching for "-" (dash). Any search I do that contains a dash will throw this error.

**Comment by lee-dohm** [comment]
I cannot reproduce this by searching only for `-` using Atom v1.27.1 on Mac OS X 10.13.4. Nor can I reproduce this by searching for `foo-bar`. I can, however, reproduce this using the minimal example @50Wliu provided.

**Comment by amayer5125** [comment]
I am using version 1.27.1 on Fedora. All three of these trigger the error for me. `ö-`, `-`, `foo-bar`

**Comment by maxbrunsfeld** [comment]
This occurs whenever a regex contains a dash and either:
1. The search term contains a non-ascii character
2. The buffer contains astral plane characters

I think it was introduced in https://github.com/atom/superstring/pull/61. It looks like for some reason, PCRE does not allow dashes to be escaped when in unicode mode.

**Comment by maxbrunsfeld** [comment]
Oh, nevermind; this isn't a superstring issue. The exception is thrown by V8 when trying to instantiate a *JavaScript* regular expression with an escaped dash in unicode mode. Maybe we just need to change our regexp-escaping code to not prepend a backslash before dashes; that seems unnecessary anyway.

**Comment by maxbrunsfeld** [comment]
Thanks for the reports everyone. The fix will go out in our next hotfix release.

**Comment by DenaByte** [comment]
Awesome ! Thanks for your time max ! Hoping to get the hotfixt soon

**Comment by maxbrunsfeld** [comment]
Ok, it looks like my fix broke the Arom build because regex escaping is used in a different way elsewhere in the codebase. I’ll have to come up with a slightly different fix on Monday.

**Comment by maxbrunsfeld** [comment]
This fix has shipped in Atom 1.28.0-beta3.

**Comment by T1MOXA** [comment]
![image](https://user-images.githubusercontent.com/19938629/53602609-0119cc80-3bb8-11e9-9635-94fa5583d3bb.png)
