### ISSUE TITLE
When invoking context menu using keyboard in tree-view focus, the "Search in Directory" option is missing. 

### ISSUE THREAD

**Issue by JK-mber** [atom/find-and-replace#1025]
### Description

Using the keyboard to navigate to a folder, pressing 'Context' keyboard key shows no "Search in Directory" option. In an earlier Atom version (1.17.0) it showed, but selected the wrong directory.

### Steps to Reproduce

1. Move focus to tree view (either by keyboard shortcut or using mouse)
2. Use keyboard arrows to navigate to a folder
3. Press 'Context' keyboard key
4. Observe that no "Search in Directory" option is present

**Expected behavior:** A "Search in Directory" option as the first entry, as if the context menu was invoked with a mouse right click

**Actual behavior:** No "Search in Directory" option appears

**Reproduces how often:** Every time

### Versions

[~] $ atom-1.22 --version
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Linux, Debian, Gnome

**Comment by rsese** [comment]
Thanks for the report -

> [~] $ atom-1.22 --version

The latest stable release version is currently 1.27.1  - can you install 1.27.1 and confirm if you still see the issue?

**Comment by JK-mber** [comment]
@rsese Issue can be reproduced with version 1.27.2
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by rsese** [comment]
Thanks @JK-mber - I think I assumed the "Context" keyboard key was the same as right clicking but is that actually not true?  If you right click in your step 3 do you see the "Search in Directory" item?

**Comment by JK-mber** [comment]
Yes, the Search in Directory item is there using mouse. One thing I thought could be the issue is that when invoking the context menu using the keyboard, the menu appears where the mouse is (is the mouse position considered when selecting context menu items?)
I attached two images showing the to context menus.
![keyboard_context_menu](https://user-images.githubusercontent.com/22314853/41082936-302029ac-6a30-11e8-98bc-d67d84f176a9.png)
![mouse_context_menu](https://user-images.githubusercontent.com/22314853/41082938-303f7b72-6a30-11e8-818c-228100132ada.png)

**Comment by rsese** [comment]
> One thing I thought could be the issue is that when invoking the context menu using the keyboard, the menu appears where the mouse is (is the mouse position considered when selecting context menu items?)

Oh interesting - so just to confirm, if after your step 2 you then moved your mouse pointer over the folder you navigated to with your keyboard, does "Search in Directory" show up in that case?

I don't have a keyboard with a menu/context key so I'll see if someone else can give it a try (unless there's a way for me to simulate that key?).

**Comment by JK-mber** [comment]
@rsese Yes, that is correct. If move mouse pointer to the exact same folder and right click, the Search in Directory option is there. 

According to https://superuser.com/questions/875332/how-to-emulate-context-menu-key-when-theres-none-on-keyboard you can emulate the context key using shift-f10.

**Comment by rsese** [comment]
Thanks @JK-mber I was able to reproduce on Windows using `shift-f10` but I just got a notification on an old issue and see that this has been reported already as the more general issue you described where the context menu seems to be working off of the mouse position:

https://github.com/atom/atom/issues/7850

Going to go ahead and close as a duplicate of that issue if you want to subscribe.
