### ISSUE TITLE
Text in find or replace field disappear when window size changes

### ISSUE THREAD

**Issue by shawnpyle** [atom/find-and-replace#1033]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Text in the find-and-replace window disappears when the window increases and shows up again when the window size is reduced.

![find-and-replace_diappearing_text](https://user-images.githubusercontent.com/48266/43010693-1fc64d2e-8c0f-11e8-9e05-8d5fbaee6d6c.gif)

### Steps to Reproduce
1. `atom --safe`
1. Create a new file
1. Cmd+F to open the find-and-replace window
1. Enter text in find
1. Expand the window and watch the text disappear before your eyes!

**Expected behavior:** [What you expect to happen]
Text would show at all times.

**Actual behavior:** [What actually happens]
Text is disappearing and reappearing when window size changes.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
$ uname -a
Darwin shawn-desktop.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199

$ atom -v
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report - have you tried disabling your GPU?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem

Also, is this behavior new to 1.28.2 or have you seen this in previous versions?

**Comment by shawnpyle** [comment]
@rsese Yes, disabling the GPU (`atom --disable-gpu`) did fix the problem I was seeing. 
Testing on [1.27.1](https://github.com/atom/atom/releases/tag/v1.27.1) did show the same behavior with disabling the GPU fixing the problem.

In addition, I should have mentioned that I'm on a fairly old MacPro.
![image](https://user-images.githubusercontent.com/48266/43088570-7b9e250a-8e70-11e8-8c9d-af7ed5041686.png)
