### ISSUE TITLE
Selection changed after clicking 'Find All' with "Only In Selection" enabled

### ISSUE THREAD

**Issue by qoomon** [atom/find-and-replace#1034]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Get a cursor at every search result works like a charm,
except with enabled "Only In Selection" search option,
then only one cursor is set.

relates to https://github.com/atom/find-and-replace/pull/290 

---

*Edit by @rsese*
Mentioned in https://github.com/atom/find-and-replace/issues/1034#issuecomment-409676635, looks like the selection is changed after clicking 'Find All' with "Only In Selection" enabled which causes the behavior described above.  If you don't click 'Find All' (step 4 below), it works ok.

---

### Steps to Reproduce

1. create a file with two lines of 'foo'
2. select both lines
3. enabled search option "Only In Selection" 
4. 'Find  All' for 'foo'
5. hit `alt+enter`

**Expected behavior:** a cursor behind every 'foo'

**Actual behavior:** one cursor behind last 'foo' only

**Reproduces how often:** always

### Versions

Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report! I was unable to reproduce with Atom 1.28.2 on macOS 10.12.6:

![find-replace-in-selection](https://user-images.githubusercontent.com/734194/43439775-4e8d3a20-945a-11e8-9e9e-306574e5c2b2.gif)

Can you share a GIF/screencast that shows your reproduction?

**Comment by mcgeek-mkcorp** [comment]
![atom-sr-multi-selection](https://user-images.githubusercontent.com/37450715/43485559-2c9062ee-94d7-11e8-8f07-eff74ca8db37.gif)

**Comment by rsese** [comment]
Thanks @mcgeek-mkcorp - I can reproduce if I select using multiple cursors but I tried the original repro steps again and found that I can reproduce (from my GIF I can see I didn't do step 4).

Looks after you click `Find All`, the selection is changed (i.e. `atom.workspace.getActiveTextEditor().getSelectedText()` only returns a single "foo").

**Comment by hneiva** [comment]
I've had some similar issues with this, but with single cursor.
(Leave "Only in selection" on, add "foo" to search, hit "Find" twice - get "only 1 found")

Here's my humble opinion on how the "Only in selection" button should behave:
> If user clicks Find, or Find all without any selection, disable said behaviour until the user intentionally selects text, either with shift select for multiple cursors (or single), or with mouse.

I don't know how/if this would even be achievable, but to me it makes no sense that a feature targeted to selection gets in the way of search even though there was no selection to begin with.

Cheers

**Comment by viniciusfaria1** [comment]
[NSGSoftwareLicenseAgreement__EULAandCorporateEntity__2019.docx](https://github.com/atom/find-and-replace/files/4831957/NSGSoftwareLicenseAgreement__EULAandCorporateEntity__2019.docx)

**Comment by viniciusfaria1** [comment]
- 

- [ ]   #@[
Duplicate of #](url)
