### ISSUE TITLE
command-enter/ctrl-enter doesn't replace all when find input is focused

### ISSUE THREAD

**Issue by jedwards1211** [atom/find-and-replace#1039]
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

When the find input is focused, the command bound to `command-enter`/`ctrl-enter` is `find-and-replace:confirm`.
When the replace input is focused, the command bound to `command-enter`/`ctrl-enter` is `find-and-replace:replace-all`.
(I determined this using the Key Binding Resolver)

I want the keybinding to always do the same thing regardless of what's focused within the find and replace pane.

What even is `find-and-replace:confirm`?  None of the button tooltips mention "confirm".  Only the "Replace All" button shows this keybinding, so this is very unexpected behavior.

**Comment by rsese** [comment]
> I want the keybinding to always do the same thing regardless of what's focused within the find and replace pane.

If you want to `find-and-replace:replace-all` if the find input is focused, you can tweak your  [keymap file](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/), I think this will work:

```
'. platform-win32 .find-and-replace':
  'cmd-enter': 'find-and-replace:replace-all'
```

I think `find-and-replace:confirm` acts almost the same as when the find input is focused and you click the Find button or use its keybinding.  The difference is that the Find button and its keybinding will focus the editor after you search whereas `find-and-replace:confirm` won't by default unless you enable `Settings > Packages > Find and Replace > Focus Editor After Search`.

**Comment by jedwards1211** [comment]
@rsese well, what I don't understand is that `enter` by itself seems to do the same thing (find next)
so this `cmd-enter` binding seems a) redundant and b) inconvenient since there is no default keyboard shortcut for replace all that works regardless of which field is focused.

I know I can edit my keybindings, the main reason I filed this issue is it seems like making more helpful defaults for users is a no-brainer (would you accept a PR to make this change?)

**Comment by jedwards1211** [comment]
Man the code for find-and-replace is nowhere to be found in the debug tools, not even at the path from the getSelectedBufferRange error stack trace...what the freaking f kind of hack is causing this?

**Comment by rsese** [comment]
> I know I can edit my keybindings, the main reason I filed this issue is it seems like making more helpful defaults for users is a no-brainer (would you accept a PR to make this change?)

Ahhh gotcha :+1:  My understanding is that we're very unlikely to change any default keybindings at this point since people can customize things in their keymap file if they want.  But I'll double check with the team for you and let you know if this is something we'd consider.
