### ISSUE TITLE
Regex is not wrapped correctly when whole word is on

### ISSUE THREAD

**Issue by jedwards1211** [atom/find-and-replace#1042]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`getFindPatternRegex` wraps with
```coffee
    expression = "\\b#{expression}\\b" if @wholeWord
```
This means `for|in` gets interpolated to `/\bfor|in\b/`.  In other words, `for` preceeded by a word boundary, or `in` followed by a word boundary -- but it doesn't require `for` to be followed by a word boundary or `in` to be preceeded by a word boundary.

I knew immediately when I saw this code that this would be a problem.

We should be wrapping with a non-capturing group (`"\\b(?:#{expression})\\b"`) to prevent this bug.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/1448194/44049810-bd4e01ba-9efa-11e8-8e3b-11ec824cea3b.png)

**Expected behavior:** [What you expect to happen]
The `for` in `forceUnicode` is not matched

**Actual behavior:** [What actually happens]
It is matched

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 2.7.11
git 2.15.2

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lee-dohm** [comment]
Thanks for the bug report. I've opened a feature request that will resolve this problem https://github.com/atom/find-and-replace/issues/1044.
