### ISSUE TITLE
document how to run tests

### ISSUE THREAD

**Issue by jedwards1211** [atom/find-and-replace#1049]
I wanted to figure out how to run tests on my local machine before making a PR, but currently I'm relying on going ahead an making the PR so I can see the CI results.  Is there a way to run tests on my local machine?

I checked in the Atom contributing guide, looked for scripts in `package.json` etc, but didn't find anything about how to run tests.  Finally I tried running what `.travis.yml` does, but that didn't work either:
```
$ curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh
Downloading latest Atom release on the stable channel...
Unknown CI environment, exiting!
```

**Comment by Arcanemagus** [comment]
Like almost everything else related to Atom, this is covered in the Flight Manual: [Running Specs](https://flight-manual.atom.io/hacking-atom/sections/writing-specs/#running-specs).

As a note, that's also what that script you found ends up doing after getting the environment setup:
https://github.com/atom/ci/blob/b671ab4b5706742e102b4173add7820d29ff90b5/build-package.sh#L184

**Comment by jedwards1211** [comment]
Oh yeah, I forgot to check that.  My apologies, thank you!

**Comment by Arcanemagus** [comment]
Actually you have a good point though, the document linked here in _this_ repository's `CONTRIBUTING.md` doesn't actually cover that aspect of an individual packages development.
