### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by cadreinfoca** [atom/find-and-replace#1053]
You have the core package "find-and-replace" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (<embedded>:13604:20)
Generator.next (null:null:null)
step (<embedded>:13591:279)
<unknown> (null:null:null)
process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by Arcanemagus** [comment]
Thank you for the report!

The readme linked in the report gives you instructions on the steps you need to take to get rid of this deprecation notice https://github.com/atom/dalek#i-got-a-warning-what-do-i-do.
