### ISSUE TITLE
Results don’t use the same font as in other source code views

### ISSUE THREAD

**Issue by ariasuni** [atom/find-and-replace#1057]
*Edit by @rsese - to add notes from https://github.com/atom/find-and-replace/issues/1057#issuecomment-438810270*

Looks like the behavior changed in 1.28.0, here's how things looked in 1.27.2, the code uses the font I set while the filename headers don't:

![1.27.2](https://github-slack.s3.amazonaws.com/monosnap/Project_Find_Results__sandboxtest-tree-sitter_2018-11-14_14-32-09.png)

But in 1.28.0 it swapped, the font I set is used for the filename header and the code doesn't:

![1.28.0](https://github-slack.s3.amazonaws.com/monosnap/Project_Find_Results__sandboxtest-tree-sitter_2018-11-14_14-36-52.png)

And this is how things look on 1.32.2 with macOS 10.12.6.

Maybe related to https://github.com/atom/find-and-replace/pull/1002.

---

 ### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Find and replace results aren’t displayed with the same font as configured in Editor → font-family

### Steps to Reproduce

1. Set a distinguishable font
2. Launch a search

**Expected behavior:** find and replace text results uses the same font as for other source code views.

**Actual behavior:** find and replace text results uses a different font than in other source code views.

See how the file name (using Atom’s font) is different from the source code extract which is using another font I didn’t configure:
![screenshot_20181113_184707](https://user-images.githubusercontent.com/2446451/48432522-db85c600-e774-11e8-9d59-d74f210ec2a4.png)

**Reproduces how often:** all the time

### Versions

On Arch Linux:

```
Atom    : 1.32.2
Electron: 2.0.12
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by rsese** [comment]
Thanks for the report!  Looks like the behavior changed in 1.28.0, here's how things looked in 1.27.2, the code uses the font I set while the filename headers don't:

![1.27.2](https://github-slack.s3.amazonaws.com/monosnap/Project_Find_Results__sandboxtest-tree-sitter_2018-11-14_14-32-09.png)

But in 1.28.0 it swapped, the font I set is used for the filename header and the code doesn't:

![1.28.0](https://github-slack.s3.amazonaws.com/monosnap/Project_Find_Results__sandboxtest-tree-sitter_2018-11-14_14-36-52.png)

And this is how things look on 1.32.2 with macOS 10.12.6.

Maybe related to https://github.com/atom/find-and-replace/pull/1002.
