### ISSUE TITLE
Clicking search result in Project Find Result does not focus on already opened file in other pane

### ISSUE THREAD

**Issue by Eric2048** [atom/find-and-replace#1058]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Clicking search result in Project Find Result does not consistently focus on already opened file in an existing pane. If you had clicked in another pane before clicking the search result, a new instance of the file is opened.  These can lead to confusion when working with lots of opened files in multiple panes.

### Steps to Reproduce
1. Open two panes, for example top and bottom.
2. Open file1 (containing "foo") in top pane
3. Perform a project-wide search for "foo"
4. Project Find Results opens in a new pane (depending on your find-and-replace settings)
5. Click in the bottom pane (i.e. pretend you are working with multiple files in multiple panes, and don't remember if file1 is already opened or which pane it is visible in.)
6. Click on the first "foo" search result in Project Find Results

**Expected behavior:**
Because file1 is already opened in the top pane, that instance of file1 will be focused and scrolled to the location of the search term "foo".

**Actual behavior:**
Another instance of file1 is opened in the bottom pane. Now you have two instances of file1 opened.

**Reproduces how often:**
Always

### Versions
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 2.7.10
git 2.14.3

OSX 10.12.6

**Comment by rsese** [comment]
Thanks for the report - I can reproduce with 1.32.2 on macOS 10.12.6.
