### ISSUE TITLE
Unknown Error occur when searching in project

### ISSUE THREAD

**Issue by XingyuJin** [atom/find-and-replace#1070]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I trying to use the feature **search in project** to find the files that certain content is in. But there is a window saying **UNKNOWN: unknown error, open '............(my path to directories in the project I am searching in)'**. The error window blocked all search result and cannot be closed.

### Steps to Reproduce

1. Ctrl+Shift+F to search in project
2. type content I want to find

**Expected behavior:** show me the files which contains the content I want.

**Actual behavior:** The window saying UNKNOWN: unknown error blocked the searching result

**Reproduces how often:** 100%

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

Also, is this only an issue with a specific project and there's no error with other projects?

> The window saying UNKNOWN: unknown error blocked the searching result

Can you share a screenshot?

**Comment by rsese** [comment]
> This issue only happen with this one specific project, which is a private github directory.

Oh interesting - do you remember if you always had trouble with this project and search or did it start recently?

Do you have any similar project that happen to be public that we can test?

Also, based on the path it looks like this is just a local project on your computer?

**Comment by XingyuJin** [comment]
This is actually my first time working with a project like this and use the function of searching in project, so I am not sure if it has been like for a long time. 

I don’t really know what is this project different from other folders and directories that I have on my laptop. Do you have any idea what kind of directory maybe a good test?

Yes, it is a local project on my computer. But I cloned it from github.

Also, I’m not sure if this is helpful, but I tried the searching in project function of some other text editors. Interestingly, Sublime Text reports the same errors like Atom, but it does not block the search result window. Additionally, if I use IntelliJ and use the option [import a project], this error does not occur. 

Thank you for answering my question! Hope this clues help!

**Comment by rsese** [comment]
Thanks for the extra details - since you're seeing similar errors in Sublime, it at least sounds like this isn't an issue specific to Atom?  And it also sounds like it's specific to this one project so I'm assuming you've cloned other Git repositories and had no problems?

Are there any permissions issues with the files mentioned in the output?  For example, can you edit and save them with no problem?

**Comment by sjg10** [comment]
I had exactly the same issue as reported above. 
(Atom 1.34.0 x64
Electron 2.0.16
Chrome 61.0.3163.100
Node v8.9.3)

The files throwing the Unknown error were found to all be 0 bytes, apparently a common on Windows 10.
Deleting those files and checking out again resolved the issue for me. This may have been due to file system corruption after SSD cloning.
