### ISSUE TITLE
Improve time to find on a large repository by using `ripgrep`

### ISSUE THREAD

**Issue by rafeca** [atom/find-and-replace#1075]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After seeing the big benefits that `ripgrep` has brought to `fuzzy-finder` ([more info](https://github.com/atom/fuzzy-finder/pull/369)), we want to explore what would be the impact on the time it takes to find something on a large project (which is not specially fast at the moment).

**Comment by BurntSushi** [comment]
Please let me know if there's anything I can help with here. Note that ripgrep does have a JSON output mode which should make this task much easier to get right, but its documentation might not be in an obvious place. Here's a link: https://docs.rs/grep-printer/0.1.1/grep_printer/struct.JSON.html

**Comment by rafeca** [comment]
Thanks @BurntSushi ! Really excited to integrate `ripgrep` in Atom and get some perf boosts!

I'll take a look at the JSON output docs

**Comment by rafeca** [comment]
We have a PR in `atom/atom` which adds `ripgrep` as a backend system for the `scanner`: https://github.com/atom/atom/pull/19348

Once that one gets merged we're going to be able to use it from this package 🎉

**Comment by rafeca** [comment]
Closing this issue, we're going to have an option for `ripgrep` powered search on Atom v1.39, and hopefully we're going to make it the default one very soon.

Thanks @BurntSushi for such an awesome tool! it's been a delight to integrate it on Atom ❤️
