### ISSUE TITLE
Project Find Result not mantain scroll position after open search file

### ISSUE THREAD

**Issue by abcreations** [atom/find-and-replace#1097]
**Description**
Clicking search result in Project Find Result and open file, when go back to Project Find Result the scroll position is lost.

**Steps to Reproduce**
Perform a project-wide search for "foo"
Project Find Results opens
Scroll bottom and click a search result in Project Find Results
The file opened
Go back to Project Find Results

**Expected behavior:**
After go back to Project Find Result the scroll need to mantain position.

**Actual behavior:**
After go back to Project Find Result the scroll position are lost.

**Reproduces how often:**
After update to version 0.218.15

**Versions**
Atom : 1.40.1
Electron: 3.1.10
Chrome : 66.0.3359.181
Node : v10.2.0

Windows 10

**Comment by calebmeyer** [comment]
I was able to reproduce this on my mac as well, so it looks like it's not OS specific. 

As a workaround, you can open up the settings for the find and replace package and set "Direction to open results pane" to right or down. I have mine set to right. I don't like losing the horizontal space, but it is nice to be able to click around between results.

**Comment by JeffAsSilent** [comment]
Thanks for the workaround !
I have the same issue for some days (same versions as @abcreations)

**Comment by adrian5** [comment]
Confirmed on Linux as well. Thanks for the workaround @calebmeyer ! I hope the issue gets some attention, and I suspect it's not a difficult fix.
