### ISSUE TITLE
Auto search while typing rather than hitting enter to search

### ISSUE THREAD

**Issue by mcolyer** [atom/find-and-replace#11]
When using Find to search a single file, you should be able to hit Cmd+G to find the "next" instance without ever having to hit Enter to execute the search. To be clear, Enter should still find the first instance, but Cmd+G should always find the next one.

For comparison, see Sublime Text or Google Chrome.

/cc @mdo I've moved your bug over here as that's where the new search hotness is happening.

**Comment by drKnoxy** [comment]
@benogle sorry for bringing up a closed issue, but is this supposed to advance the viewport to the next match? I tried reading the spec but didn't quite understand.

It does highlight as you type, but doesn't advance the viewport currently. Just trying to do my due diligence before opening an issue.

**Comment by benogle** [comment]
No, it doesnt by default, but there is a setting.

![screen shot 2015-11-30 at 10 53 06 am](https://cloud.githubusercontent.com/assets/69169/11481183/aef1b792-9750-11e5-83ae-96f0afa64862.png)

**Comment by drKnoxy** [comment]
Ahhh, thank you. I'm new to atom and still discovering all the bells and
whistles.
