### ISSUE TITLE
The Find/Replace feature does not work

### ISSUE THREAD

**Issue by Ephellon** [atom/find-and-replace#1111]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * **Yep** &mdash; Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * **Does not fix** &mdash; Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * **Found no solutions** &mdash; Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * **Does not match: atom/atom#4154, atom/atom#16390, atom/atom#6963, or atom/atom#7936** &mdash; Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * **Assuming problem in core package (N/A)** &mdash; Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When using the `Ctrl + F` or `Ctrl + Shift + F` (Find & Replace) with Regex enabled, the feature fails.

### Steps to Reproduce

1. Press `Ctrl + F` or `Ctrl + Shift + F`
2. Use a valid Regex in the "Find" area, such as `--\b` or `(--)\b`
3. Use a valid string in the "Replace" area, such as `?` or `$1?`
4. Notice that nothing will be replaced, **or** the replacement will be literal
  - such as `--apple` &rarr; `$1?apple`; it should be `--?apple`

**Expected behavior:**

Replace the current buffer(s) with the valid replacement string.

**Actual behavior:**

Either replaces the buffer(s) will literals, or does not replace anything.

**Reproduces how often:**

**100%** of the time: Safe Mode, fresh install, etc.

### Versions

| OS | Atom | Node | APM | Electron | Chrome |
| --- | --- | --- | --- | --- | --- |
| Windows 10 `x64` | `1.43.0` | `v10.11.0` | `2.4.3` | `4.2.7` | `69.0.3497.128` |

**Comment by Ephellon** [comment]
Hi, just saw this. It's not just that particular RegEx, I can put in others and still get `$1` (literal) instead of the match

**Comment by Ephellon** [comment]
I'll post more examples when I get home

**Comment by Ephellon** [comment]
Duplicate of #1110

**Comment by smtlaissezfaire** [comment]
Is there a way to downgrade packages?  This is a show-stopping bug for me.
