### ISSUE TITLE
cmd-f should close the pane

### ISSUE THREAD

**Issue by mcollina** [atom/find-and-replace#134]
The panel should be closed if a user hit cmd-f or alt-cmd-f again.

**Comment by philgyford** [comment]
I assumed that as there's a `find-and-replace:show` I'd be able to map my chosen keys to `find-and-replace:hide`... but this appears to do nothing. I guess I can use `find-and-replace:toggle` but it seems odd, and unexpected, for there not be a parallel `hide` matching `show`.
