### ISSUE TITLE
find/replace performance

### ISSUE THREAD

**Issue by jdc0589** [atom/find-and-replace#145]
there are some pretty serious issues with find/replace performance. I realize that some of this is an issue with speeding up marker displays in Atom core (and is supposedly already logged in the closed issue tracker), but i wanted to make sure there was a public issue as well. 

e. g. stripping newlines in a ~300 line file via `Find: "\r|\n"` and `Replace:""` can easily take over 10 seconds.

**Comment by Fank** [comment]
I also noticed if you searched something with RegEx (e.g. /,(\n+\t*)/, which were very slow, single core 100% usage) and stopped searching -> leave search "pattern" in search filed but closes the search view by pressing "Escape" the, is still slow, because it feels like its still searching the pattern after every content change. So when i open the search view again and disable the RegEx option and empty the search pattern and close it via "Escape" too, same as before. It runes fine/smooth.

Tested in atom 0.174 on Ubuntu 14.04 (Linux ***** 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux)
with a perl module (*.pm) about 760 lines

I could test this on windows too if desired

**Comment by Cipa** [comment]
For this file
https://gist.github.com/Cipa/62e40f9ac95d65ddcadd
I tried to remove the empty lines with find/replace(I just copied the empty space between 2 lines and tried to replace it with nothing) and currently I am at the 4th Keep Waiting message and it still did not do it. I think it crashed.

Same thing takes 5 seconds or less in Coda.

Atom 0.179.0, started in safe mode

**Comment by benogle** [comment]
Thanks for the test case. Sorry it's slow :(

**Comment by Fank** [comment]
Today i replaced a file with 15k lines all step by step (not replace all), and i noticed the first time i opened the file in atom i could nearly instand replace line step by step, after about 200 lines it getting slow (800ms/line). So i closed the file and reopened it (same atom session/window), it the time decreases to ~150ms foreach line, after some replacements (~200) it increases to ~2sec.
3., 4. ... same behaviour as the second opening, same times no time increasing.

I used this RegEx `,(((?:\s+--.*)?\r?\n)+\s+)+` with folling in replacement `$1,`, only the RegEx option were enabled.

Tested in 0.194.0 on linux same as my comment above, i hope this information help in someway.

**Comment by willopez** [comment]
This is the reason I don't use Atom as my main text editor. I want to spend time coding, not waiting for a tool. When I get some free time I will look into the possibility of using https://github.com/ggreer/the_silver_searcher as the backend and building an Atom plugin similar to https://github.com/rking/ag.vim

**Comment by benogle** [comment]
@willopez what specifically is slow for you? Is it search in buffer? In project? What are you searching for?

**Comment by willopez** [comment]
Specifically searching a project, my current project has 23,489 files including those in the vendor folder without vendor 2,085 files. I am searching for a word i.e Request. Further, building the index takes a while too. I currently use vim with the plugins mentioned above and the performance is great. Even my fuzzy file finder https://github.com/kien/ctrlp.vim uses ag for building the index.

**Comment by maletor** [comment]
+1 on the silver searcher.

**Comment by railrhoad** [comment]
Search in general on a smaller file takes a fair amount of time.  Doesn't matter how many files are included in the project.  I have a 30kb json file, replacing the 3000 quotes to double quotes took about 45 seconds time to do.

**Comment by jdc0589** [comment]
@railrhoad thats the exact type of thing I use it for a lot in other editors

**Comment by jdc0589** [comment]
[awesome news](http://blog.atom.io/2015/06/16/optimizing-an-important-atom-primitive.html) with the marker performance guys! cant wait.

**Comment by nathansobo** [comment]
@jdc0589 It's worth noting that *creating* markers could still use some optimization. But once they're on screen life should be much better. Stay tuned.

**Comment by sublines** [comment]
I would like to add another performance issue to the discussion. 
When you work on several files at once (which we do all the time) and you're in a file and search for something but then switch back to another file without closing the search first, it will automatically also search the file you went back to or any newly opened file. 
I always leave the search bar open after I've searched for something and of course I'm glad it doesn't close automatically when you change to another file. 
But please, add a settings function to disable auto searching everytime you switch between files or open a new one.

**Comment by JeremybellEU** [comment]
My editor also reports to keep on hanging when performing the regex
`\\n`
I need to replace all `\n` with actual endline characters. This regex on a file with 2900 matches found is currently taking a couple of minutes before finishing.

**Comment by benogle** [comment]
This has been improved significantly via a new marker index which is currently in master. Check out these PRs for more information

* TextBuffer treap-based index: https://github.com/atom/text-buffer/pull/109
* Optimize markers via new layers API and treap-based index: https://github.com/atom/atom/pull/9426
* Use new index in FNR: https://github.com/atom/find-and-replace/pull/588
* Drop the marker index to C++: https://github.com/atom/text-buffer/pull/114

As with any performance things, more work can always be done, and we have ideas. We will create more specific issues moving forward.

**Comment by jdc0589** [comment]
thanks a bunch @benogle!  I've actually been using atom some more recently (as my preferred markdown editor) and have noticed some solid marker improvements.
