### ISSUE TITLE
There's no way to exclude paths from a search

### ISSUE THREAD

**Issue by mattbasta** [atom/find-and-replace#149]
When searching, filters can be specified. However, there's no way to exclude paths from the search. 

E.g.: `*.js, -*.min.js` cannot be used to exclude minified files from a search of JS

**Comment by msisto** [comment]
+1

**Comment by drw158** [comment]
It'd be great to get someone working on this. The solutions I see here don't apply to me.

If I'm doing a find and replace and want to exclude one of the files in the results, it's impossible. For example, if I want to replace `$light-blue` with `$blue` for every file *except* for `colors.scss`, it's not possible.

**Comment by backspaces** [comment]
I'd like to eliminate "derived files" from my searches .. i.e. min.js, docco directory (documentation generated from src/ files), tools/ (.js files used in demos, not the project) and so on.  I'd like to do this on a per-repo basis.

Thus far it seems like atom does not search node_modules (and other files in my .gitignore file?).  I'm not sure why folks are seeing node_modules in their global searches .. they are typically not included in the repo, but referred to by package.json.

Apparently all I have to do is put the dirs I want to search in the "pattern" line of the global search pane.  It would be nice to automate that, somehow.  Not sure if best to have "positive" or "negative" i.e. include or ignore semantics.

   -- Owen

**Comment by AGregg** [comment]
In the case of excluding a directory for a find and replace, my current workaround is to make sure my directory is clean, do the find and replace, then go into git bash and type `git checkout <directory>/.`

I would definitely like this feature to happen, but hopefully this can help people in the meantime.  @drw158

**Comment by brendanfalkowski** [comment]
The ability to exclude folder's is very important to me. For Magento projects, there are sometimes 4 or 5 versions of the same file due to theme inheritance. Example:

```
/app/design/frontend/base/default/template/...
/app/design/frontend/default/default/template/...
/app/design/frontend/enterprise/default/template/...
/app/design/frontend/rwd/default/template/...
/app/design/frontend/custom/default/template/...

/skin/frontend/base/...
/skin/frontend/default/...
/skin/frontend/enterprise/...
/skin/frontend/rwd/...
/skin/frontend/custom/...
```

Only the `custom/default` files are being opened/edited 99% of the time.

**In Sublime Text,** I can exclude the other folders:

```javascript
{
"folder_exclude_patterns":
    [
        ".git",
        "*/frontend/base",
        "*/frontend/default",
        "*/frontend/enterprise",
        "*/frontend/rwd",
    ]
}
```

Sidebar: I don't like that Sublime also hides those folders from the tree. I do still need access to them occasionally.

**In Atom,** you can't exclude paths or use wildcards. You can only add individual folders to "ignored names":

```
.git, base, default, enterprise, rwd
```

But this is way too generic because it hides wanted folders/files. So it's not useful.

When you "find in project" for "pageheader.phtml" you should be able to configure seeing only your theme files. But now you have to scrutinize the list to select yours among all themes, it's very annoying.

Ideally, you could set exclusions per project (Atom should make "project-manager" a core package). It would be nicer if (like Sublime) this was simply JSON and you could comment out lines temporarily. Otherwise if global, it needs to be simple to toggle folder exclusions on/off (not a long text input).

**Comment by danielweck** [comment]
+1 to mimic SublimeText `folder_exclude_patterns` and `file_exclude_patterns` on a per-project basis, except that SublimeText maps its search-index with the files/folders shown in the folder tree view ... which isn't really adequate (especially as this behaviour cannot be deactivated, i.e. if my 'build' folder is excluded from search, then I cannot browse it in the folder tree view).

**Comment by ilianaza** [comment]
+1 very important feature!

**Comment by Kuzirashi** [comment]
+1, it's crucial for code editor.

**Comment by lmartins** [comment]
Another annoying +1 on this one too. Surprised to find this is default behaviour yet.

**Comment by thomasjo** [comment]
Given all the +1's, I'm really surprised that nobody in the community has opened a PR yet... this is open source, so if you desperately need a feature, contribute instead of complaining.
There are many of us who would love to provide you with guidance, testing, and what not.

**Comment by lmartins** [comment]
@thomasjo You're absolutely right, I probably extended my comment too much, but when I say annoying it was just self awareness of the fact that all those +1, including mine, are a bit annoying considering what you said. 
For my part, I don't do it myself as im afraid is a task over my skills.

**Comment by kylegoetz** [comment]
I can already search for strings using regex. Why can't that code just be extended to apply to the file/directory pattern field like it already does for the find-in-project field? That seems best to me: if you search using regex in one field, it should be applied to all fields. Otherwise, I have to think about escaping . characters and stuff in one field but doing a totally different syntax in the other field, and that gets jarring.

**Comment by jehoshua02** [comment]
@thomasjo Let's be realistic. It's probably going to take more time than many of us can afford to get familiar enough with the code and process to submit a PR. We have jobs and most of us would get in trouble for going on a tangent to fix our editor.

**Comment by kylegoetz** [comment]
If I'm reading the code right (I don't know CoffeeScript), there is a file in src called scan-handler.coffee that imports scandal, which performs path scanning using minimatch. Minimatch supports regex, but Scandal appears to have omitted incorporating Minimatch's support of regex matching.

So I might take a look at this sometime, but it doesn't look like adding it would be too hard.

**Comment by Igor10k** [comment]
Even though some of you point to Sublime Text, I'd like to introduce you to they way TextMate handles exclusions and honestly I think it's the best solution possible. TextMate has a list of config variables that give you the flexibility to set things up for the optimal performance and usability.

```
excludeDirectoriesInBrowser
excludeDirectoriesInFileChooser
excludeDirectoriesInFolderSearch
excludeDirectories
excludeFilesInBrowser
excludeFilesInFileChooser
excludeFilesInFolderSearch
excludeFiles
excludeInBrowser
excludeInFileChooser
excludeInFolderSearch
exclude
```

Not sure if these variables require any explanation. Compared to this even Sublime Text falls short.
You can of course use this feature per project and/or globally. This feature alone is the main reason I always switch back to TextMate.

**Comment by kylegoetz** [comment]
OK I forked and cloned Atom and have loaded it with atom --dev and have opened /src/scan-handler.coffee and, to make sure I'm doing this right (never hacked on Atom before), and added

console.log "Foo"

as line #1 in the file, saved the file, and did ctrl-cmd-alt-L to reload. The developer console does not ever show this log. How do I get started implementing a solution? The docs are bereft of how to edit the core of Atom. They just talk about creating new plugins/extensions/whatever they're called in Atom.

I'm going to implement regular expressions for directories and not just the filenames themselves. Then I'll do a PR. If Atom rejects it, that's fine. But at this point, lack of regex in paths has added hours and hours of development time, and if no one else is going to do it, then I'm going to get it done, at least to my satisfaction. It shouldn't be too hard. The Regexp package is already loaded and the path search backend (scandal, minimatch) already supports it. Just for some reason Atom doesn't.

**Comment by jaspervalero** [comment]
+1 This is a fundamental feature that should be supported in any code editor/IDE from day 1. Please treat this with some priority. Thank you!

**Comment by kylegoetz** [comment]
I implemented regex support in the Project search path field today and just created a pull request. We'll see if the maintainers accept my PR or want to modify it in some way. It works for me, and I'm going to keep using it, so if you're interested in the same, here it is: https://github.com/atom/find-and-replace/pull/420

**Comment by serapath** [comment]
is there an estimate when this might feature might become available?

**Comment by kylegoetz** [comment]
If you're referring to my implementation (not sure if you are), then I need to write a comprehensive unit test suite for it. But I have to learn how to do that first, and find time in my insanely busy actual job and life schedule to do it. So no estimate, but I would hope in the next couple weeks I could complete some tests.

After that, I imagine the people in charge would have to discuss internally whether they like my solution and want to include it or not. That part, I have no idea about, so would defer to someone else who knows like benogle.

**Comment by mbrammer** [comment]
+1 Please add ignore pattern

**Comment by zeroedin** [comment]
:+1:

**Comment by icetraxx** [comment]
+1

**Comment by Fire-Dragon-DoL** [comment]
Has this been added? I'm waiting **specifically** for this feature to start using atom

**Comment by kylegoetz** [comment]
I added the ability to do regex path filtering to my fork but need to implement unit tests before I think Atom will even consider a pull request (understandably so). I just don't have time to learn how to do create unit tests for this right now with work and home life. You're welcome to take a look at my fork and implement unit tests if you want.

**Comment by miloszw** [comment]
This issue is almost 1,5 years old. It's beyond me why the atom dev team doesn't see this as a priority... +1

**Comment by RiFi2k** [comment]
Trying doing a find a replace " for ' 34000 times on 2 full websites...
At least I use git
Needs fixed bad

**Comment by scott-kennedy** [comment]
+1 - Can't use the editor without this feature.

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! However, all these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – we may unlock it once someone starts working on this enhancement to get further feedback.

**Comment by benogle** [comment]
A fix for this will be in atom 1.0.3 tomorrow.

**Comment by benogle** [comment]
See https://github.com/atom/scandal/pull/29 for a little bit about handled cases.

**Comment by swrobel** [comment]
:clap:

**Comment by Fire-Dragon-DoL** [comment]
That's **great** downloading atom, preparing for tomorrow.

**Comment by acusti** [comment]
:tada:

**Comment by miloszw** [comment]
It seems now that VCS ignored paths are no longer excluded from the results. Is it just me?

**Comment by Fire-Dragon-DoL** [comment]
mhhh did you try with these syntaxes?

```
inclusions: []
exclusions: []
globalExclusions: ['vendor/', '*.pyc']
```

(I didn't test it yet, so I don't know)

**Comment by Fire-Dragon-DoL** [comment]
I tested with:

```cson
# projects.cson
'MyProj':
  'title': 'MyProj'
  'exclusions': [
    'node_modules/*'
  ]
  'paths': ['/Users/myuser/Projects/MyProj']
```

With ctrl + P, node modules directory is still included entirely, making it unusable.

**Comment by sasikanth513** [comment]
I've added ".git, .meteor" to the Ignored Names and enabled both "Hide Ignored Names" and "Hide VCS Ignored Files" in `tree-view` settings.

Still search results are showing from those folders.

**Comment by benogle** [comment]
It will search the git ignored files when you explicitly call out an ignored folder like node modules.

Can one of you open a new issue with the following info:

* exactly what you are putting in each input in the find in project panel
* the output of the following on the atom dev tools:

  ```js
  atom.config.get('core.ignoredNames')
  atom.config.get('core.excludeVcsIgnoredPaths')
  ```

Mine

![screen shot 2015-07-29 at 11 56 17 am](https://cloud.githubusercontent.com/assets/69169/8966923/dd0a4a8c-35e8-11e5-945b-13f40d32f6e3.png)

**Comment by benogle** [comment]
> With ctrl + P, node modules directory is still included entirely, making it unusable.

I dont understand what this means. Can you elaborate in a new issue with very explicit steps?

**Comment by Fire-Dragon-DoL** [comment]
@benogle yes, but I want first to understand if i'm setting options correctly in the right place. I'm doing it in projects.cson

**Comment by benogle** [comment]
Open the settings view with `cmd-,`

![settings](https://cloud.githubusercontent.com/assets/69169/8967075/a48aed3c-35e9-11e5-9dd8-49b2a5310f9e.jpg)

These are the settings that will affect find and replace (along with `.gitignore`).

**Comment by Fire-Dragon-DoL** [comment]
Uhm, what you point out works. I mean, after adding it (and reloading project so it reindexes), ctrl + p  (and find) don't look into node_modules anymore. Good.

Although, I was sent here from a bug which stated it should be possible to configure this on a per-project basis. Is this possible?

**Comment by benogle** [comment]
> Although, I was sent here from a bug which stated it should be possible to configure this on a per-project basis. Is this possible?

Maybe with a package. This issue only affects find-and-replace, not the command palette or the fuzzy-finder.

**Comment by Fire-Dragon-DoL** [comment]
Mh ok thanks.

I'm testing with find (I'm not replacing, does it matter?), with node_modules in ignoredNames, it doesn't find the text "coffee-script/repl" (which is the content of a file in node modules), however when I remove "node_modules" from ignored names I still can't find that (I restarted the editor). Probably it needs reindexing but I can't find a way to force it. The only way I found is adding the pattern `**/*` which allowed me to find the text either if it's in ignoredNames or not

**Comment by benogle** [comment]
Can you make a new issue? Each comment on here notifies 50+ people.

**Comment by Fire-Dragon-DoL** [comment]
@benogle https://github.com/atom/find-and-replace/issues/466 I can't stress this enough, I'm not sure if this is a bug.

P.S.
Project manager allows per-project settings so fixed my problem from this point of view. Although, I can't get "negated" paths to work. if I add !node_modules it includes **only** node_modules directory

**Comment by nicolas-van** [comment]
My case is quite simple, in 1.0.7 I have this: 

    atom.config.get('core.ignoredNames')
    [".git", ".hg", ".svn", ".DS_Store", "._*", "Thumbs.db"]
    atom.config.get('core.excludeVcsIgnoredPaths')
    true

And yet when I make a search in my project I can find results in my `.git` folder.

**Comment by cluxter** [comment]
Not working for me in Atom v1.0.10 in Windows 7.
Here is the result of the commands in the console:

```atom.config.get('core.ignoredNames')
[".git", ".meteor", ".semantic-ui", ".git\"]
atom.config.get('core.excludeVcsIgnoredPaths')
true```

Yet when I right-click on my project root folder, click on "Search in Directory" and search a word, results from ".git" folder are shown.

However it works when I add this in the "File/Directory pattern":

```
!.git/
```

Am I doing it wrong or is it a bug? I tried everythink I could, including modifying the "config.cson" file and adding the "exclusions" line. Nothing is working.

**Comment by MichaelJCole** [comment]
I just edited my config an got something like this to work.  I added an ignoredNames section to my config.cson (Preferences -> Open Config Folder -> config.cson):
```
"*":
  core:
    autoHideMenuBar: true
    ignoredNames: [
      ".meteor"
      ".git"
      "etc"
    ]
```
and don't get results in these directories:
```
/etc/*
/src/.git/*
/src/admin/.meteor/*
```
Not saying there isn't a bug, but this worked for me on 1.0.7 on Linux Mint

**Comment by TerrenceLJones** [comment]
@MichaelJCole This works for me as well on 1.0.15 on Mac O.S.

**Comment by jagc** [comment]
@MichaelJCole Thank you. Worked for me at 1.0.19.

OS: Windows 7 Ultimate SP1 64bit

**Comment by Samuel-Graham** [comment]
Just use commas and start the path from the root project directory. Works well.

**Comment by PierBover** [comment]
Is there a way a exclude files from the command "find file"?

I've added `.jpg, .png` in the ignored names setting but they do still appear there.

**Comment by CharlesMcKeever** [comment]
Bless you @MichaelJCole Works for me on 1.0.19 on OS X El Capitan. You are awesome!

**Comment by chung-leong** [comment]
Feature is still buggy in 1.1.0. A file can still pop up if the path matches the file/directory pattern. I.e. If you do "Search in directory", files in ignored folders will show up.

**Comment by benogle** [comment]
> If you do "Search in directory", files in ignored folders will show up

Can you make a new issue giving the exact values you have in each text box + if possible, a test repo? I know it will do this in some case due to some ambiguity.

**Comment by proehlen** [comment]
@MichaelJCole Thanks so much for that man.  Works well and removes a major frustration with Atom for me.

**Comment by jldec** [comment]
See #621

**Comment by kevin-smets** [comment]
@MichaelJCole thanks for that quick fix. I added 2 project which led to 2 million files being indexed, it was crazy... 

Imho it should be as easy as right clicking on a folder - exclude from index or something, where you could then take just that specific folder, or use it as a pattern.

**Comment by leongaban** [comment]
Ok I finally got this working, had to add `.sass-cache` into my config.cson file, now when I fuzzy search I don't get `.scssc` files

`core:
    closeEmptyWindows: false
    ignoredNames: [
      ".scssc"
      ".sass-cache"
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "Thumbs.db"
      "node_modules"
    ]
    themes: [
      "atom-material-ui"
      "atom-material-syntax"
    ]`

**Comment by lope** [comment]
+1 @MichaelJCole @leongaban 
Your config.cson hack worked for me.

Trying to exclude paths by typing them in the search does not work for me.
Trying to exclude paths using .gitignore (with "Ignore VCS" enabled in Prefs) does not work either.

**Comment by konstantinmagg** [comment]
+1 Would be great to ignore folters (bower_components or node_modules) in the search bar.

@leongaban your solution worked for me, too. thx ;)

**Comment by ocssor** [comment]
Right Click -> Search in directory

Still searches in '.svn' despite that being in ignored names (both in core settings view and in config.cson).

**Comment by akmur** [comment]
Thanks @leongaban

**Comment by MichaelJCole** [comment]
FYI, this bug is closed.  Posting here doesn't help fix your issue, and emails a bunch of people who can't help.  For best results, please open a new bug.  Thanks!

**Comment by MichaelJCole** [comment]
FYI, this bug is closed.  Posting here doesn't help fix your issue, and emails a bunch of people who can't help.  For best results, please open a new bug.  Thanks!

**Comment by MohammedAl-Mahdawi** [comment]
In order to search in a folder within my project folder and ignore the `.git` folder within it, I did the following
![selection_108](https://cloud.githubusercontent.com/assets/5562839/16322953/a781ead4-39af-11e6-82ed-3eb9b2f5835b.png)
Just added `, !.git` after my folder path.

**Comment by stringaro-leo** [comment]
this works for me: !**/node_modules/**,!**/bower_components/**

**Comment by findsje** [comment]
Thanks, this worked for me. Was giving up on this! **/*.html was what I needed.

**Comment by eugenealegiojo** [comment]
Nice! This works for me as well: `!*.min.js`

**Comment by mrahulreddy** [comment]
This works for me 
`!node_modules`

**Comment by jorgeorpinel** [comment]
Not working at all for me ):

![image](https://user-images.githubusercontent.com/1477535/37016607-17c3a148-20db-11e8-8698-98fe47bfc5b5.png)

**Comment by jrial** [comment]
@jorgeorpinel could it be that your file was not saved at that time? If so, see #647

**Comment by spencerspear** [comment]
Just ran into this issue myself. I wanted to find all instances of a keyword within a directory, but wanted to exclude the search from a single nested directory within. 

**Demo File Structure:**
```
project-name/
    search-this-directory/
        ...
        ...
        ...
        exclude-this-directory/
            ...
            ...
            ...
```

**File/Directory Search Pattern - FAILS**
```
project-name/search-this-directory, !project-name/search-this-directory/exclude-this-directory, 
```

After several attempts, I found that each additional file/directory pattern built on the previous... Therefore, in order to ignore the nested directory, we simply ignore that one single directory after defining the search context.

**File/Directory Search Pattern - WORKS**
```
project-name/search-this-directory, !exclude-this-directory, 
```
