### ISSUE TITLE
Find in Selection

### ISSUE THREAD

**Issue by ethanmcc** [atom/find-and-replace#154]
Ran into a case today where I need to find and replace in a selection today and had to resort to another editor. Would be a cool feature to have in Atom.

**Comment by nicomacme** [comment]
Hi @ethanmcc,

I can't seem to find that button anymore. The button seems to be replaced with the "Whole Word" button.

**Comment by bkfunk** [comment]
I have an issue where if I do a find in selection in one selection, and then select another selection, suddenly doing "replace all" will replace within entire document. It's very wonky, and I'm never sure how to keep it from doing the wrong then. I try escaping, then toggling the in-selection button, and retyping the search phrase (which seems to work best). Also, it'd be great if, if I select a block of text, then do a find, that it will default to finding within that selection.

**Comment by SSPJ** [comment]
Reproducible steps for replacing text in multiple selections (running 1.19.2 on Linux):
1. select the first block with Only In Selection turned OFF
2. turn it on
3. click Replace All
4. select the next block
5. click Replace All
6. click inside the editor, hit Ctrl-z to fix the bad replacement
7. click Replace All again
8. repeat steps 4 through 7 for each selection block you want to replace inside of

**Comment by cotterjd** [comment]
Where is this button at? I'm not seeing it...
![screen shot 2018-06-01 at 2 58 53 pm](https://user-images.githubusercontent.com/2576700/40860816-6524fd5e-65ac-11e8-91e8-17336f8a344e.png)

**Comment by davidhealey** [comment]
It looks like this in the latest version:
![image](https://user-images.githubusercontent.com/14021202/174589504-27df2f81-4212-4ef2-8619-0d5a2e5f95fc.png)
