### ISSUE TITLE
Does not use system-wide search clipboard

### ISSUE THREAD

**Issue by pcasaretto** [atom/find-and-replace#162]
The Mac OS has a nice feature which this package does not use. There is a separate clipboard for "find" items which is shared between applications. You can copy text to it in any Mac application by highlighting it and pressing Command-E, then search for it in another by pressing Command-G, or you will find it already present in the second application's find dialog.

**Comment by nemoDreamer** [comment]
:+1: Agreed: Sublime Text does this, and it's brilliant to search between your editor and browser, for example.

**Comment by benogle** [comment]
Closing in favor of https://github.com/atom/atom/issues/4650 which has more info / activity
