### ISSUE TITLE
No way to hide the Find/Replace Pane

### ISSUE THREAD

**Issue by jamiepeloquin** [atom/find-and-replace#164]
I can not seem to find a way to get rid of the Find/Replace pane in the editor. I have tried various shortcuts (⌘P, ⌘T , ⌘⇧F) and options via Find menu. So far, the only way to close the Find/Replace pane is to close the entire window.

**Comment by reggieb** [comment]
Just started using Atom. Not having a visible way to close the search panel was a pain. Googling got be the Esc option, but I know I'm going to have to do that google again some time (I'm getting old and don't have a great memory). I hate systems where you need to know 'magic' keystrokes to do anything. A small x as suggested here takes up minimal screen space, and in common practice in more windowed user interfaces. 

As for users learning the key command - they'll learn it if it is useful to them. If not your only going to alienate some of the user base by making it difficult for them not to.

Perfect solution for me would be x to close. Hover over x to see keyboard alternative.

**Comment by jeffmcneill** [comment]
Aggree with @reggieb the lack of a visual cue (x), and needing to read instructions or remember a keyboard command (esc) is a step back in modern usability. http://www.nngroup.com/articles/recognition-and-recall/

**Comment by sotomo** [comment]
Esc is fine with me.  Rouge X buttons confuse me.  

IMO, the larger problem is that the search pane is not really a window or pane (that can be moved around).  I recommend making the search area a window or pane, then an X button would make more sense.

**Comment by jeremykoerber** [comment]
I had this problem for a while and nothing was working. It turned out to be an issue with the git-diff-details package. I disabled it and I was able to close the find panel with ESC again. Found the issue by using the toggling the keybinding resolver and hitting ESC.

**Comment by ea167** [comment]
I'm new to Atom, and ESC is NOT intuitive AT ALL. 
I had to google it after deep frustration. Not good for such a basic feature as Find.

You should definitely go with a X button, and tooltip the "Esc" when hovering

**Comment by ojwoodford** [comment]
X button to close the find panel, please. :+1:

**Comment by DaClone** [comment]
I'm also new to Atom and found the lack of any obvious way to close the search pane.
I, like some other people here, had to Google it.

A X button (or really any button at all) to close it with a tooltip for ESC would solve it easily.

**Comment by Vloz** [comment]
As said, that's 100% not intuitive.

**Comment by FoolishFrost** [comment]
Jast had to search to figure this out as well, and I'm a mac/pc/linux programmer that goes back to the C64 and vic20 era.

This sounds like you guys are attached to a sacred cow, not a design methodology.  The X is now a universal constant that offers a visual cue in how to close something.  While having escape to close is good, you have to remember you are in a GUI, not just a UI.  This means visual cues and options to do things as well as keyboard methods.  Right now, you're a step away from saying "But CTRL-ALT-4-S is a perfectly good way to open..."

Considering that you just said you don't want to change it, and it's your project, then you have to do what you have to do.  Just understand that you're making hard on new users, and that means they use something else if it happens too many times.  They're fickle that way.

**Comment by felixjung** [comment]
Anyone having issues with this: getting toggle behavior really isn't hard. Just edit your ``keymaps.cson`` like this:
``` cson
# Toggle find panes
'.platform-darwin':
  'cmd-F': 'project-find:toggle'
  'cmd-f': 'find-and-replace:toggle'
```

This will cause the toggle to happen when you press the shortcuts. With project-find this currently has the disadvantage that you're not being focused on the search input. However, you can a) change the shortcut and b) I'm sure it wouldn't be hard to write a tiny package for this.

**Comment by elharo** [comment]
This UI is very confusing. Good that esc works, but it needs a close button.

**Comment by whiterosecoffee** [comment]
The first thing every single one of us with an issue tried was a second find shortcut.  This is natural UI, does not affect visual layout and easy to make consistent for all relevant "toggle" panes.  No need for a close button.

**Comment by JonWel** [comment]
In gedit, the search (without replace) disappears when clicking in the text. This makes the "how to make that thing disappear?" question self resolved, but I don't like it so much because this doesn't allows to keep it open either.

An alternative could be to add an entry in the find menu with "Close search pane      ESC", just under the Find and replace.
That way, there is a possibility to know the command without googling it, and it does not overload the rest of the interface.
In File, there is a "Close pane", but not being native English speaker, I have no idea of what a pane is (tab, pane, window, I can't really tell witch one is targeting the small band appearing at the bottom of my screen), plus that entry has no shortcut written and is not working to close that pane (I have version 1.8.0).
But "Close tab      CTRL+W" is working (both the entry and the shortcut). Which ends up to tech an other shortcut than the more convenient ESC.

**Comment by cantonic** [comment]
For me not even ESC closes the pane. Any ideas what could be causing this? I am on Mac OS X 10.11.6 with a german keyboard.

**Comment by pictor-cogitationis** [comment]
This shouldn't be closed as it's obviously still causing people problems unnecessarily.

I'm a lead developer and experienced UI/UX designer. I tried looking for an "x", repeating the "Find" shortcut command, right-clicking on the Find pane, and searching for a menu item in all of the menus. Then, after wasting considerable time trying to figure out something that should have been really simple, I gave in and did a Google search which brought me here.

Using "Esc" for those who know it is great. But you absolutely should have an "x" for beginners or for those who simply don't feel the need to learn a shortcut. It can be subtle, but it should be there. I've now lost twenty minutes to my "productivity" tool.  :(

**Comment by luongs3** [comment]
just use "Esc"

**Comment by benlogan1981** [comment]
Very silly! Should toggle or allow closing via UI...

**Comment by 50Wliu** [comment]
Please stop commenting on this issue and subscribe to #347 instead.  Thanks.

**Comment by dkaushik94** [comment]
@kevinsawicki Dude I have been trying this for quite a while today. And I read your comment and did it. LMAO. Just had to press ESC. Haha. Lmfao. Unreal.

**Comment by sigdestad** [comment]
An x would have been nice, just spent 4 minutes figuring out that esc solves it..

**Comment by danielcroft** [comment]
It's hilarious to me that we're "training" people to use a keyboard option in a graphical interface and not providing a button or, menu option of some kind. There are conventions for a reason. I spent some time looking for a dock/hide/whatever menu option, went into the appearance options and then eventually found this bug, I'd agree, it's a bug. I'd politely suggest that providing only one way of doing things that doesn't match the expectation of users isn't the best approach to a UI/UX problem.

**Comment by FoolishFrost** [comment]
I would like to point out something, and then I'm unsubscribing from this thread and washing my hands of this.

It has been three years, and people have regularly advised ESC is not intuitive.  The irony is, he's just making work for himself by having a regular flow of people sending in bug reports that there is no close button.

This is a shining beacon that has reminded me for years not to think I can't be wrong, and to adapt my thinking to the reality of the situation.

**Comment by welkie** [comment]
It's not even that it's not intuitive. I was able to figure it out. I just had issues closing it when my keyboard stopped working. It's also ironic that free software is supposed to be accessible for everyone in the world but that is clearly not being followed here.

*Begins searching for virtual keyboard software for his Linux distro so he may be privileged enough to be allowed to close his ctrl-f dialog*

**Comment by 50Wliu** [comment]
I'm locking this issue since it has been closed for quite a long time now and I want the discussion to be moved to #347 so that it doesn't get lost as easily.  Feel free to move your comments there!  Just remember to keep the conversation civil and in accordance with the [Atom code of conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) :smile:.

**Comment by 50Wliu** [comment]
#885 has been merged.  Expect to see a close button starting with Atom 1.19.0.
