### ISSUE TITLE
Unable to copy selection (all results)

### ISSUE THREAD

**Issue by chamons** [atom/find-and-replace#184]
You can't copy paste the results of "Project FInd Results". This makes further filtering by other tools impossible and it worse that grep.

**Comment by edrex** [comment]
I think the more common need is to copy the entire file, or an arbitrary section. In fact, I think the patch is blocking copying a selection (I can select text in the results window by dragging from row padding)

**Comment by fgalarza** [comment]
+1 - I often find the need to copy text from the results page. It would be nice to be able to save/export the Project Find Results as a text file.

**Comment by kristenward** [comment]
+1 - I often find the need to copy or save the entire set of search results.

**Comment by benogle** [comment]
Can you make a new issue?

**Comment by johnjelinek** [comment]
@benogle: did someone add a new issue for this problem yet? I need to screen-scrape the find results window.

**Comment by benogle** [comment]
No one made a new issue. You shouldnt need to screen scrape. As a temp workaround, you can dig into the model. After you do a search, open the console and enter these two lines:

```js
pack = atom.packages.getActivePackage('find-and-replace')
pack.mainModule.resultsModel.results
```

Also the `resultsModel` has a bunch of events you could subscribe to like `resultsModel.onDidAddResult`. 

Anyway, the long term option would be to add a command to copy the entire contents of the result set.

**Comment by thenikso** [comment]
Following @benogle hint I did:

`⌘ + ⎇ + i` → `Sources` → `Snippets` and create a new snippet with:

```javascript
var pack = atom.packages.getActivePackage('find-and-replace');
var results = pack.mainModule.resultsModel.results;
var resp = [];
for(var r in results) {
  if(results.hasOwnProperty(r)) {
    resp = resp.concat(results[r].matches);
  }
}
var matches = resp.map(r => r.matchText);
matches;
```

You can then right click it and `Run` to have the output on your console. right click the result on the console and `Store as Global Variable` then `copy(temp1)` to copy the result to the clipboard.

**Comment by tfoote** [comment]
I still can't copy the whole result, new ticket at: https://github.com/atom/find-and-replace/issues/738

**Comment by zohozer** [comment]
@thenikso Hi mate. Followed your instructions but instead of the desired result I'm getting the following errors into console (using the Atom 1.15.0):


[-1489955795362.log.txt](https://github.com/atom/find-and-replace/files/853551/-1489955795362.log.txt)
