### ISSUE TITLE
Ability to change highlight color in preferences

### ISSUE THREAD

**Issue by 34code** [atom/find-and-replace#206]
It would be great if there was an ability to change the highlight color in preferences via CSS for this module -- e.g. One might want all search results highlighted yellow for instance.

**Comment by senpost** [comment]
It seems to be not working, here is my stylesheet and screenshot,

![image](https://cloud.githubusercontent.com/assets/679076/6084310/7247b49e-adf5-11e4-801d-3c84d7947a69.png)
```css

/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

// style the background and foreground colors on the atom-text-editor-element
// itself
atom-text-editor {

}

// To style other content in the text editor's shadow DOM, use the ::shadow
// expression
atom-text-editor::shadow .cursor {

}

.search-result .match.highlight-info {
  background: yellow;
}

**Comment by lee-dohm** [comment]
See the reply on [Discuss](https://discuss.atom.io) for an updated solution:

https://discuss.atom.io/t/how-to-change-find-and-replace-highlight-color/14750
