### ISSUE TITLE
Find next/previous occurence of word under cursor

### ISSUE THREAD

**Issue by thomasthorsen** [atom/find-and-replace#210]
This is a request to add functionality similar to find-next/find-previous but automatically pick up the word under the cursor as the current search term (and don't open the search box). Subsequent uses of find-next/find-previous will also use this word. The natural key-binding is ctrl-f3 and ctrl-shift-f3 (for Linux at least, but also Windows assuming that find-next/find-previous is moved to f3/shift-f3 which is very common in Windows programs (including Sublime Text))

**Comment by lazutkin** [comment]
:+1:

**Comment by benogle** [comment]
Closed by #376
