### ISSUE TITLE
How to close the search panel?

### ISSUE THREAD

**Issue by ghost** [atom/find-and-replace#215]
Any command to close that?

**Comment by Vloz** [comment]
i agree, please add a graphical button.

**Comment by ORESoftware** [comment]
+1 graphical x

**Comment by erinknight242** [comment]
Agree, graphical x would be helpful. Esc is not intuitive.

**Comment by lucasbsilva** [comment]
+1 graphical X, I had the same issue.

**Comment by mspiegel** [comment]
+1 graphical X

**Comment by denapey** [comment]
+1 graphical X Please

**Comment by KolyaKorruptis** [comment]
+1 graphical X

**Comment by SystemLogoff** [comment]
+1 gui x

**Comment by 2pha** [comment]
+1

**Comment by Stefanqn** [comment]
+1

**Comment by jonaramos** [comment]
+1 graphical X or right click "close panel"

**Comment by joshuapack** [comment]
In the latest 1.7.4, I have been unable to close the find panel with `esc`. Not sure if plugin issue or something else. A graphical X would help in cases like this. I have to keep it there until I have time to figure out if it is a plugin or not.

**Comment by lucasbento** [comment]
Please stop commenting on this, as mentioned on #683, the maintainers are not interested into a graphical close button.

**Comment by jonaramos** [comment]
I just found a bug in the find bar. If you have "selected" text option you
can not select "match-word" at the same time, cause it disables "selected"
option.


https://linuxcounter.net/cert/502483.png

*********************************************
The definition of myself:

struct jonathan.ramos {
   char *lifeStyle = action(HaveFun);
   char *respect2 = noPcUser("Mi-Viejo")
   ostype os = Linux(Arch(gnome-shell-3.2);
   char *gaming = "Battlefield 3,Starcraft 2";
   quote = "Santa Cachucha!!!";
}

*********************************************

**Comment by xhlwill** [comment]
I found that the find panel couldn't be closed if I enabled vim-mode, if vim-mode is disabled it can be closed

**Comment by charlesqwu** [comment]
+1 graphical X

**Comment by Alphavader** [comment]
came here for this  +1 for graphical!!!

**Comment by JeffGreenlee42** [comment]
+1 for graphical!

**Comment by mariospassaris** [comment]
+1 for graphical

**Comment by Ben3eeE** [comment]
Graphical close button has an open issue: https://github.com/atom/find-and-replace/issues/347.
