### ISSUE TITLE
"Only in selection" icon is misleading

### ISSUE THREAD

**Issue by tobia** [atom/find-and-replace#231]
This ext. uses a double quote symbol for the "Only in selection" find option. But that icon and its button placement is the same as Sublime's "Whole word" option (which does a `\b...\b` search.) It took me a few minutes to realize why my search was not working.

It would be better to use a different icon, maybe the word `Sel` or an icon that looks like a selection with a cursor beside it: ▇▇ ▏ or maybe a multi-line selection: ▄██▀ (I hope the Unicode-art shows something)

**Comment by mnquintana** [comment]
Fixed in https://github.com/atom/find-and-replace/pull/390
