### ISSUE TITLE
Add select-previous command

### ISSUE THREAD

**Issue by KylePDavis** [atom/find-and-replace#269]
Seems like there ought to be a `find-and-replace:select-previous` to go along with the current `find-and-replace:select-next` command.
I am trying to mimic some behavior from Ace and I'm unable to without this.

**Comment by synthecypher** [comment]
+1

**Comment by cscalfani** [comment]
+1

**Comment by jamesarmenta** [comment]
+1000

**Comment by TarVK** [comment]
I am also attempting to copy ace shortcuts, and the feature is still not here. Do you still have the shortcut file of what you did get to work from back then? It could save me some time

**Comment by UziTech** [comment]
@sadick254 this should be closed based on https://github.com/atom/find-and-replace/pull/1112#issuecomment-756297777
