### ISSUE TITLE
Scroll to search result

### ISSUE THREAD

**Issue by plaxdan** [atom/find-and-replace#278]
When navigating from a set of search results to the piece of text that the search result was pointing to, it is difficult to see the resultant highlighted text.

The suggestion is to have the editor scroll vertically until the highlighted text is centered vertically. That way, when you navigate from search results, the item found is always in the middle of the screen.

**Comment by mehmetalisavas** [comment]
Hey @benogle !! 
I know this problem works as well for while using `cmd+f` to find words.
But while searching functions (symbols) with `cmd+r` , search result appears at the bottom of the screen.(not center of the screen)
I'm talking about this keybinding.
```
'.platform-darwin atom-text-editor':
  'cmd-r': 'symbols-view:toggle-file-symbols'
```
