### ISSUE TITLE
Allow user to vary how many lines of code are displayed in context of Project Find Results

### ISSUE THREAD

**Issue by dingledow** [atom/find-and-replace#323]
When I search for a value across a project, the line with that value in is highlighted and displayed as a preview of the result under groupings of the file name.

I would find it beneficial to be able to vary the amount of lines that are shown around previews of results to give more context to the search.

**Comment by zumbalogy** [comment]
I would like to second this, and I think it is an important feature. I think even maybe having an option (or +/- buttons) to set the number of lines context right in the find/replace form (maybe underneath the 'Replace All' button) that would live update it (kind of like gitk) could be great.

**Comment by 807811b0-1373-11e5-b60b-1697f925ec7b** [comment]
This is a dupe of #190

**Comment by 50Wliu** [comment]
Thanks @807811b0-1373-11e5-b60b-1697f925ec7b!
