### ISSUE TITLE
Search in Directory that uses a link to another location yields no results

### ISSUE THREAD

**Issue by JonathanGawrych** [atom/find-and-replace#327]
I seem to be having the opposite result of #129.

I have the following directory structure:
```
|-- ~/
|   |-- www/
|       |-- online-client/ -> ~/repos/gitlab/online-client/
|       |-- ...
|   |-- repos/
|       |-- gitlab/
|           |-- online-client/
|               |-- bower.json
|               |-- package.json
|               |-- ...
```

I open Atom in the ```~/www/``` folder. Any search in directory has no results found for any phrases found in files in "online-client" or any of it's subdirectories.  Opening Atom directly to ```~/repos/gitlab/online-client/``` or even ```~/www/online-client/``` will allow me to search in the directory.

I'm using Ubuntu v14.04 LTS, Atom v0.157.0, and Find And Replace v0.152.0. No errors in dev tools.

**Comment by nsartor** [comment]
Go in to your settings and make sure "Follow symlinks" is checked. You might still get duplicates like the other issue, but at least you can search :)

![untitled - atom_2015-03-05_15-56-57](https://cloud.githubusercontent.com/assets/6578903/6514423/5ff5770c-c350-11e4-9773-e53692c4a7ce.jpg)

**Comment by izuzak** [comment]
@JonathanGawrych Just wondering if the above suggestion from @nsartor resolved the problem for you? :thought_balloon:

**Comment by benogle** [comment]
Closing as this seems like it is no longer an issue.
