### ISSUE TITLE
use-selection workflow is disruptive, unwieldy

### ISSUE THREAD

**Issue by clhynfield** [atom/find-and-replace#332]
Using keyboard shortcuts in [other editors](https://github.com/atom/find-and-replace/issues/67) to set Find pattern, select next/all, and replace is smooth and efficient — select text, ⌘E, ⌘⌃G, and type to replace: 

![sublime-use-selection](https://cloud.githubusercontent.com/assets/148868/5504809/fb4557a8-8756-11e4-951c-eb7481fb1957.gif)

In Atom, use-selection-as-find-pattern brings up the find panel, requiring the user to dismiss it or switch focus back to the editor before using select-next or select-all keyboard shortcuts: 

![atom-use-selection](https://cloud.githubusercontent.com/assets/148868/5504835/51b0e42c-8757-11e4-9912-ffdab87208a9.gif)

Showing the panel is right for ⌘F, and grabbing the current selection as the find pattern on show is a handy default action, but for a sleek use-selection and select next/all workflow, there's got to be a smoother way.

**Comment by izuzak** [comment]
@clhynfield I'm able to do this without showing the panel. Here's a gif:

![select](https://cloud.githubusercontent.com/assets/38924/6170006/a4c91382-b2d1-11e4-800f-37152ace4fe2.gif)

Does that help?

**Comment by clhynfield** [comment]
Thanks, @izuzak, that does help a bit—I didn't know you could find all occurrences without setting the find pattern. Still, that doesn't work for find-next or find-previous, does it?

**Comment by izuzak** [comment]
@clhynfield You're right. I was just pointing out that there's a better way to do what you did in the GIFs you recorded.

Also, clarifying what exactly is possible and what exactly isn't possible or how exactly it could be improved is always helpful in pushing issues forward. Some users reading the issue don't have the same context as you do and might not know what you said about OS X or other editors in your recent comment. Sharing as many details as possible in the original issue and doing so in a clear way is _always_ helpful. :blue_heart:

**Comment by schmurfy** [comment]
this is really annoying, I am used to the behavior @clhynfield demonstrated and I find the actual atom behavior really disturbing, the example was maybe not the best but here is what I use cmd+e for:
- quickly replace a word in multiple lines (cmd+e, cmd+g, type new text)
- replace all (cmd+e, ctrl+cmd+g, type text)

With Atom currently this becomes: cmd+e,escape,cmd+g, type text.
What was the idea behind the current behavior ? is there actually someone who finds it ok ?

**Comment by davejamesmiller** [comment]
I'm looking for the same thing. In Sublime Text I often used ctrl+e, ctrl+g to find the next occurrence - e.g. to skip from a function call to it's definition and back. In Atom I'm finding I always have to press escape to close the find dialog - whereas I've never needed to modify the find pattern at that point, so I don't really need it open. I was hoping for a way to remap ctrl+e to set the find pattern without opening the find dialog, but I can't see that option. (It doesn't have to be the default behaviour, but an option to remap it would be nice.) Thanks!

**Comment by benogle** [comment]
@davejamesmiller are you commenting on the right issue? You should be able to just hit cmd-g and focus the next occurrence in the editor.

**Comment by davejamesmiller** [comment]
@benogle I believe I am. I don't have a Mac, but it [looks like](https://github.com/atom/find-and-replace/blob/master/keymaps/find-and-replace.cson) `cmd-g` that you refer to is just `find-and-replace:find-next` (`F3` on Windows) that jumps to the next occurrence of the *current* find pattern. I want to *set* the find pattern to the text under the cursor with `ctrl-e` and *then* jump to the next occurrence (`F3`). Currently it goes `ctrl-e`, `escape`, `F3` (or `ctrl-e`, `F3`, `escape` works too). I believe that's the same issue...

**Comment by benogle** [comment]
So the issue is just that the find panel is open then? The editor is focused after hitting `F3`, right? So you are hitting escape to get the panel out of the visual field, not because you need to in order to focus the editor, correct?

**Comment by davejamesmiller** [comment]
Yes, that's correct.

**Comment by schmurfy** [comment]
so... any chance we can get an option to set the behavior we want ? I don't care which is the default just please let us choose.

**Comment by holzenburg** [comment]
A year has passed and this is still an issue – and one that makes me thinking of switching back daily. It hurts my flow badly. @clhynfield's fix looks simple enough, and wrapping that into an option is a good idea. Please consider this again.

**Comment by schmurfy** [comment]
for me I just stay with sublime text 2 for now, I have atom installed aside but almost does not use it.

**Comment by schmurfy** [comment]
since this issue is not going anywhere I tried another strategy but failed: how can I run my own fork of a core atom package ? I tried `apm develop find-and-replace`, after a reload the package shows in development package but changing anything in it does not change the behavior, it looks like atom still use its own version...
Also if I disable the core package it disables the development one too, it seems to consider them as the same :(

**Comment by frantic** [comment]
@schmurfy have you tried launching atom with `--dev` flag?

**Comment by schmurfy** [comment]
I would prefer a way which don't require using dev mode.

**Comment by vjeux** [comment]
Just submitted a pull request to fix it: https://github.com/atom/find-and-replace/pull/796

**Comment by schmurfy** [comment]
@vjeux  thanks ! I hope it gets merge, it is still an eveyday annoyance for me...
I tried to fix it but failed.
