### ISSUE TITLE
Provide find by whole words option for project find.

### ISSUE THREAD

**Issue by jeffschwartz** [atom/find-and-replace#339]
Currently this isn't implemented in project find.

**Comment by therealmarv** [comment]
+1 ... it was causing headaches for me today.
A tip from @timscott about this issue in file search for a workaround for now:

Use regex and search for `\bword\b`

**Comment by Zentrifuge** [comment]
+1

**Comment by opadillaintegrify** [comment]
Looks like we came full circle.  This originally started as a way to do a whole word search *without* having to use regex

https://discuss.atom.io/t/how-to-search-for-whole-words-in-atom/10969/9

which lead to 
https://github.com/atom/find-and-replace/pull/260

which lead to this issue

**Comment by changnet** [comment]
so far,use regex,and search \bfoo\b instedad.foo is the whole word you search
