### ISSUE TITLE
Find in Project does not recognise accented characters

### ISSUE THREAD

**Issue by alefragnani** [atom/find-and-replace#341]
When you search (Find in Files) for words that contains accented characters, it does not work.

For instance, if you search for **compõe**, it will not find. But if you search for **comp**, it finds. I added a screenshot where you can see that the accented character is also drawn incorrectly (the _interrogation mark_ icon).

![screen shot 2015-01-28 at 9 17 37 pm](https://cloud.githubusercontent.com/assets/3781424/5949276/2591f376-a733-11e4-80bd-756c4a7a3b6a.png)

But, if you use **Find in Buffer**, it works perfectly.

Changing the **Default File Encoding** in **Settings** made no difference.

I'm using Atom 0.176.0, in Windows 7 and Mac OS X Yosemite

Hope the details provided helps.

Thanks

**Comment by benogle** [comment]
This should be fixed in https://github.com/atom/scandal/pull/25 Let me know if it's still an issue.

**Comment by caiobep** [comment]
I'm having the same issue, it seems like my Atom just don't recognize special characters...
