### ISSUE TITLE
Find in Project hanging 

### ISSUE THREAD

**Issue by paulcbetts** [atom/find-and-replace#342]
Recently, Find in Project now just spins on my machine forever:

![](http://cl.ly/image/2r3L3S1I1i34/content#png)

No messages logged to console, Atom version is 0.176.0

**Comment by ricardograca** [comment]
Sometimes I see the message "XX results found in XX files for ..." but no results are actually displayed.

**Comment by benogle** [comment]
@ricardograca what version are you on? Are you on windows? There was an issue with dependencies causing your issue that should be fixed in ~175. 

I cant reproduce the OP @paulcbetts issue.

**Comment by paulcbetts** [comment]
@benogle I believe that was on OS X, is there anything I can capture for the next time it happens?

**Comment by ricardograca** [comment]
@benogle It was with Atom version 0.175 on Ubuntu 14.04. I've since upgraded to 0.177 and so far I haven't run into this issue yet.

**Comment by benogle** [comment]
@paulcbetts @ricardograca is this still an issue?

**Comment by ricardograca** [comment]
I never saw this error again. Currently on version 1.0.
