### ISSUE TITLE
Find and replace with regex doesn't allow for regex groups in the replaced text

### ISSUE THREAD

**Issue by virtualthoughts** [atom/find-and-replace#349]
Input text: 
`myclass.helloworld(1, 2, test)`

Find Dialog:
`helloworld[(](.*), test)`

Replace Dialog:
`helloworld(\1, newTest)`

Resulting text (assuming i didn't get my regex wrong):
`myclass.helloworld(1, 2, newTest)`

What I currently end up getting version 0.179 of atom
`myclass.helloword(\1, newTest)`

Did some digging and it looks like it is possible to do:  http://stackoverflow.com/questions/432493/how-do-you-access-the-matched-groups-in-a-javascript-regular-expression

**Comment by benogle** [comment]
This is not super intuitive. Rather than using `\1`, you can use `$1`.

**Comment by virtualthoughts** [comment]
I had no idea that there was $1 syntax available.  My only suggest would be to offer up some documentation as to what is available as all the past editors I've used implement this with the \1 style syntax.

Thanks for the quick reply!

**Comment by benogle** [comment]
Yeah, not very clear. It's built into javascript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter

**Comment by virtualthoughts** [comment]
Thanks again... this knowledge makes Atom much more useful for me!
