### ISSUE TITLE
Regular Expressions: $1 or \1?

### ISSUE THREAD

**Issue by wackywendell** [atom/find-and-replace#351]
Right now, `$1` appears to be the accepted syntax for the backreference, as opposed to the POSIX standard `\1`. This is unexpected to me, and while there is some precedence (i.e. Perl, PHP, maybe others), I was surprised to find it here, due to the generally stronger support for the `\1` syntax (sed, javascript, python, even Perl allows `\1` [although it is not recommended](http://perldoc.perl.org/perlre.html#Warning-on-1-Instead-of-$1), I believe).

What regular expressions standard is Atom following? Can this also be made clear in the tooltip for the regular expressions button?

**Comment by thomasthorsen** [comment]
+1 for \1 rather than the odd $1

**Comment by benogle** [comment]
> What regular expressions standard is Atom following?

It currently uses [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter) regular expression syntax. 

Supporting `\n` is a reasonable enhancement.

**Comment by wackywendell** [comment]
Ah, JavaScript uses `$1`, I got that wrong.

Anyways, maybe this should be two issues:

 - Support `\1`
 - Add text to the tooltip saying what regex is supported, as there are many other syntax pitfalls out there beyond this one.

Perhaps I should make the second into a new issue?

**Comment by andya9** [comment]
Is it me, or neither works? (atom 189.0)
I mean, I have a latex file with: \textit{some text}
I do (.* is checked):
FIND: \\textit\{\w+\s*\S+\}
REPLACE: <emph>$1</emph>
But it prints a literal $1... i tried \1 and it’s the same

**Comment by posita** [comment]
I like the tooltip idea (or maybe even some way to display documentation regarding the features/flavor of supported regexes). Perhaps as an additional reminder, the default text for the replacement field could indicate the accepted format (if regex mode is selected)?

Something like:

![regex](https://cloud.githubusercontent.com/assets/222581/7290667/00bfffec-e938-11e4-8679-8a6a92d46201.gif)

**Comment by pezholio** [comment]
:+1 for the default text idea. I keep forgetting the syntax for replace, so this would be really useful

**Comment by sijh** [comment]
Agree. I try to use \1, and find that it just won't work. I almost try to open an issue here. It will be helpful to tell us the supported regular expression sytax. After all, both are OK.

**Comment by j4zzcat** [comment]
+1 for \1.

**Comment by lee-dohm** [comment]
Perhaps there can be a link to some JavaScript regex documentation? I wonder if `$1` is the only peculiarity that people stumble over.

**Comment by posita** [comment]
As far as I can tell, `$1` is used by the underlying regular expression library.

**Comment by lee-dohm** [comment]
@posita Yes, it is. Atom uses the JavaScript regular expression system for find-and-replace.

**Comment by posita** [comment]
> Yes, it is. Atom uses the JavaScript regular expression system for find-and-replace.

@lee-dohm, my apologies, I misread your original comment. I can't speak for others, but I'm used to perlre, so `$1` was a stumbling block for me (hence my [earlier proposal for a self-documenting interface](#issuecomment-95429952)).

**Comment by lee-dohm** [comment]
Yep, I liked your proposal and I was suggesting expanding on it :grinning: Rather than *only* `$1` being referenced in the default text, there could be a link to the JavaScript regular expression documentation ... so that if people are having a hard time getting things to work, the *correct* docs are readily available.

Rather than linking to an external website, it could bring up a quick reference instead. Lots of possibilities.

**Comment by posita** [comment]
Sounds good to me! :+1: 

(I was just trying to save you some perhaps unnecessary work of trying to hunt for `(\\{2})*\\1` in the replacement string.) :grin:

**Comment by adambuczynski** [comment]
Currently, neither `$1` nor `\1` appear to be working for me. Whichever I use, both are shown as literals in the previews of the find & replace screen.

**Comment by wackywendell** [comment]
@adambuczynski: are you sure you had the `Regex` option enabled? The button looks like `.*`.

**Comment by adambuczynski** [comment]
Yes, I am sure ;)

Actually I just found out that it does work properly if I re-activate the search (pressing enter again in the search box).

**Comment by juanojeda** [comment]
Just a minor bug/question, but if I have 2 captured strings that I want to use with back-references, I would expect to be able to use `$1` and `$2`.

For instance, to change something from Dot.Case to Kebab-Case, I would want to use
`(Foo|Bar|Baz)\.(Foo|Bar|Baz)` and replace with `$1-$2`.

What is the correct way to do this?

**Comment by benogle** [comment]
@juanojeda is the regex option turned on?

**Comment by vosmith** [comment]
I am also unable to use the $1 backreference to replace text.  I'm using the replace in buffer option from my "find" menu.  The regex find is working lovely, it's highlighting all of the matches, but even if I just put `$1` in the replace field it literally replaces it with the string `$1`.

version 0.158

**Comment by mnquintana** [comment]
@vosmith Although this won't resolve the issue, you're running an extremely old version of Atom (current is 1.0.2) - I suggest that you upgrade as soon as possible.

**Comment by vosmith** [comment]
:open_mouth: Oh my.....this is quite embarassing

**Comment by DaveEveritt** [comment]
I’m also having the problem several others have identified where during 'replace, the backref `$1` is inserted as literal text. I have the latest Atom installed, and regex is on. Tried in Latex and plain text syntax mode. No joy.

**Comment by lee-dohm** [comment]
@DaveEveritt If you don't have a capture in the find regular expression, then the `$1` is inserted as regular text in the replacement. For example:

1. Open the atom/atom project in Atom
1. Open the `README.md` file
1. Press <kbd>Cmd+F</kbd> to open the find-and-replace panel
1. Ensure that Regular Expressions mode is turned on
1. Enter `(atom.io)` in the find field
1. Enter `foo$1` in the replace field
1. Click Find
1. Click Replace

When you do this, the found instance of the text `atom.io` is replaced with `fooatom.io`. However, if you enter `atom.io` without the parens in the fifth step, then the text `atom.io` is replaced with `foo$1`.

Verified this behavior using Atom v1.0.12-ad95281 on Mac OS X 10.10.5.

**Comment by DaveEveritt** [comment]
@lee-dohm thanks, answered this on the forum. Good that it's documented here in case anyone else makes the same mistake!

**Comment by lgcc** [comment]
(\d)(\d), then  $1.$2

**Comment by nghtstr** [comment]
This is strange. I have text like this:
`[ItemCode] => SD111107-00`
I am trying to do a Regex find and replace with this as the search:
`\[(.*)\].*?\r`
And this as the replace:
`protected $($1)`

Now it appears to be able to find it, but when I press Replace or Replace All, it acts like it did something but nothing is changed in my file. Very weird...

**Comment by jrobichaud** [comment]
Activating both case sensitive ("Aa" button) and regex (".*" button) appears to work with $n syntax.

**Comment by btoo** [comment]
Is there any way we could replace the capture group itself? i.e. use $1 in "find" rather than "replace"

**Comment by posita** [comment]
@btoo, it sounds like you're talking about true back-references (not group references for replacements). In theory, [ES6 supports them](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#grouping-back-references). My anecdotal testing suggests the `\#` notation already works in the find string in Atom. For example, `(123)(xyz)\2\1` will match the string `123xyzxyz123`. If you want to disambiguate a back-reference from a literal digit, there are several strategies. For example, `(xyz)(\1)2`, `(xyz)\1(2)`, and `(xyz)\1[2]` will all match `xyzxyz2`.

**Comment by tkstreet** [comment]
I didn't know that there was even a way to do this until I found this post.  I'm glad that Atom at least supports search result replacement.  But there really should be something explaining what syntax it uses.  From what I have seen and from my personal experience, /1 is _far_ more common in general practice than $1, regardless of language considerations.

So yeah, I recommend to both support /1 and to add some kind of little clickable callout that gives a brief rundown of the syntax....or something like that.

**Comment by pinjaliina** [comment]
It's not just the difference between \1 and $1. I'm trying to pad strings with zeroes on replace (see [this question](https://stackoverflow.com/questions/37159034/regex-to-add-leading-zero-in-date-record) at stackoverflow.com), i.e. choose backreferences with conditionals (say, ```if $2 matches, then print $1 and $2, else just 0 and $1```), but while my search works just fine, I can't seem to find a way to replicate that behaviour in replace; curly brackets are just printed literally. Online workaround suggestions assume the regexp is done in code, and thus propose if-else -based javascript tests as solutions, so they're not helpful with Atom.

**Comment by lee-dohm** [comment]
Thanks for the feedback.

We understand that this is confusing for some. Unfortunately, the amount of work that it would take to implement and maintain this is not something we want to take on in the foreseeable future. Because of this, I'm going to close this issue at this point. If we decide to revisit it at some point in the future, we will reopen the issue.

Thanks again for all the thoughts and ideas.
