### ISSUE TITLE
No results when searching with regexes containing \n 

### ISSUE THREAD

**Issue by floscher** [atom/find-and-replace#362]
I've a fresh Atom 0.186.0 on Ubuntu 14.10 with no additional packages.

When I use "Find in project" with any regex that contains `\n` it always tells me there are no results.

![newline-search](https://cloud.githubusercontent.com/assets/3904348/6541710/2fd33406-c4e0-11e4-9cd7-e1ea7ec06c9d.png)

**Comment by PaulMorel** [comment]
I have the same issue on Atom 0.181.0 on Windows 7 with searching `\n` in regex Find and Replace

**Comment by floscher** [comment]
The issue still holds after installing 0.187.0 via *.deb file.
Other special characters (like `\t` or even `\r`) still work. But as soon as the search term contains `\n`, nothing is found.
Atom seems to recognize correctly that `\n` doesn't mean "a backslash and an n", but "line feed" instead. Because if a file in a project contains an actual backslash followed by an n, it still finds nothing.

This bug appeared in every repo or normal folder that I open in Atom since reporting the bug.

**Comment by lee-dohm** [comment]
This is really just a special case of #218. Currently, Find in Project doesn't support multi-line patterns. See the referenced issue for details and please subscribe there for updates.
