### ISSUE TITLE
Incremental find

### ISSUE THREAD

**Issue by dantman** [atom/find-and-replace#367]
Here's another Sublime Text feature Atom doesn't have that Sublime users may miss.

{`Cmd`,`Ctrl`} + `i` starts an incremental find, which works like {`Cmd`,`Ctrl`} + `f` but jumps to the first match as you type and closes when you hit enter.

It's great for quickly getting to a different part of the file.

I'm moving this from atom/atom#6058.

@izuzak mentioned that someone attempted to do this before in #178.

**Comment by mike-engel** [comment]
I think this may have been what #11 was trying to accomplish as well. Could be wrong.

**Comment by devios1337** [comment]
Imo, there is no need for a second "incremental find" command. There should be one Find command and its behavior should be incremental. Splitting this into two almost-identical commands needlessly fragments the user interface.

Here's how it should work in my ideal implementation:

1. User types Cmd-F to open Find bar.
2. As they type, the cursor and view moves to find the first match from their starting position.
3. Hitting Cmd-G goes to the next match in the file (Cmd-Shift-G in reverse direction).
4. Hitting Enter accepts the currently displayed result and hides the Find bar.
5. Hitting Esc cancels the Find and goes back to the original starting location, hiding the Find bar.

**Comment by mike-engel** [comment]
Agreed with @devios1337.

**Comment by dwelle** [comment]
I agree with @devios1337, too. Incremental search should be standard in today's world.

**Comment by plrenaudin** [comment]
Agreed, this feature is missing. Added a PR #427 to cover this but no news since then.

**Comment by benogle** [comment]
Implemented as an option in #427
