### ISSUE TITLE
shift-click find button should select previous ocurrence

### ISSUE THREAD

**Issue by dasilvacontin** [atom/find-and-replace#369]

**Comment by hotoiledgoblinsack** [comment]
It would also be neat if this could be bound to Shift + Return (Shift + Enter) by default, as to provide the reverse of the current find next behavior.

**Comment by kenden** [comment]
+1 for Shift-Enter to find previous occurrence.

Cmd-F to find next, ok.
Shift-Cmd-G to find previous... not obvious and hard to remember.

I would also add a "find previous" button.
Maybe like in Firefox: up arrow to find previous, down arrow to view next.

**Comment by callummr** [comment]
Looks like shift+enter already finds previous for me (Windows if it makes a difference), but I've submitted a PR above for shift + click on 'Find' to find previous.

**Comment by dasilvacontin** [comment]
Awesome, thanks! :)

**Comment by hotoiledgoblinsack** [comment]
Strange, shift+enter while in the find & replace bar does not find the previous here, at least not by default, perhaps it is a Linux (and Mac) issue?

**Comment by zp-j** [comment]
Hello @hotoiledgoblinsack, I'm using Atom 1.0.19 with Mac, `shift` + `enter` works when you have the **find** input box focus.

**Comment by hotoiledgoblinsack** [comment]
@zp-j Thanks for your reply. Looks like once again I was a victim of my own keymap settings. I tried safe mode but didn't think that they'd apply there as well.
