### ISSUE TITLE
Find + Replace icons

### ISSUE THREAD

**Issue by simurai** [atom/find-and-replace#370]
Would be nice if the find + replace buttons would have graphical icons instead of text. Related: #231

![screen shot 2015-03-26 at 8 54 08 am](https://cloud.githubusercontent.com/assets/378023/6837927/b4dcf5c4-d395-11e4-8d2b-69ba61093c88.png)

Probably should be part of the Octicons, but not sure yet if it's better to fork+extend or create a second Atom specific set.

**Comment by benogle** [comment]
YES

**Comment by lee-dohm** [comment]
If Octicons is being extended, perhaps github/octicons#34 could be addressed too? :grinning: Personally, I would love to see all of these added to the standard Octicons set though I admit that I'm not sure what the implications are to adding a bunch of other icons to the standard set. So perhaps an Atom-specific set would be the best approach.

**Comment by benogle** [comment]
We could probably get them added to the main distro. I know @cameronmcefee was cool with some of the atom specific icons a while ago. Still a decent idea @cameronmcefee?

**Comment by cameronmcefee** [comment]
I think it's still reasonable, though I don't foresee these icons getting much use on github.com (thus being a hollow inflation of the bundle over there). Would it be a pain in the ass to have two fonts bundled with Atom, so stock Octicons and a custom Atom set? If that's an option that would be nice, but if that's a hassle for you guys, the impact on the main bundle isn't too crazy.

**Comment by cameronmcefee** [comment]
@simurai are you down to design the icons? They have to fit a 16x16 grid, and I have a template I can provide you.

**Comment by simurai** [comment]
@cameronmcefee Yeah, I can give it a try. Template would be great to start.

I can see that if the new icons don't get used on .com it's better to not merge upstream. Just to keep the filesize down. I still have to check out how generating the font from the SVG source works. Maybe it's possible to have two different sources? Or we can "fork" the Octicons and in case they change, update them for Atom manually.

**Comment by cameronmcefee** [comment]
Here's the AI template: http://cl.ly/0l2L25441X0R. Nothing fancy, but it is scaled to the correct size to match the rest of the octicons. Here's the short list of best practices:

- Use as few vector points as possible.

- To prevent blurring, design your icon so straight lines sit on exact pixels.

- SVGs must be <code>1024px</code> tall. Each icon pixel = 64 SVG pixels.

- SVGs should be only as wide as the graphic. If the graphic is an odd number of pixels in width, add one icon pixel (64 SVG pixels) of space on one side of the icon. This prevents icon blurring when using <code>text-align: center;</code> on icons.

- If you are using Illustrator to create your SVG, be sure to merge your shape and expand the path. This is because the generator can only import one <code>path</code> element per SVG.

- In general, try to create your icon at 12x12 px and only break out of that space when necessary.

> I still have to check out how generating the font from the SVG source works.

@simurai here's where it might get tricky.

Octicons is generated from a private repo, rather than from scripts that live in the public octicons repo. It might not be the best method ultimately, but it is what it is for now. The generator supports subsets, so we can totally have an Atom subset that's saved and easy to generate. You can see a public overview of how it works here: https://github.com/github/octicons/issues/24

Since you're a GitHub contractor we can definitely give you access as needed, but we wouldn't be able to make it public.

**Comment by mnquintana** [comment]
I'm excited for this – don't know if anyone already has repo name ideas, but I'd :+1: `atomicons`.

**Comment by kevinsawicki** [comment]
> Would it be a pain in the ass to have two fonts bundled with Atom, so stock Octicons and a custom Atom set?

Just want to say, this is no biggie, we can definitely bundle/use a second font if needed.

**Comment by cameronmcefee** [comment]
Cool. I'm thinking of hacking on a release of octicons that makes the build process something that can be bundled into the repo. From that you'd be able to have your own fork. Not sure how much time I'll have to make it happen but I figure it's relevant to your interests if I can do it.

**Comment by simurai** [comment]
Ok, here a first stab:

![screen shot 2015-05-13 at 11 11 07 pm](https://cloud.githubusercontent.com/assets/378023/7612528/69f3ffe2-f9c6-11e4-913c-c46cd775c638.png)

1. Regex
2. Case Sensitive
3. Within Current Selection
4. Whole Word

![find-replace-icons-dark](https://cloud.githubusercontent.com/assets/378023/7612610/e225da1c-f9c6-11e4-9955-f6be9b92d178.png)

![find-replace-icons-light](https://cloud.githubusercontent.com/assets/378023/7612615/e7499966-f9c6-11e4-9521-a4c37d365f90.png)

The first 2 are pretty much the same as the current "text" version. 3 + 4 are more graphic. Some notes:

- 3 + 4 have two colors, not necessarily needed, but help to highlight certain areas.
- 3 + 4 are `18px` wide.. especially 4 was hard to fit into `16px`.

So maybe for this case, it would make sense to add the icons as SVG.

**Comment by lee-dohm** [comment]
:+1: on the SVG idea. We should keep things as scalable as possible for people with visual differences. Also, we should still maintain the hover tooltip.

**Comment by benogle** [comment]
I think all these look great. Down to try the svg idea.

**Comment by cameronmcefee** [comment]
> Also, we should still maintain the hover tooltip

Definitely this. The icons are beautiful, but "selection" and "whole word" aren't immediately clear without explanation.

The only one that feels, from a nitpick standpoint, a little off is the "whole word" one. Presumably you're implying that the collection of vertical lines are letters and that the highlighted portion is a word? I think the metaphor makes sense, however no type is 1:7, so I don't immediately think "letters" when I see it.

**Comment by benogle** [comment]
> a little off is the "whole word" one

Maybe just the underscore thing for that one? Not sure if that would be more clear, though.

**Comment by simurai** [comment]
Yeah, the "Whole Word" looks a bit too much like a bar code?

There could be 2 lines of text:

![find-replace-icons-2](https://cloud.githubusercontent.com/assets/378023/7625011/b8ea2cf0-fa2c-11e4-833b-76dea75fd402.png)

But that feels a bit too detailed.. so maybe just one line with 1:3 ratio letters and the "underscore thing" pulled down a little to give the whole icon more height:

![find-replace-icons-3](https://cloud.githubusercontent.com/assets/378023/7625032/f25ef484-fa2c-11e4-8ef4-e63d4a90a908.png)

**Comment by mnquintana** [comment]
> But that feels a bit too detailed.. so maybe just one line with 1:3 ratio letters and the "underscore thing" pulled down a little to give the whole icon more height:

> ![find-replace-icons-3](https://cloud.githubusercontent.com/assets/378023/7625032/f25ef484-fa2c-11e4-8ef4-e63d4a90a908.png)

This one looks good to me :+1: 

This is minor, but I feel like the `Aa` icon should be kerned a bit tighter - looks a little too loose right now.

**Comment by simurai** [comment]
> the Aa icon should be kerned a bit tighter

![find-replace-icons-4](https://cloud.githubusercontent.com/assets/378023/7625463/d7aea11a-fa32-11e4-86f9-9bd091d6ff65.png)

**Comment by mnquintana** [comment]
> the Aa icon should be kerned a bit tighter

![find-replace-icons-4](https://cloud.githubusercontent.com/assets/378023/7625463/d7aea11a-fa32-11e4-86f9-9bd091d6ff65.png)

:+1: Looks great to me

**Comment by cameronmcefee** [comment]
:+1: @simurai the shorter "letters" feel much less like a bar code.
