### ISSUE TITLE
Find and Replace stopped working for Directory Searches

### ISSUE THREAD

**Issue by jcasabona** [atom/find-and-replace#371]
The package is enabled and the search fields come up, but it's not yielding any results for Directory searches (for text I know is there, or any searches that yield results in Sublime, for example). It seems to be working fine for file searches.

I'm using a 2014 Macbook with Yosemite, if that helps.

**Comment by lee-dohm** [comment]
* Is the text in files that are in your `.gitignore`?
* Which version of Atom are you running?

**Comment by jcasabona** [comment]
* This is any text in any files in the folders. 
* Version 0.188.0

Thanks!

**Comment by jcasabona** [comment]
Hmm it looks like it's working now. Perhaps this was an issue with my machine. 

Thanks - sorry for the false alarm.

**Comment by lee-dohm** [comment]
You're welcome. Sorry I couldn't get you more help :disappointed:
