### ISSUE TITLE
Support the Edit / Folding menu options

### ISSUE THREAD

**Issue by alefragnani** [atom/find-and-replace#374]
The result page shows the results grouped by file, and for each file, it already has a _collapse/expand icon_, that hides or shows the results (the line where the text was found inside the file). But the **Edit / Folding** menu options does not work.

Sometimes you know, or have an idea, in which files your search should be looked first, so folding all the results and visually finding the files, is faster than scrolling.

**Comment by benogle** [comment]
Interesting. The fold menu items are supposed to apply to the editor, but they could conceivably apply to the results page as well.
