### ISSUE TITLE
Open "Project Find Results" in Existing Tab Option

### ISSUE THREAD

**Issue by sftd** [atom/find-and-replace#378]
"Find in project" is always opening "Project Find Results tab in active Pane (or splitting active Pane if "Open Project Find Results in Right Pane" is enabled). I think the default behaviour (or at least an option) should be not to open new tab if "Project Find Results" tab already exists (as all 
"Project Find Results" tabs are updated anyway - new tab would make sens if old tabs would remain with previous results).

I would be very grateful for such a change/feature.

**Comment by izuzak** [comment]
@sftd I'm not sure I understand your request. You said:

> I think the default behaviour (or at least an option) should be not to open new tab if "Project Find Results" tab already exists 

But as far as I can tell, that's already the behavior in Atom. I started Atom, used a project find, and then a new tab was opened. Then I ran another project find and a new tab wasn't opened but the existing one was updated.

Could you perhaps record a short GIF in which you demonstrate the behavior and provide steps to reproduce? I'm probably misunderstanding something. Thanks!

**Comment by sftd** [comment]
Let's say I have something like that:
![atom1](https://cloud.githubusercontent.com/assets/3073859/7116316/0b60aa12-e1f1-11e4-8ff7-2961d80fd833.png)

Expected behavious in my opionion would be to display search result in already existing tab. But depending on active Pane, a new Tab will be created in that Pane:
![atom2](https://cloud.githubusercontent.com/assets/3073859/7116333/242cdaca-e1f1-11e4-9794-95a17629a01b.png)

Sorry for not making myself clear.

**Comment by izuzak** [comment]
Thanks for clarifying, @sftd

**Comment by benogle** [comment]
I think this is reasonable as an all-the-time thing: just find the any open results view, and use that.

**Comment by harai** [comment]
+1

**Comment by rickyliu93** [comment]
+1
