### ISSUE TITLE
add whole word option

### ISSUE THREAD

**Issue by haikyuu** [atom/find-and-replace#380]
It would be very good to add this feature:
whole word option

**Comment by benogle** [comment]
It's already in find in buffer, but the icon is not very intuitive: ![whole-word](https://cloud.githubusercontent.com/assets/69169/7257346/e6eefa70-e809-11e4-8d1a-3ca0268b43f1.jpg)

**Comment by haikyuu** [comment]
Ok thanks. But its tool-tip isn't working actually.
