### ISSUE TITLE
Line with multiple matches is listed twice in results

### ISSUE THREAD

**Issue by focusaurus** [atom/find-and-replace#381]
When you do a project find, if a matching line contains the search term more than once, the line is listed in the find results once for each occurrence of the search term. I would rather just see each line listed once, even if the search term appears multiple times. Screenshot attached. Note how line 82 occupies 2 rows of results.

![2015-04-21 project find duplicates](https://cloud.githubusercontent.com/assets/482377/7260983/7829038e-e82b-11e4-8f79-bd46113dd64b.png)

(originally [discussed here](https://discuss.atom.io/t/project-find-lists-duplicates-for-matching-line/16284))

**Comment by izuzak** [comment]
This was discussed in https://github.com/atom/find-and-replace/issues/97. Could you add a comment there instead (it makes discussing feature requests easier if everything is in one place)? Thanks!

**Comment by focusaurus** [comment]
Ah, I didn't see that since it is closed already.

**Comment by focusaurus** [comment]
Closing as already discussed in #97
