### ISSUE TITLE
Doesn't search everywhere in large project

### ISSUE THREAD

**Issue by alexmngn** [atom/find-and-replace#382]
Hi,
I am working with Atom on a large project, about 500K files for 1.2GB of data.
I noticed that the find module doesn't search everywhere in my project. Some of my folders are really nested into a dozen of other folders and it doesn't go that deep.
I don't know if that's a bug, but to me it should search everywhere... I didn't find any configuration of deepness the package should go.
Thanks!

**Comment by benogle** [comment]
Is this still an issue with the latest version of atom (1.0.3)? What system are you on? 

Project search doesnt search binary files, and currently doesnt do well with non-utf8 encodings.

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/find-and-replace/issues/382#issuecomment-126442695. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
