### ISSUE TITLE
find + replace not opening

### ISSUE THREAD

**Issue by dapitts08** [atom/find-and-replace#386]
i am new to atom but for some reason none of the shortcuts for find + replace are working. am i missing something here? i assume typing cmd + f would open the search window but nothing happens.

**Comment by 50Wliu** [comment]
Please open the keybinding resolver (<kbd>Cmd+.</kbd> on a Mac or <kbd>Ctrl+.</kbd> otherwise) and see what appears when you try opening Find and Replace.  Thanks!

**Comment by dapitts08** [comment]
That worked! Thanks!!!!

Sent from Outlook




On Sun, May 10, 2015 at 6:05 PM -0700, "Wliu" <notifications@github.com> wrote:












Please open the keybinding resolver (Cmd+. on a Mac or Ctrl+. otherwise) and see what appears when you try opening Find and Replace.  Thanks!

**Comment by 50Wliu** [comment]
To clarify, is Find and Replace working properly now?

**Comment by dapitts08** [comment]
yes. find and replace is working properly after using the keybinding resolver.

**Comment by bojidar-bg** [comment]
Strange, it doesn't work here after updating to 0.201.0... No matter how many times I press ctrl-F, the find-and-replace pane doesn't show up. The keybinding resolver shows that "find-and-replace:show" matches...
OS: Ubuntu(-gnome) 14.04
Atom version: 0.201.0

**Comment by bojidar-bg** [comment]
lol, restarted atom, and now it works..... :smiley_cat:
