### ISSUE TITLE
Find in project does not search in folders with a dot in the name

### ISSUE THREAD

**Issue by VodkaBears** [atom/find-and-replace#388]
In folders like: `desktop.level`.
If dot is at the beginning – all works fine.

**Comment by danderson00** [comment]
+1 this is time consuming to work around

**Comment by harai** [comment]
Suppose I want to find a text in a file located at `foo/bar.baz/file.js`.
Then, search works fine if the Path field is one of the following:

* blank
* `foo`
* `foo/bar.baz/` .

On the other hand, search fails if the Path field is:

* `foo/bar.baz` .

Is this what this issue says?

**Comment by danderson00** [comment]
I have a project that refuses to search any child folder (they all have a dot in the name), but I haven't been able to repro in a simple scenario. I will invest more time to come up with a repro soon.

**Comment by VodkaBears** [comment]
Seems like if i search in a folder with a dot, Atom thinks that it is a filename with its extension. So, yes, @harai, if a slash is added to the end then all works fine.

**Comment by VodkaBears** [comment]
I have an ultra creative solution to add a slash here if relPath is not empty: https://github.com/atom/find-and-replace/blob/master/lib/project-find-view.coffee#L251
