### ISSUE TITLE
Wrap-around notification icon

### ISSUE THREAD

**Issue by mrodalgaard** [atom/find-and-replace#401]
E.g. XCode and Eclipse has a nice little feature when searching a document. When the active search does a wrap-around an icon notification flashes shortly to indicate that you have reached the bottom or top and are starting over.

![wrap-around](https://cloud.githubusercontent.com/assets/659763/7896907/35561b7a-06c9-11e5-9c09-82c578068f1d.gif)

It might just be me. Otherwise I can create a PR for this small addition, probably with a more discreet notification.

**Comment by ryanjbonnell** [comment]
BBEdit has a similar search wrap-around UI notification. It would be nice to see this subtle refinement added to Atom as well.
