### ISSUE TITLE
don't ignore speicified file from a npm module in node_module folder

### ISSUE THREAD

**Issue by dhirenderbp** [atom/find-and-replace#404]
I have .gitignore file something like:

!node_modules/
node_modules/*
!node_modules/loopback-component-storage/
node_modules/loopback-component-storage/*
!node_modules/loopback-component-storage/lib/
node_modules/loopback-component-storage/lib/*
!node_modules/loopback-component-storage/lib/storage-handler.js
!node_modules/loopback-component-storage/lib/providers/
node_modules/loopback-component-storage/lib/providers/*
!node_modules/loopback-component-storage/lib/providers/filesystem/
node_modules/loopback-component-storage/lib/providers/filesystem/*
!node_modules/loopback-component-storage/lib/providers/filesystem/index.js

I commit index.js and storage-hndler.js and pushed it to my branch. When I merge it with Development branch there is folder created node_module/loopback-component-storage/lib with both the files. And when one of my teammember take pull request from development he get error that please move or remove those file because these file already exist. Then he remove folder loopback-component-storage and take pull again the lib folder was there. And then again he install the loopback-component-storage module and i found the loopback-component-storage/lib was removed.  So please let me know if am going wrong somewhere.

**Comment by 50Wliu** [comment]
Hey @dhirenderbp, this issue doesn't seem to have much to do with Atom or Find and Replace, so I'm going to close it.
However, I may have misunderstood your issue-if so, you can clarify here and I'll re-open it.
