### ISSUE TITLE
Feature Request: "Match Quotes" option in finder

### ISSUE THREAD

**Issue by colllin** [atom/find-and-replace#410]
Similar to "Match Case" (and turned off by default).

When disabled, typing `'` or `"` in the finder query would essentially match the regexp `['"]`.

![image](https://cloud.githubusercontent.com/assets/185923/8115047/124b56c4-1036-11e5-943b-f42f41edb311.png)

**Comment by benogle** [comment]
This is probably too specific for us to add as an option that is around all the time. I'm going to close this as it can be solved with regex and the pattern you described.
