### ISSUE TITLE
Stops too early

### ISSUE THREAD

**Issue by BlaM** [atom/find-and-replace#411]
I have some strange issues with the search and replace tool:

Let's assume I have this text file:

    1. thisModule.rowEditor
    2. thisModule.rowEditor
    3. thisModule.rowEditor
    4. thisModule.rowEditor
    5. thisModule.rowEditor
    6. thisModule.rowEditor
    7. thisModule.rowEditor
    8. thisModule.rowEditor
    9. thisModule.rowEditor
    10. thisModule.rowEditor

I want to use find and replace to change "thisModule.rowEditor" to "thisEditor" in the rows numbered 6 to 10.

... so: 

- Search for "thisModule.rowEditor"
- Replace with "thisEditor"
- Position cursor in row 6
- Atom tells me "10 results found"
- Press "Find" - Atom selects the item in row 6
- Press "Replace" - Atom replaces the item in row 6 and selects the item in row 7.
- Atom tells me "9 results found"
- Press "Replace" - Atom replaces the item in row 7 and selects the item in row 8.
- Atom tells me "8 results found"
- Press "Replace" - Atom replaces the item in row 8 and **selects the item in row 1**.
- Atom tells me "7 results found"

I have absolutely no clue why it doesn't continue with row 9.

I can then click "Find" repeatedly to go on to row 9, press "Replace" - and again, it goes back to row 1 (not row 10).

Not sure if it is relevant, but I click the "Find" and "Replace" buttons with my mouse.

For me the problem occurs under Windows 8 x64, but I don't think that's relevant.

Atom is 0.209

**Comment by BlaM** [comment]
I guess that means not everyone has that problem?

atom.packages.getAvailablePackageNames():

    [
    "atom-beautify", 
    "atom-bootstrap3",
    "atom-keymap-compatible-master",
    "bower-install", 
    "composer",
    "ctrl-dir-scroll", 
    "date",
    "define-jump",
    "docblockr", 
    "emmet", 
    "format-sql",
    "highlight-selected",
    "html-id-class-snippets",
    "keyboard-localization",
    "language-sql-mysql",
    "less-autocompile", 
    "linter",
    "linter-htmlhint", 
    "linter-jshint",
    "linter-jsonlint", 
    "linter-php",
    "minimap",
    "minimap-highlight-selected",
    "open-recent", 
    "pigments",
    "pretty-json", 
    "project-manager",
    "select-rectangle", 
    "seti-monokai",
    "sort-lines", 
    "symbols-tree-view",
    "title-case", 
    "uuidgen",
    "atom-dark-syntax", "atom-dark-ui", "atom-light-syntax", "atom-light-ui",
    "base16-tomorrow-dark-theme", "base16-tomorrow-light-theme",
    "one-dark-ui", "one-dark-syntax", "one-light-syntax", "one-light-ui",
    "solarized-dark-syntax", "solarized-light-syntax",
    "archive-view",
    "autocomplete-atom-api",
    "autocomplete-css",
    "autocomplete-html",
    "autocomplete-plus",
    "autocomplete-snippets", 
    "autoflow",
    "autosave", 
    "background-tips",
    "bookmarks", 
    "bracket-matcher",
    "command-palette",
    "deprecation-cop",
    "dev-live-reload",
    "encoding-selector",
    "exception-reporting",
    "find-and-replace", 
    "fuzzy-finder",
    "git-diff", 
    "go-to-line",
    "grammar-selector", 
    "image-view",
    "incompatible-packages",
    "keybinding-resolver", 
    "link",
    "markdown-preview", 
    "metrics",
    "notifications", 
    "open-on-github",
    "package-generator",
    "release-notes",
    "settings-view", 
    "snippets",
    "spell-check", 
    "status-bar",
    "styleguide",
    "symbols-view", 
    "tabs", 
    "timecop",
    "tree-view",
    "update-package-dependencies",
    "welcome", 
    "whitespace",
    "wrap-guide",
    "language-c", "language-clojure", "language-coffee-script", "language-csharp", "language-css",
    "language-gfm", "language-git", "language-go", "language-html", "language-hyperlink",
    "language-java", "language-javascript", "language-json", "language-less", "language-make",
    "language-mustache", "language-objective-c", "language-perl", "language-php",
    "language-property-list", "language-python", "language-ruby", "language-ruby-on-rails",
    "language-sass", "language-shellscript", "language-source", "language-sql",
    "language-text", "language-todo", "language-toml", "language-xml", "language-yaml"
]

**Comment by benogle** [comment]
Can you try again running `atom --safe .`? Does this still happen? There is more information in the [debugging document](https://atom.io/docs/latest/hacking-atom-debugging)

**Comment by benogle** [comment]
Nevermind, I can reproduce this.

**Comment by maxbrunsfeld** [comment]
@BlaM Sorry about this. I believe it will be fixed in Atom 0.210.
