### ISSUE TITLE
Could we have case sensitive by default, or via a setting?

### ISSUE THREAD

**Issue by adambuczynski** [atom/find-and-replace#413]
Title says it all :)

I usually need to search in code, where case sensitivity matters. It would be nice if this could be enabled by default, or if it would be toggleable via the settings to be on/off by default.

**Comment by benogle** [comment]
All the default options can be set via the config. The case sensitivity setting is: `find-and-replace.caseSensitive`. Though the previous state when reopening a window takes precedence.  See [find-options.coffee](https://github.com/atom/find-and-replace/blob/f940b220e0bea22ec926ded1a19de91a6f33cf59/lib/find-options.coffee#L22-L25) for more info.

**Comment by adambuczynski** [comment]
Great, thank you.
