### ISSUE TITLE
If I specify a path to search in that is `.gitignored`'d then please search it

### ISSUE THREAD

**Issue by ProLoser** [atom/find-and-replace#414]
Most of the time I don't want to search my `.gitignore`'d code. But occasionally, you want to poke around 3rd party modules. Instead of manually toggling this behavior on and off, it would be nice if when I specify a 'search from this folder path' that is a `.gitignore`'d path then the setting is ignored and every file in that tree is searched. Then as soon as I clear the search path it goes back to regular behavior.

**Comment by benogle** [comment]
This was fixed in atom 1.0.3 by atom/scandal#29

**Comment by ProLoser** [comment]
Yay :+1:
