### ISSUE TITLE
feature request: allow basic javascript in find and replace function

### ISSUE THREAD

**Issue by Billybobbonnet** [atom/find-and-replace#417]
Hello,

My issue is quite simple, I have a list of countries in  ISO 3166-1 alpha-2 format. here is how it looks:

``` json
{
  "name": "Afghanistan",
  "code": "AF",
  "country-code": "004"
}, {
  "name": "Åland Islands",
  "code": "AX",
  "country-code": "248"
}, {
  "name": "Albania",
  "code": "AL",
  "country-code": "008"
},
```

I want to change all the codes to their lowercase equivalent. I can select them using a simple regex find string `"[A-Z]{2}"` 

I would love a way to apply a `matchedString.toLowerCase()` on every string matched by my regex. Or maybe something like `this.toLowerCase();`

Thanks!

**Comment by dorian-marchal** [comment]
You can use <kbd>Ctrl+K U</kbd> to change the selection to uppercase and <kbd>Ctrl+K L</kbd> to lowercase.

**Comment by Billybobbonnet** [comment]
I just did a click on `find` + `Ctrl+K L ` 294 times. It was surely shorter than doing it "manually". But still, I fell ashamed :wink: 

I love atom and I want to stick with it. I must say that this is the kind of feature that I would like to have in my main development tool.

Keep up the good work!

**Comment by davelnewton** [comment]
A partial solution would be to allow Sublime-style replacement expressions, e.g., https://manual.macromates.com/en/regular_expressions#replacement_string_syntax_format_strings. That makes easy stuff super-easy. It's one of the few things I really miss about Sublime. That and keyboard macros :(

**Comment by benogle** [comment]
> A partial solution would be to allow Sublime-style replacement expressions

Do you mean replacing `ab([c]+)` with `de$1` style of replacement? Atom currently supports these. Or is there something in that link that I am missing? A solution to this issue without allowing js would be interesting.

**Comment by davelnewton** [comment]
No, I mean to allow Sublime-style modifiers like `\u` to upper-case as mentioned in the "case foldings" section:

> It is possible to convert the next character to upper or lowercase by prepending it with \u or \l. This is mainly useful when the next character stems from a capture register. Example:

    Find: (<a.*?>)(.*?)(</a>)
    Replace: $1\u$2$3

> You can also convert a longer sequence to upper or lowercase by using \U or \L and then \E to disable the case folding again. Example:

    Find: (<a.*?>)(.*?)(</a>)
    Replace: $1\U$2\E$3

**Comment by benogle** [comment]
Ah, neat. :+1: to that idea.

**Comment by techmag** [comment]
Google searching just led me here (rabbit hole was a tad deep however). I'm just discovering the joys of Regex within the Atom editor's search-and-destroy, ahem I mean find-and-replace features and I love it - first one that stumped me however was that yes I have a dataset with "words" needing to be upper-cased and  while I can do the match I can't indicate the "replace match as UPPER". 

Would love to have that as a feature as I'm sure the proper implementation of it would bring in a whole bunch of other delicious goodies as well that I've yet to discover...

**Comment by AustinDizzy** [comment]
:+1:  Just had to `Ctrl+K L` 44 times. Supporting Sublime Text style regex case manipulation would be great for this specific purpose.

**Comment by AaronCritchley** [comment]
Note that you can use `Alt + Enter` to select all found results so you only need to do the modification once. (Not a solution but hopefully saves some time for anyone looking for toLowerCase / toUpperCase alternatives)

**Comment by davelnewton** [comment]
That's only an alternative if you're not making use of regex replacement with case manipulation, though.

**Comment by AaronCritchley** [comment]
Absolutely, like I said, it's not a solution but should save time for the people coming here saying 'Just had to Cmd + KU 350 times!'.

**Comment by techmag** [comment]
That alt-enter trick is neat! Thank you Aaron for pointing that out! 

Doubt I was the only now that didn't know it was there. 

Only works on a single file at a time though right? 

Even so a huge step up as you say. 

Having an actual regex replacement process would of course work on either type of search (in file versus across a set of files)

**Comment by AaronCritchley** [comment]
Yeah, it would add be huge value to have something fully functional. 

I only learnt about Alt + Enter today, had a [question sitting on SO](https://stackoverflow.com/questions/32507604) about it for a month or so and there's a lot of others regarding similar functionality, really hope it gets implemented soon!

**Comment by doughsay** [comment]
+1 on implementing \U \E like a lot of editors support (vim, sublime, etc.)

**Comment by Pharylon** [comment]
This would be nice. Fortunately, there are a lot of other utilities to do this (Notepad++, for instance) and it's done so rarely it's no a big deal to switch to a different editor for this.

**Comment by softerhardware** [comment]
I switched from sublime to atom, but the limitation of not being able to change case in search and replace may be a showstopper for me. Why must I have another editor to do this simple task? Also, I am not changing the case of an entire word, just part of it, so the tricks mentioned earlier will not work. What I want to do is:

Find:
S00_AXI_(.*)

Replace with:
S00_AXI_\L$1

**Comment by bmperrea** [comment]
snake_case -> camelCase requires casing functionality. 👍  for this!

**Comment by bmperrea** [comment]
I started working on this here:

https://github.com/bmperrea/find-and-replace/tree/bmperrea/function

I have the functionality finished for the current file replace. There is a new button on the replace line that toggles function mode, exposing the option to enter a function into Javascript's String.prototype.replace. I have done careful error handling for bad functions. Things I still need to do:

1. Write specs!

Other things that would be nice:

1. Extend to project replace
2. Color the replace function box red when there is a function-related error
3. Make the icon height match the input box and buttons better 

I would appreciate some help on those last three.

**Comment by bmperrea** [comment]
P.S. I am getting inconsistent results when running the spec on the current master branch. Is this normal?

$ apm -v
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.2

**Comment by 50Wliu** [comment]
> P.S. I am getting inconsistent results when running the spec on the current master branch. Is that normal?

Nope.  If you are getting inconsistent failures, it may be useful to report them as a new issue.

You're probably more likely to get help on the things you're stick with if you create a WIP PR.

**Comment by bmperrea** [comment]
Thanks @50Wliu . I just opened a [WIP PR](https://github.com/atom/find-and-replace/pull/944). I will open an issue about the spec failing inconsistently (a random assortment of tests fail each time) tomorrow if I haven't figured it out.

**Comment by bmperrea** [comment]
![camel_to_snake](https://user-images.githubusercontent.com/5274371/29745891-776b6478-8a95-11e7-8b30-ba5033d0e27c.gif)

**Comment by Gabb1995** [comment]
I used this to uppercase my regex selection ` perl -pi -e 's/-([a-z]{2}) \{/-\U$1 {/g' somefile.css`

my regex was `[a-z]{2} {`

for example icon-flag-au { to icon-flag-AU {

**Comment by lee-dohm** [comment]
We've reviewed this concept at length and, unfortunately, this isn't something that the team wants to maintain long-term. Our apologies for taking so long to come to a decision on this. We do believe that this would make a very interesting community package, however.

**Comment by Swivelgames** [comment]
@lee-dohm Bummer. Could really use this right now :(
