### ISSUE TITLE
Slow regexp

### ISSUE THREAD

**Issue by sergeyklay** [atom/find-and-replace#418]
File for test: https://github.com/stibiumz/incubator/blob/24d8b32ecfb6596b9e6862b3a62d2697e5c53228/tests/Phalcon/Mvc/Model/EagerLoading/resources/schema.sql
Result: 
![selection_027](https://cloud.githubusercontent.com/assets/1256298/8393146/90b12f9e-1d0a-11e5-8f62-ebec003ad282.png)

**Comment by benogle** [comment]
Closing as a duplicate of #145
