### ISSUE TITLE
"Finding with options" is different in single file and Project find

### ISSUE THREAD

**Issue by a7madgamal** [atom/find-and-replace#421]
"Finding with options" for single file:
![single](https://cloud.githubusercontent.com/assets/939602/8406865/3b317724-1e61-11e5-988f-484791d14133.png)
"Finding with options" for Project:
![project](https://cloud.githubusercontent.com/assets/939602/8406866/3b344116-1e61-11e5-9f7d-e842c13abef8.png)

why the "whole word" or exact search find option is missing!?

Atom 1.0.0 on Mac 10.10.3

**Comment by mnquintana** [comment]
There's already [an open issue for "whole word"](https://github.com/atom/find-and-replace/issues/339), but there isn't for "exact search" yet, so I'm going to rename this issue to reflect the latter enhancement.

**Comment by benogle** [comment]
Closing this as now there is a whole word option, and the in selection option doesnt make sense in this context.
