### ISSUE TITLE
Start live searching only after 3rd character

### ISSUE THREAD

**Issue by andya9** [atom/find-and-replace#423]
Linux, Atom 1.0.0.
Currently find-and-replace will start looking for matching strings as soon as we start tiping; this means that if we begin with "e" it will look for every "e" in the file: with large files (but even when under 2mb) this will lead to atom freezing for many seconds.

It would be cool if we could prevent search until we arrive to something like the 3rd character (at least until we have better support for large files).

**Comment by benogle** [comment]
I'm going to close this in favor of #145 as it is in the same direction. There have been improvements recently, but as you said this degrades with large files.

**Comment by andya9** [comment]
Thank’you for pointing there @benogle !
