### ISSUE TITLE
Atom becomes unresponsive on searching large files for common search queries.

### ISSUE THREAD

**Issue by mbullington** [atom/find-and-replace#424]
I'm sure you might be aware of this already, but the find-and-replace will often make Atom become unresponsive (I have to Force Quit) when searching through large files for common searches, like a letter or a small phrase where there are many results.

This usually occurs when the find-and-replace package automatically searches for part of my search query while typing it, with files about 1.5MB in size. I'm also using Atom 1.0 on OSX 10.10.3. 

Perhaps stop trying to find matches after a configurable limit? You could then try lazily loading matches after the user iterates through enough, or wait till the user refines their search query. From a user-visible standpoint, this could be represented as something like '100+ matches'.

Thanks for taking this issue into consideration, it's really frustrating to have to reopen my workspace every time I don't type my search in fast enough.

**Comment by 50Wliu** [comment]
Closing this in favor of #145 - please subscribe there for updates.
