### ISSUE TITLE
Add double asterisk option for project search path

### ISSUE THREAD

**Issue by Yajo** [atom/find-and-replace#428]
To find a word in any Python file inside a tests folder, I write this path: `**/tests/*.py`, but there are no results. Seems like the double-asterisk does not work as expected (I expected it to work [as in Fish](http://fishshell.com/docs/current/index.html#expand-wildcard)). It would be a very nice improvement.

**Comment by benogle** [comment]
This now works in the latest version of atom

![screen shot 2015-07-30 at 4 13 01 pm](https://cloud.githubusercontent.com/assets/69169/8997404/e53a335a-36d5-11e5-927e-302ed8dd32b9.png)

**Comment by Yajo** [comment]
I'm sorry but this is still happening. In which version it is supposed to be fixed?

**Comment by Yajo** [comment]
Ah sorry, it was https://github.com/atom/find-and-replace/issues/578.
