### ISSUE TITLE
Find only option

### ISSUE THREAD

**Issue by alefragnani** [atom/find-and-replace#429]
Instead of always having **Find** and **Replace** options available when you hit `Ctrl + F`, it would be interesting to have an option to suppress the **Replace** option (maybe a button on its panel). So if I only want to **Find** something, it would take less space on editing area.

**Comment by DiogoAndre** [comment]
Could be a workaround solution to #451. Hit Ctrl + F once you get the find only panel, hit again while the panel is open and you get the replace option.

**Comment by benogle** [comment]
I think for now we're going to keep this with both boxes to avoid confusion.
