### ISSUE TITLE
Find settings are not shared between project find and buffer find

### ISSUE THREAD

**Issue by harai** [atom/find-and-replace#431]
Markers don't reflect case-sensitivity of the searched word even if Case Sensitive is checked.
![screenshot from 2015-07-03 07 53 49](https://cloud.githubusercontent.com/assets/515636/8489645/d9a33308-2158-11e5-8841-94ddf5bda1c5.png)

Likewise, Regex is also ignored.

**Comment by benogle** [comment]
My guess is that the case sensitivity of the buffer find is not checked. We should probably link the options in both search interfaces.
