### ISSUE TITLE
Replace in buffer should use selection as find-pattern

### ISSUE THREAD

**Issue by dwelle** [atom/find-and-replace#433]
When selected, `replace in buffer` command should use the selection as find-pattern so that you then have to only type the replace-pattern. Maybe I'm doing something wrong?

Win 7, Atom 1.0

![replace_in_buffer](https://cloud.githubusercontent.com/assets/5153846/8508468/380192b8-2272-11e5-94b0-994750242b54.gif)

**Comment by 50Wliu** [comment]
Looks like this was only implemented for Find, not Replace: #135.
