### ISSUE TITLE
Settings button doesn't show up

### ISSUE THREAD

**Issue by bronson** [atom/find-and-replace#439]
find-and-replace has settings so it seems strange that the Packages list doesn't show a Settings button for it...?

![bug3](https://cloud.githubusercontent.com/assets/1776/8539850/249df238-2435-11e5-9e5a-8034a344a538.gif)

**Comment by thomasjo** [comment]
I'm unable to reproduce, but I'm running `HEAD`. Are you able to reproduce in safe mode?

**Comment by izuzak** [comment]
I'm running the latest version of master (1.0.1-ed735d8) and was able to reproduce this:

![sett](https://cloud.githubusercontent.com/assets/38924/8542076/2fbe6ce8-2493-11e5-8db9-a08472bdf161.gif)

Seems like some packages have a Settings button, and some do.

**Comment by thomasjo** [comment]
This is really weird... it's missing here now as well. Heisenbug?

**Comment by izuzak** [comment]
This issue was moved to atom/settings-view#573
