### ISSUE TITLE
Search while typing: Regexp on and type "."

### ISSUE THREAD

**Issue by BlaM** [atom/find-and-replace#440]
This is not actually a bug, but may be worth thinking about: 

Some minutes ago I used find-and-replace to find a "regular expression" term. Then shortly after I needed to search ".tl" in my code. So I pressed CTRL+F and started typing. Didn't take long until I noticed that the RegExp flag was still set, because the editor locked up for some seconds highlighting every character in the file.

The simple solution would be to not "autohighlight" when the user just enters "." - but maybe there are other options?

**Comment by lee-dohm** [comment]
Or only auto-highlight when there are fewer than a hojillion results :grinning:
