### ISSUE TITLE
Doesn't search symbolic linked folders

### ISSUE THREAD

**Issue by ryanmclaughlin** [atom/find-and-replace#445]
I know there has been two issues about this already, but this is still not working. I am unable to search sym-linked folders.

I have the core setting enabled for following symlinks:
![2015-07-13 12 29 46](https://cloud.githubusercontent.com/assets/451112/8659887/8c6225c4-2962-11e5-9bd1-5139490e7e95.png)

Related fuzzy finder issue: https://github.com/atom/fuzzy-finder/issues/87

**Comment by thkdog** [comment]
Right click the symbolic folder in the project, then click 'Search in Directory', I can find nothing whatever I input

**Comment by thkdog** [comment]
Because node_modules are always symbolic, this problem affects a lot...

**Comment by jblandry** [comment]
Is there a update on this ?

**Comment by jblandry** [comment]
If I think this correctly. Is it possible that the index keeps only the resolved path of a symlink as a reference making the symlink path unindexed ?

```
abc/
def/
ghi → abc
```

Index contains only `abc` and `def` as `ghi` is a symlink to `abc`, making a search under `ghi` useless.
