### ISSUE TITLE
Request for Collaborator status. WAS: There's no way to exclude paths from a search

### ISSUE THREAD

**Issue by kylegoetz** [atom/find-and-replace#449]
Hi. I was working on a fix for #149 (in fact it's been completed for weeks but I'm having difficulty figuring out how to do unit tests, which is what another collaborator told me I had to do before my PR got accepted).

But the thread just got locked to all but collaborators. Can I get marked as a collaborator so I can actually consult with people on the issue?

I wouldn't have opened a new issue for this, except someone on the official IRC channel told me that's what I should do, and because there's no PM feature to message any collaborator. And I'm pretty lost on the unit testing stuff. So it's done and the issue could actually be closed if I could get help on making unit tests.

You can check out my progress via the PR or here: https://github.com/kylegoetz/find-and-replace

Thanks.

**Comment by 50Wliu** [comment]
Hey @kylegoetz, the best solution here would probably be for you to open a new PR.  Then, we can either unlock the issue, or direct everyone to your PR for feedback.  Does that sound like a good plan?

Also, by "official IRC channel", do you mean https://atomio.slack.com?  If not, you can join [here](https://atom-slack.herokuapp.com).

**Comment by benogle** [comment]
This was fixed in atom/scandal#29 and is out in 1.0.3
