### ISSUE TITLE
Find/Replace in Project does not have expected behavior when pattern field is empty

### ISSUE THREAD

**Issue by eliasak** [atom/find-and-replace#451]
It seems to me that in "Find in Project"/"Replace in Project" dialog, an empty pattern field does not mean the expected behavior.  I use notepad++ (NPP) and VisualStudio (VS) often, and in NPP the filter box is prefilled with "*.*" and in VS the "Look in" selection is prefilled with "Entire Solution".

It would be clearer if:
- the empty pattern field only replaces in the current/active buffer (safer) 
and/or
- the pattern field is prefilled with "*" or "*.*", as that is the behavior (currently) when the pattern field is empty

**Comment by benogle** [comment]
I assume you mean the directory pattern? Closing this as a wontfix. It comes with the Visual Studio functionality
