### ISSUE TITLE
Regex Finds more selections than it should

### ISSUE THREAD

**Issue by flanderb** [atom/find-and-replace#454]
Regex search for (\w*) on a simple list
PRSQIS
MNTMRC
ALPENA
OSCODA
ALCONA

shows 10 results(14 when whole word is not selected). 
![find5not10](https://cloud.githubusercontent.com/assets/1275871/8829745/5482e494-3066-11e5-9450-eef0a7a36cac.PNG)

 It creates an issue when doing a replace as it replaces twice.
![replacetwice](https://cloud.githubusercontent.com/assets/1275871/8829750/5a0e9c82-3066-11e5-99bf-b4fac13b3695.PNG)

Running:
find-and-replace 0.174.2
Atom 1.0.2
Windows 7

**Comment by 50Wliu** [comment]
Confirmed.
Here's something else interesting: Undoing the Replace All doesn't completely reset the number of results found.  For example, I've undid the replace 3 or 4 times, and now there's 3686 results found.
Pressing Find Next goes from 1 (selects first word) to 318 (cursor at end of first word) to 761 (selects second word)...etc.

**Comment by jeancroy** [comment]
searching for `\w+` instead of `\w*` should fix it on your side.

Issue is \w* ask for 0-or-more repetition of a word character.
And there happens to be a 0-repitition of \w just before line feed.
(And there will be two if using CRLF)

This is CORRECT by regex spec. Regex that can match empty string are tricky.
Some editors like Webstorm behave like that.
Other like Sublime filter out 0-length match.

**Comment by jeancroy** [comment]
enter `aaaabbbb` in buffer

search `a*`
replace `c`
result `cccbcbcbcbc`

enter `aaaabbbb` in buffer

search `a+`
replace `c`
result `cbbbb`

**Comment by flanderb** [comment]
Thank you JeanCroy.  jEdit, what I am coming from, filters out the 0-match as well.  After working with jEdit for so long I have always just used * and thought nothing of it.   Sorry for the mistake.

**Comment by jeancroy** [comment]
I don't believe there's anything to be sorry about.
There's a lot of ppl that know `*` from minimatch / glob and don't know `+` 
so filtering 0 is friendlier i guess. Plus keeping a match in between every negative char probably don't help performance.

**Comment by maxbrunsfeld** [comment]
A lot of people are finding it surprising that we now ignore 0-length matches, and are reporting it as a bug. For example, it removes the ability to search for `^` or `$` (https://github.com/atom/find-and-replace/issues/497).

I'm thinking that it was actually better the way it was before: if you search for a pattern that matches the empty string, you get a lot of matches. Alternatively, if we want to get *really* fancy, we could ignore any 0-length matches if there are any matches of non-zero length. I tend to think we should not get that fancy.

**Comment by jeancroy** [comment]
Oh well it looks like some people have good use for zero length. Sorry for creating confusion.
I agree that it's better to not block anyone. Just tested sublime 2 & 3, they don't block zero length. Not sure why I tough they did.

I still find that many regex that can match something or not create confusing result, but that fit in the fancy case.
