### ISSUE TITLE
Escape search string on use-selection-as-find-pattern and Regex enabled

### ISSUE THREAD

**Issue by adamfranco** [atom/find-and-replace#455]
Currently, if the Regex option is enabled and the `use-selection-as-find-pattern` command is triggered on a string like `function foo($bar) {`, then the find-window's search string won't actually match the selection since the characters in the string don't make for a valid regular expression.

If the Regex option is selected, then the selection string should be escaped when triggering `use-selection-as-find-pattern` so that it is a valid regular expression.

**Comment by izuzak** [comment]
Semi-related: https://github.com/atom/find-and-replace/issues/366

**Comment by adamfranco** [comment]
Pull request #456 is now working with the "show" action as well as in the project-find dialog and is ready for review. Thanks!
