### ISSUE TITLE
When looking for string in minified css file, Atom editor freezing.

### ISSUE THREAD

**Issue by KiYugadgeter** [atom/find-and-replace#457]
When looking for string in minified css file, (e.g bootstrap.min.css) Atom editor freezing.

OS: OS X 10.10.4
Atom: 1.0.2

**Comment by benogle** [comment]
Thanks for reporting. This is a duplicate of #145 #152

**Comment by JTFouquier** [comment]
I'm on Atom 1.3.2 and I am having this issue. I looked at issues referenced above and they are both closed. I also looked at other related issues and all are closed.  My file as minified is 152 kb. Usually I have to shut down Atom when I open this file, so I have to use another editor.  Any thoughts?  Thank you!
