### ISSUE TITLE
Find in Project creates a new process for each search

### ISSUE THREAD

**Issue by alefragnani** [atom/find-and-replace#459]
Hi,

Every time I execute **Find in Project**, a new `atom.exe` process is started. No matter if I execute *n* search at once, or close and reopen the **Find in Project** pane, it will always start a new process for every search *for different arguments*. 

Atom itself starts with 4 processes, and after 3 consecutive searches, it will have 7 processes. The number of processes goes on, for each new search. I could see at least 27 processes :confused: while using it today, 

I don't know if this is intentional or not, but if is intentional, it should at least be limited to lower limits (3 for instance), and reuse already created processes.

![find-in-project-atom-processes](https://cloud.githubusercontent.com/assets/3781424/8864716/c6d1e0c0-317b-11e5-975e-9a7139fcc0ab.png)

**Comment by benogle** [comment]
Legit. I can reproduce this on a mac as well.

![screen shot 2015-07-28 at 2 11 12 pm](https://cloud.githubusercontent.com/assets/69169/8943959/85eac9b8-3532-11e5-9bf5-b70c7fa050e4.png)

**Comment by benogle** [comment]
Thanks for reporting this and connecting it to find and replace
