### ISSUE TITLE
Issues with replacing newline

### ISSUE THREAD

**Issue by rjbergerud** [atom/find-and-replace#462]
I'm having issues making this work.  I have an html string with lots of return statements as in 
 
```html
<a class="js-features-page usage-logging-enabled" href="https://www.google.ca" page-name="linkedChannels">
	<i class="icon-bar-chart-o"> </i>
	          <span data-i18n="menuSidebar.linkedChannels">Linked Seller Accounts</span>
</a>
```

I would like to replace all newline characters by either escaping them with a backslash or simply replacing them with whitespace.  I can select them by using the regex option, but when I go to replace them with other characters, it simply appends them after the newline.

**Comment by benogle** [comment]
What kind of line endings do you have? Can you try replacing `\r\n`? I assume you have the `regex` option set.

**Comment by rjbergerud** [comment]
Hey Ben Ogle - yeah, that does the trick.  What's the difference between \r and \r\n?  Reading up on this, it seems to depend on your OS?

**Comment by benogle** [comment]
Yeah windows uses different line endings.
