### ISSUE TITLE
"Search in Directory" is unreliable and not searching all files :(

### ISSUE THREAD

**Issue by zyklus** [atom/find-and-replace#463]
Atom 1.0.2

This seems to happen on larger directories, and I've run into it a few times now but don't have a consistent reproduction case --

Search in files often turns up empty or partial results.  The only thing I did between taking the following screenshots was:

- open a few files in the directory
- re-do search

<img width="335" alt="screen shot 2015-07-26 at 11 58 14 am" src="https://cloud.githubusercontent.com/assets/320562/8892520/da6dc310-338d-11e5-9146-0ea58e1a4bd4.png">
<img width="267" alt="screen shot 2015-07-26 at 11 58 34 am" src="https://cloud.githubusercontent.com/assets/320562/8892522/dca07a10-338d-11e5-8a6c-e74bcf833031.png">
<img width="266" alt="screen shot 2015-07-26 at 11 58 44 am" src="https://cloud.githubusercontent.com/assets/320562/8892524/df6edd7c-338d-11e5-8951-f76b404c3c0e.png">
<img width="237" alt="screen shot 2015-07-26 at 11 59 02 am" src="https://cloud.githubusercontent.com/assets/320562/8892525/e0b9bc88-338d-11e5-8fc4-257afae362db.png">

**Comment by benogle** [comment]
Which files do you have open in each of these cases? When the file is open in the editor, it does the search in a different codepath than when the file is closed.

**Comment by benogle** [comment]
Also can you paste in the result of running `atom.config.get('core.ignoredNames')` from the atom console? (open the console via the devtools with `cmd-option-ctrl-i`

**Comment by 50Wliu** [comment]
<kbd>Ctrl+Alt+I</kbd> if on Linux or Windows.

**Comment by benogle** [comment]
Closing as further information was not provided. If you get to reproducing this again, in addition to the the information asked for in the previous comments, please provide very specific steps to reproduce including a project I can clone and run the specified search on. 

Note that it is probably adding the results from open buffers when they are opened.
