### ISSUE TITLE
Paths excluded from search and then reincluded are not searched with find-and-replace

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [atom/find-and-replace#466]
Using `ignoredNames`, adding a path, let's say, `node_modules` and then removing it doesn't "force a reindex", ending up no file being searched in node_modules directory after it's allowed again.

I can't stress this enough, I'm not sure of this but the other bug was notifying too many people.

**Comment by benogle** [comment]
Find in project doesnt keep an index, so stale state should not be an issue.

* How are you adding the value to `ignoredNames`? 
* How are you removing the value from `ignoredNames`? 
* Is `node_modules` gitignored? Can you paste in your git ignore?
* What are you entering into each field in find in project?

Can you give me super clear, detailed steps to follow to reproduce this?

**Comment by Fire-Dragon-DoL** [comment]
@benogle You can close this issue. I completely forgot about the gitignore and unfortunately, node_modules was there. Tested with a different directory and works fine.

**Comment by benogle** [comment]
Cool, thanks for letting me know.
