### ISSUE TITLE
Allow navigating to previous results

### ISSUE THREAD

**Issue by bronson** [atom/find-and-replace#467]
I often want to see a previous project find's results...  Maybe 'back' and 'forward' buttons could be added to the Project Find Results tab?  That way I can do a big search, do a quick search, and then hit the back button to go back to my big search results.  Later I'd hit forward to go back to the quick search, and so on.

It would make it much easier to chase down rabbit holes using Atom.

I probably want this because vim has :cold and :cnew commands ([description](http://thepugautomatic.com/2014/03/stacked-vim-searches-down-cold/)) -- very useful!

This might be related to https://github.com/atom/find-and-replace/issues/360.  Implementing one would reduce the need for the other but I hope both could be provided one day.

Tag me enhancement!

**Comment by UziTech** [comment]
@sadick254 this should be closed based on https://github.com/atom/find-and-replace/pull/1112#issuecomment-756297777
