### ISSUE TITLE
ctrl-d not listed in key bindings but is used

### ISSUE THREAD

**Issue by RolandHughes** [atom/find-and-replace#483]
![screenshot from 2015-08-11 13 24 37](https://cloud.githubusercontent.com/assets/1883220/9206299/8a3aec28-402c-11e5-98c6-667c1da22d9e.png)
ctrl-d is not listed in key bindings, but is used for find-and-replace:select-next. This is a real problem on Ubuntu 15.04 64-bit Unity desktop when one wishes to map ctrl-d to delete-line as it really should be. One cannot override the key binding so one has to disable find-and-replace.

**Comment by benogle** [comment]
You should be able to remap it by doing the follwing:

1. Remove the `unset!` line from your keymap
1. Prefix the selector for your override with `.platform-linux` so it has the same specificity as the original binding

If that does not work, can you share your keymaps file?

**Comment by benogle** [comment]
Please reopen if you arent able to override the keybinding. I'm 99% sure it's a specificity issue, and that `unset!` line is not helping.

**Comment by RolandHughes** [comment]
Putting the platform in seemed to work. unset! appeared to be the method the manual recommended though. Might want to update documentation.
