### ISSUE TITLE
Find in Project caches prior search results

### ISSUE THREAD

**Issue by izuzak** [atom/find-and-replace#490]
_From @fungilation on August 12, 2015 1:53_

For example: ![screenshot 2015-08-11 18 50 00](https://cloud.githubusercontent.com/assets/3803466/9215014/deff6ba8-4059-11e5-9bd1-3dfef03dac26.png)

The search for "rsvpOptions" doesn't search what is intended. It immediately comes up with results of prior search, on "mainGuest". I can force an actual search by changing say, the case sensitivity setting in the Find in Project panel.

I noticed this only today, after updating Atom to 1.0.6. Can't say if this is bug in Atom or some misbehaving package I'm using. (Is there a way on cli to launch Atom with non-core packages temporarily disabled to test?)

_Copied from original issue: atom/atom#8338_

**Comment by izuzak** [comment]
I've noticed similar strange things with find and replace after upgrading to 1.0.6 (e.g. searching in project returns no results when there should be -- see https://github.com/atom/find-and-replace/issues/373#issuecomment-130194295). /cc @benogle

**Comment by ryedin** [comment]
Concurred. First got no results, then finally got it to show some results, but now shows the same results no matter what.

Atom 1.0.6; find-and-replace 0.177.0;

**Comment by benogle** [comment]
Repro'd. Looking into...

**Comment by bradbeck** [comment]
After updating to 1.0.6, I noticed that Find in Project initially returns no results for a search that I expect to return many results. After waiting several minutes and executing the search again, I finally see the results I expect.

If it is indexing or something behind the scenes, then I think the user should be informed that is what is happening and not simply told that the search returned no results.

Or in some cases it will pop up the results from a prior search that did return results. e.g. I search for "component" but I'm presented with the results of a prior search for "immutable".
