### ISSUE TITLE
Occasionally find-replace isn't searching at all, just displaying previous results

### ISSUE THREAD

**Issue by bobber205** [atom/find-and-replace#492]
Tried pretty hard to repo this reliably but here's my story.

Quite often after today's update of 1.0.6, especially after recently searching for something else, I press Comamnd E then Command Shift F to do a search all.

I get something like the following in the tab with the results.

![image](https://cloud.githubusercontent.com/assets/5841107/9236768/a83ffe78-40fb-11e5-91ca-e32beda1eef4.png)

It's says it searche for clear_cache! but clearly it's showing the results of "aa" search.

**Comment by benogle** [comment]
Sorry about that, it should be fixed in the next release. See #490

**Comment by bobber205** [comment]
Awesome! Thanks <3
