### ISSUE TITLE
Find in project always does not work well

### ISSUE THREAD

**Issue by Araon** [atom/find-and-replace#495]
my atom version is 1.0.6(mac), and today i find the "find in project" function does not work well after i tap enter button.
sometimes the result is empty. sometimes the result is the result i searched last time. I do not know why.

when i input some condition in the directory pattern, it works again.

there is no problem before. the packets i installed are : docblockr, file-icons, git-plus, git-projects, highlight-line, highlight-selected, language-lua, merge-conflicts, script.

**Comment by benogle** [comment]
Can you upgrade to 1.0.7? It should be fixed. If it isnt fixed in the latest version, please reopen.
