### ISSUE TITLE
Immediate replace or replace all no longer possible

### ISSUE THREAD

**Issue by adambuczynski** [atom/find-and-replace#502]
When I enter something in the find and replace fields, I can't hit the replace or replace all buttons, they are disabled with the mouse cursor turning into a disabled one on hover. I explicitly have to press find first, before I'm allowed to do replacements.

![ss](https://www.dropbox.com/s/miknh9dg5uo83z4/Screenshot%202015-08-18%2008.32.44.png?dl=1)

Is this a bug or is it supposed to be a new feature?

It used to be possible to simply hit replace right away. The current behaviour is slowing down my work flow and introducing unnecessary clicks?

**Comment by benogle** [comment]
It's because live search is only invoked then >= 3 characters are typed. You can set the option in the find and replace settings to 1 to get the old behavior.

**Comment by adambuczynski** [comment]
Ok, thanks. Can the buttons replace / replace all not be unlinked from the live search?

**Comment by krainboltgreene** [comment]
Uh, I'm getting this with "Blankgem" -> "Rubyscript", any particular reason?
