### ISSUE TITLE
Replace All disabled button isn't informative

### ISSUE THREAD

**Issue by Maelstrome26** [atom/find-and-replace#504]
I think there is an issue with the Replace All functionality.

I'm seeking to find "inheritDoc" and change it to "inheritdoc". I'm unable to do this and there isn't an explanation as to why.

To illustrate the issue, I've provided a screenshot:

![atomfindbug](https://cloud.githubusercontent.com/assets/1776058/9355788/043c1bd0-4674-11e5-989b-7e7d5b304504.png)

**Comment by mnquintana** [comment]
Just to clarify, are you trying to replace all instances in that file, or across your whole project?

**Comment by Maelstrome26** [comment]
Ideally both. Neither seem be working.

I'm tempted to open another separate issue regarding that the package doesn't clearly say whether you're searching within a project or just the file. Ideally it would be nice to have the option to do one or both.

**Comment by mnquintana** [comment]
Did you hit enter to perform the project search? Replace All is disabled until you perform a search, to prevent accidentally permanently replacing things without knowing what you'll be replacing.

> I'm tempted to open another separate issue regarding that the package doesn't clearly say whether you're searching within a project or just the file.

I think it does:

<img width="421" alt="find-and-replace" src="https://cloud.githubusercontent.com/assets/823545/9355989/b784e664-464b-11e5-84ab-dda055c5391d.png">
<img width="326" alt="find-and-replace" src="https://cloud.githubusercontent.com/assets/823545/9356033/fbe5ce86-464b-11e5-8fda-90b8c58f5daa.png">

**Comment by Maelstrome26** [comment]
Ahh, my mistake on that point, thanks for highlighting it out. Maybe altering the text on the button to say "Find all in Project" or "Replace all in Project" would eliminate any confusion.

Ideally, there should be two separate buttons for the Control-Shift-F functionality. I assume that when you press Enter you wish to do a search for it, however the option to directly replace it there and then should be implemented how it is now with a button.

**Comment by Maelstrome26** [comment]
For an example, from Sublime Text, this is how they've done it:

![sublimeexample](https://cloud.githubusercontent.com/assets/1776058/9356229/41493032-4677-11e5-9049-a5716cf87866.png)

So you can see they offer a Find and also a Replace button, which are both separated. Therefore giving the user the choice rather than assuming their intent.

**Comment by Maelstrome26** [comment]
Renamed the title to a more appropriate one for the discussion. The functionality is working, but it's more of a UX issue now.
