### ISSUE TITLE
Feature request: Folder exclude filters

### ISSUE THREAD

**Issue by derwaldgeist** [atom/find-and-replace#507]
I'm coming from Brackets, where the Find & Replace offers a neat option to define exclude filters for certain folders.

This is especially important for output folders like /dist or Meteor's .meteor/ folder which contain more or less a compiled version of the main webapp code. If you include these folders, your search results will be doubled. 

Often, it also does not make sense at all to search in bower_components/ or node_modules/ folders.

In the Atom find-and-replace, I only found a way to limit the search to certain file patterns.

**Comment by izuzak** [comment]
You should be able to exclude files and folders, as described in https://github.com/atom/scandal/pull/29 which fixed https://github.com/atom/find-and-replace/issues/149. If that's not working for you, including a link to a specific project with the exact search parameters which you tried would help us investigate further and provide advice.

**Comment by derwaldgeist** [comment]
@izuzak: Thanks for your fast reply, though I still have no clue how to use these inclusions, globalExclusions etc. correctly (I assume they are documented somewhere, so I'll have to dig a bit deeper in the documentation of Atom).

Yet, besides this, I still think that having a configuration file as a solution is a bit suboptimal. I would like to recommend having a look at how Brackets solves this problem by allowing the user to define exclude patterns on the fly and store them for later. This is much more convenient. Maybe that's something a plugin package for Atom could provide. Well, I'll dig deeper into Atom, and who knows, maybe someday I'll be able to write such a package myself :-)

**Comment by izuzak** [comment]
@derwaldgeist To exclude a folder, prefix it with `!`, as mentioned in the pull request I linked to.

> And finally, maybe we dont want to search in the `tests` directory, so lets add a new negation for that. At this point the paths input in find and replace would look like: `vendor, !*.md, !test/`

Does that help?
