### ISSUE TITLE
Project find and replace improvements

### ISSUE THREAD

**Issue by a7madgamal** [atom/find-and-replace#511]
Although I'm really glad I switched from Netbeans to Atom and I love many things about it. I do miss some features in the Project wide Find\Replace functionality so I will try to list them here:

1. I think the results screen shouldn't be a normal tab because sometimes it's harder to find it when many taps are open!
I think It's better to have results as a panel instead of a normal tab

2. I should be able to have multiple search\replace instances without having to reuse the same instance! sometimes you want to search for multiple keywords and currently I'm only able to have one search instance at a time

3. When replacing, it's VERY important to be able to select or filter out some results. It really sucks when I want to replace 99 results from 100 and I cancel the whole thing just for one result I want to skip!

That's my basic thoughts and after discussing we can find a more specific features and I can then split them into different features or tickets
Now I really have to go back to work :D

**Comment by 50Wliu** [comment]
Hi there @a7madgamal, can you please separate this issue into two different ones (one about your 1st point, and 1 about your 3rd) so that there's a definitive focus on each one?

Your second point is already being tracked under #360.

**Comment by a7madgamal** [comment]
Done.
You can close this one if you want

**Comment by a7madgamal** [comment]
Done :)
