### ISSUE TITLE
Exclude file right-click option when using Replace All

### ISSUE THREAD

**Issue by jiku** [atom/find-and-replace#514]
Just a feature request for Replace All. Right click a file in the results and opt to exclude it from being affected by the replacement. Unless it already exists or there's some other, better way of doing it without having to step over each instance in the file or altering the search pattern.

**Comment by mnquintana** [comment]
Related to https://github.com/atom/find-and-replace/issues/513

**Comment by benogle** [comment]
Closing in favor of #513 as that's likely the route we would take.
