### ISSUE TITLE
CMD-D should only select full words if a full word is selected

### ISSUE THREAD

**Issue by zyklus** [atom/find-and-replace#519]
It shouldn't select partial words if a full word is selected.

Atom:

![atom](https://cloud.githubusercontent.com/assets/320562/9629044/622f9170-51a2-11e5-9a0c-e7837e111b21.gif)

ST3:

![subl](https://cloud.githubusercontent.com/assets/320562/9629047/65938628-51a2-11e5-9e59-1bb51d46fca9.gif)

Atom 1.0.9

**Comment by izuzak** [comment]
I believe that's intentional. Check out https://github.com/atom/find-and-replace/pull/482 for context and advice.

**Comment by izuzak** [comment]
And let me know if I misunderstood your report :grin:

**Comment by zyklus** [comment]
Thanks.  Shouldn't this be in 0.180.0?  I don't see a `wholeWord` option in the package.

**Comment by izuzak** [comment]
> I don't see a wholeWord option in the package.

That's in the UI:

<img width="299" alt="screen shot 2015-09-02 at 12 53 27" src="https://cloud.githubusercontent.com/assets/38924/9629270/a37c9cda-5171-11e5-8c65-364e79ae9338.png">

**Comment by zyklus** [comment]
Nevermind, found it :)  Thanks.
