### ISSUE TITLE
Select next selects all text between current selection and the next selection

### ISSUE THREAD

**Issue by sethlopezme** [atom/find-and-replace#520]
When performing select-next, all text is selected from the first character of the current selection, to the character just before the next selection. This was tested in safe mode, as well (see gif below).

![atom-select-next-bug](https://cloud.githubusercontent.com/assets/5733658/9649690/4c29d114-51c6-11e5-8c10-8990202f9e86.gif)

My setup:
Atom v1.0.11
Apple MacBook Pro
Mac OS X 10.10.5

Possibly related to atom/atom#8369? The reason I say this is that if I wait a second or two after my first selection and then initiate the select-next, the issue doesn't appear.

**Comment by izuzak** [comment]
Thanks for the report, @sethlopezme -- I'm seeing that problem as well.

> Possibly related to atom/atom#8369? The reason I say this is that if I wait a second or two after my first selection and then initiate the select-next, the issue doesn't appear.

These problems do look similar, you're right. I'm going to :phone: a :octocat: -- @nathansobo it seems like we need to apply the same medicine :syringe: to find-and-replace as we did in Atom core?

**Comment by nathansobo** [comment]
Yeah. We probably need to synthesize a mouse up on *any* command being dispatched. Unfortunately when I tried this the other day I got entangled in some of our shims to support the deprecated jQuery APIs that are no longer needed. I'm going to look into removing the code that was causing issues and then address this in a general way. Stay :tv:ed.

**Comment by Ben3eeE** [comment]
Closed via https://github.com/atom/atom/pull/15916
