### ISSUE TITLE
Please separate "whole word" option in CMD+D vs Find cases

### ISSUE THREAD

**Issue by zyklus** [atom/find-and-replace#521]
These aren't the same thing to me and it seems very odd that they're the same option.  Personally I like how CMD+D works with this option on (it searches for a whold word if and only if you have a whole word selected).  But I almost never use this option when opening a find dialog.

Personally, I think the CMD+D case is personal preference -- Either you expect it to select a whole word or not and you expect it to act like that globally.  I'd put that option in the package settings.

**Comment by benogle** [comment]
> Personally I like how CMD+D works with this option on

This used to be the default behavior, but many many people thought it was a bug. See https://github.com/atom/find-and-replace/pull/482 for the change, and related linked issues. 

Closing as I am inclined to leave this how it is for a while until a better solution emerges. I'm not sure that a global setting is the right move.

**Comment by zyklus** [comment]
:( can I point out that the old way is how ST3 works, and has worked for ages?

I don't know the solution, but please do something, as this is unusable to me (well I don't care that much since I patched find-and-replace, but still...)

**Comment by benogle** [comment]
It seems more consistent and intuitive to the majority of folks, though, to follow the behavior of find. Maybe an option would be ok, but I am not super keen on adding one as most people wont find it, and there is an option now by setting whole word to true.

**Comment by zyklus** [comment]
> It seems more consistent and intuitive to the majority of folks, though

Okay, but is the best response to placate the majority and to break existing functionality for other users?  I think you're just going to have the opposite problem for other users now -- everyone coming from ST3 is going to say it's broken :)

I asked about this on Slack just now -- out of 4 of my colleagues that responded (none Atom users), nobody thought to look in the Find panel to change CMD+D behavior.  And once I explained it one person had the same objection I do -- that you can't disassociate the two.  I personally don't think they have any logical connection -- I rarely (though sometimes) use CMD+D to actually _find_ other instances of what I have selected.  I usually just use it to either select the current word (so I can delete it, for instance) or quickly get multiple cursors of things that are right in front of me, so I don't even think of it as a "find" tool, rather a "select" tool.  Having the two associated leaves me with the choice of fundamentally "breaking" one or the other, or having to toggle an extra option every time I actually want to find something.  (since I use CMD+D about 5,000 times/day I prefer it to work "correctly" over find)

Just "thinking out loud", but what about the possibility of having the keyboard shortcut toggle the option for CMD+D when the find panel is closed and having it toggle the option in the find panel when it's open?

> I am not super keen on adding one as most people wont find it

I don't think most people particularly care.  Most devs I've seen rarely use multiple cursors to the extent I do.

**Comment by colllin** [comment]
How about at least making the Whole Word keyboard shortcut available globally?

This change is so bad that I'm considering switching back to Sublime, after being on Atom for what feels like forever.

**Comment by colllin** [comment]
@zyklus can you turn your patch into a package?

**Comment by zyklus** [comment]
@colllin - I stopped using Atom after about 2 months of legitimately trying to switch, making several plugins, contributions, etc.  If you want to make it a package, go ahead :)

**Comment by benogle** [comment]
> How about at least making the Whole Word keyboard shortcut available globally?

This is a good call for all the fnr options.

**Comment by jeancroy** [comment]
What bother me it there is no way to know what options are active, or change them without doing `cmd-f`, but then find&replace take the control and we loose the `cmd-d` work.

Maybe the ultimate solution would be to `cmd-d` to have it's own pane. A one line version of the find/replace with only the `Finding with option: [ .* ] [ Aa ] [ = ] [ ||| ]` section.

Global keyboard, fix the ability to change option, but doesn't help to discover what toggles are active.

**Comment by colllin** [comment]
Wait a second, I thought the original behavior in ST handled this really well.  Atom never had it right, even previous to v1.1.  Here's how I think it worked in ST:

If you originally have no selection (just a cursor in a word somewhere), and you use `cmd-d` to select that whole word, then the following presses of `cmd-d` will match only whole words.

If you created your initial selection by any other means (e.g. clicking and dragging to highlight a whole word), then the following presses of `cmd-d` will match anything (not just whole words).

**Comment by benogle** [comment]
> If you originally have no selection (just a cursor in a word somewhere), and you use cmd-d to select that whole word, then the following presses of cmd-d will match only whole words.
> 
> If you created your initial selection by any other means (e.g. clicking and dragging to highlight a whole word), then the following presses of cmd-d will match anything (not just whole words).

Atom used to do that, and people didnt expect it.

**Comment by colllin** [comment]
Thank you for taking the time to respond to me.  I know this issue is marked as closed.

When did Atom do that?  I reverted to v1.0.6 (before the PR mentioned above was merged in), and I'm not seeing it.  Here's what I see in v1.0.6:

Atom behaves the same both ways - matching only whole words with cmd-d.  In this video, first I make the initial selection using `cmd-d`, and press cmd-d until all matches are selected.  Next, I make the initial selection using the mouse, and then press cmd-d until all matches are selected.

Screen recording (Atom): http://cl.ly/2m3W0M2t3z0g

Here's a video of how it works in ST3.  First I make the initial selection using cmd-d, and it works the same as Atom.  Then I start over and make the initial selection using the mouse.  Now when I press cmd-d to select all matches, it matches partial words as well.

Screen recording (ST3): http://cl.ly/22111L2P1z1A

**Comment by yamsellem** [comment]
I'm agree with @colllin and @zyklus, I'm using Atom for a year now and looking in the Find panel to change CMD+D behavior never hits my mind (I had to come here to understand the trickery).

A global setting for CMD+D seems fine to me (detached from search).
Simple and pleases everyone.

_Another brick in the wall_: is there a way to make the CMD+D smarter?
Selecting a variable and searching next do not have to select string, IMO.
This ruins refactoring — which is the purpose of that shortcut to me (_why on earth will I want to select both strings and variables of the same name?_).

![text matching](https://cloud.githubusercontent.com/assets/606754/10864247/5f5e3b12-7fe8-11e5-8834-237ade3d7c1a.png)

Thanks.

**Comment by jeancroy** [comment]
At this point the option that make the most sens is a global along the line of:

[ x ] Link select-next (cmd-d) options to find & replace
Uncheck this to always search for whole words, unless you select part of a word.

--

The wholeWord option by itself probably change too often to be set in a global, but an option to link/unlink those options might please both camp.

**Comment by colllin** [comment]
It sounds like you're suggesting to keep the options linked, but to automatically enable the whole word option if the selection is a whole word. 




This is reasonable to me. It's similar to what I suggested, except my logic for whether to enable or disable "whole words" was based on whether you initialized the selection using cmd-d (which selects the whole word surrounding your cursor, which is why it's so confusing to not match further whole words by default).




Another option might be to add a second shortcut. Let cmd-d match whole words since first cmd-d does, and add cmd-shift-d or similar for matching "anything".

**Comment by jeancroy** [comment]
I'm suggesting to allow user to chose between linked option and previous behaviour (st3 compatible) .

**Comment by benogle** [comment]
> At this point the option that make the most sens is a global

I'm really opposed to having an option for this. It will be super unclear, and people will not find it. I think we should pick something and stick with it. 

Atom used to work like this (verified with 1.0.6)

```
1 test
2 test
3 test1
4 test2
```

1. Select `test` from line 1, hit `cmd-d`, it selects only test in line 1 and 2
1. Place cursor in inside `test` on line 1, it selects only test in line 1 and 2
2. Select `test` from line 3, hit `cmd-d`, it selects all test strings, because it detects that a whole word is not selected

So it worked just like sublime except when the word was already selected.

I'm fine accepting a PR to remove the connection to the option, and make it work exactly like sublime.

**Comment by jeancroy** [comment]
>I'm fine accepting a PR to remove the connection to the option, and make it work exactly like sublime. 

Wouldn't that be more thread along the ones that started the linked option effort ?

**Comment by benogle** [comment]
No, because it would remove behavior number 1 in my list above. In that case, it would select all instances of test and work exactly like sublime

**Comment by jeancroy** [comment]
> work exactly like sublime

This include this test case where it jump from full word to part of word and is case insensitive ?
![sublime](https://cloud.githubusercontent.com/assets/12763666/10955447/d5c40df4-8321-11e5-9f8c-421258239c7a.gif)


Basically cmd+d in sublime is a way to upgrade marker into selection.

**Comment by jeancroy** [comment]
And that would be behavior 2a (case insensitive search set to on):
![sublime5](https://cloud.githubusercontent.com/assets/12763666/10955764/3e3ea482-8324-11e5-923c-77e902988fc6.gif)

And behavior 2b (case sensitive search):
![sublime5b](https://cloud.githubusercontent.com/assets/12763666/10955822/9c9c15aa-8324-11e5-9633-bd91046e7008.gif)

**Comment by jeancroy** [comment]
And behavior 3a (middle of word selected + case insensitive)
![sublime3a](https://cloud.githubusercontent.com/assets/12763666/10955903/363c0698-8325-11e5-9c44-37e79887f185.gif)

And 3b (middle of word selected + case sensitive)
![sublime3b](https://cloud.githubusercontent.com/assets/12763666/10955912/428b8572-8325-11e5-8cc3-a3164757b359.gif)

**Comment by jeancroy** [comment]
It seems wholeword does not make a difference, but case is definitively linked.

**Comment by yamsellem** [comment]
This issue is opened for 3 months and every day since renaming & refactoring has been a hassle.
Just try to rename the i variable from a for loop, you will see how frustrating it is.

May we have a clear state on that issue?
Thanks.

**Comment by colllin** [comment]
Ben described a PR that he would accept.  I started on one last week, and I
think I can finish it today or tomorrow.

> On Nov 24 2015, at 3:58 am, yamsellem &lt;notifications@github.com&gt;
wrote:  

>

> This issue is opened for 3 months and every day since renaming &amp;
refactoring has been a hassle.  
Just try to rename the i variable from a for loop, you will see how
frustrating it is.

>

> May we have a clear state on that issue?  
Thanks.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/atom
/find-and-replace/issues/521#issuecomment-159229618).![](https://github.com/no
tifications/beacon/AALWQ--LiK3IgE3ZEGnprJs_tpwPbwIHks5pJDpjgaJpZM4F3Umn.gif)
