### ISSUE TITLE
Bare caret/dollar not found

### ISSUE THREAD

**Issue by bmhkim** [atom/find-and-replace#522]
I'm trying to do a regex search and replace for start-of-line in order to prepend text to all of my lines in a file. However, a search for the caret character ('^') returns no results. This seems like a defect to me, I believe other editors such as Sublime and BBEdit/TextWrangler support this behavior. Note that a similar issue exists for the dollar sign character ('$').

**Comment by peduxe** [comment]
This has been already reported here: https://github.com/atom/find-and-replace/issues/497

**Comment by 50Wliu** [comment]
Thanks @peduxe.  @bmhkim, please subscribe there for updates.
