### ISSUE TITLE
Not able to see the correct buttons.

### ISSUE THREAD

**Issue by paaljoachim** [atom/find-and-replace#524]
Hi

I am seeing this when I click cmd+f on my Macbook Pro running OS 10.9.5

![skjermbilde 2015-09-13 kl 09 02 33 am](https://cloud.githubusercontent.com/assets/5323259/9835667/63da1c64-59f6-11e5-9607-623af8ed47a1.png)

A very limited view of finding and replacing. How can I get the correct options/settings in place?
Thanks.

**Comment by 50Wliu** [comment]
Hi @paaljoachim, can you please elaborate what you mean when you refer to the "correct options"?  Thanks.

**Comment by paaljoachim** [comment]
Here is the screen I see from the readme. It is different then the one above.

![skjermbilde 2015-09-13 kl 04 26 40 pm](https://cloud.githubusercontent.com/assets/5323259/9837100/3c7e2f46-5a34-11e5-8b88-9f29e7f9099b.png)

**Comment by 50Wliu** [comment]
The README's picture is (I believe) outdated by over a year.  I'm working on updating it though, sorry for the confusion :frowning:.

**Comment by paaljoachim** [comment]
Well it is better then what I was seeing though as it includes the buttons: Find Prev, Find Next, Replace Prev and Replace Next.... Is there a way to turn these buttons on again? Making these visible?

**Comment by 50Wliu** [comment]
@paaljoachim in that case, please see #453 which asks for an option.

**Comment by paaljoachim** [comment]
Thank you!
