### ISSUE TITLE
Double clicking on search result focusses on last line unless file was open

### ISSUE THREAD

**Issue by adambuczynski** [atom/find-and-replace#526]
Search for a search term in files, then double click on of the results. Unless the file is already open, it will open the correct file, but fail to focus on the relevant line. Instead, focus goes to the last line of the file.

This is with Atom 1.0.11 on OS X, and is a regression from older versions of Atom because it used to work well.

**Comment by izuzak** [comment]
@adambuczynski I'm having trouble reproducing this on OSX. Can you share a GIF which demonstrates this and shows that you're in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

Here's what I see:

![search](https://cloud.githubusercontent.com/assets/38924/9904044/3c837660-5c7b-11e5-9bc9-37cfc669a11f.gif)

What you can't see is that I double-click on a search result. 

Do you see the same problem if you just click on a result, or is it just when you double-click?

**Comment by adambuczynski** [comment]
Thanks Izuzak, I've actually been unable to reproduce it in safe mode, and have since narrowed it down to the offending package, https://github.com/sindresorhus/atom-editorconfig.

I'll repost this issue there.
