### ISSUE TITLE
No results for Search in Directory/Find in Project

### ISSUE THREAD

**Issue by thSoft** [atom/find-and-replace#527]
I'm using OS X 10.10.5, a freshly installed Atom 1.0.11 (with only the core packages) and find-and-replace 0.180.0. When I add a project folder, start a search in it or any of its subfolders, no matter what I enter, what options I use, I get "No results found". I attach a screenshot showing that a file indeed contains the search string but it is not found.
![find-and-replace-no-results](https://cloud.githubusercontent.com/assets/118109/9936609/13991e66-5d5d-11e5-8941-eeaa7f3f883b.png)

**Comment by madranet** [comment]
I've been having the same problem.  Thought it was my RegEx-fu letting me down, but the same expression worked fine in TextMate.

In my case Atom was finding the search string in the currently open file, but not across the project.

[And yes, I was using 'Find in Project' not 'Find in buffer' by mistake!]

*OSX 10,9,5 – Atom  1,0,13 – Find & Replace 0,181,0*

**Comment by benogle** [comment]
Do you guys have public projects we can test this out on? A public project and very specific search terms would be most helpful.

**Comment by thSoft** [comment]
http://github.com/thSoft/Terminology

**Comment by benogle** [comment]
:heart: :heart:

**Comment by benogle** [comment]
I am not able to reproduce this:

![screen shot 2015-10-01 at 4 13 51 pm](https://cloud.githubusercontent.com/assets/69169/10236161/75c710d4-6857-11e5-8803-47b3b2622a78.png)

**Comment by benogle** [comment]
Do you have specific reproduction steps? Does this still not work for you? Can you upgrade to the latest version of atom (1.0.19)?

**Comment by thSoft** [comment]
Yay, it works with Atom 1.0.19! :)

**Comment by chris-martin** [comment]
I'm seeing this in Atom 1.8.0.

**Comment by barbalex** [comment]
this happens to me when I include `npm-debug*` or `npm-debug.log*` in .gitignore and have the core setting `Exclude VCS Ignored Paths` set
