### ISSUE TITLE
Highlight results on scrollbar

### ISSUE THREAD

**Issue by surdu** [atom/find-and-replace#529]
It would be nice to have this feature as in Chrome or other editors: when you search something, the position of the search results would be highlighted on the scrollbar to see where you have to scroll to see those results.

**Comment by mnquintana** [comment]
You can essentially get this now by installing [minimap](https://atom.io/packages/minimap) and [minimap-find-and-replace](https://atom.io/packages/minimap-find-and-replace). Does that about cover what you're looking for?

**Comment by surdu** [comment]
No. That occupies way to much horizontal screen real-estate. What I'm looking for is somthing more like this: 

<img width="444" alt="screen shot 2015-09-18 at 14 57 21" src="https://cloud.githubusercontent.com/assets/11520795/9958749/a55b6b48-5e15-11e5-85c1-0e13939b5a05.png">

**Comment by sabrehagen** [comment]
+1

**Comment by nunobaba** [comment]
+1
Visual Studio Code has that functionality. As the VSCode and Atom are Electron-powered, it might be a quick job to the code and turn into an Atom package.

**Comment by tuanzhang7** [comment]
+1
useful function, please add

**Comment by ilazarte** [comment]
Just tried out minimap for this, but its not the same.  You have to scroll in order to see the occurence in the file, whereas this feature would show all occurrences in the bar itself.  Much more useful than a minimap concept.

**Comment by krasi-georgiev** [comment]
I found this
https://atom.io/packages/scroll-searcher

but doesn't install

#573

**Comment by jessexknight** [comment]
Any update on this? 

I downloaded the [`scroll-searcher`](https://github.com/Aakash1312/scroll-searcher) package, but it throws [this error](https://github.com/Aakash1312/scroll-searcher/issues/25) and doesn't work.

**Comment by Daijobou** [comment]
+1 I love this.

**Comment by surdu** [comment]
It took a while but it's finally here. I give you: [find-scroll-marker](https://atom.io/packages/find-scroll-marker).

As a bonus, I also created [scroll-marker](https://atom.io/packages/scroll-marker) that provides a consumable that other packages (like the one mentioned above) can use to add other markers to the scroll bar. Documentation pending.
