### ISSUE TITLE
find in selection mode is frustratingly mystifying

### ISSUE THREAD

**Issue by AgentME** [atom/find-and-replace#534]
There might be a few issues in this, or there's something fundamental about how it works that I missed. I'm just going to write out my most recent experience after verifying it's reproducible.

1. Push cmd+f, turn off all of the regex, case sensitivity, within selection, whole word options, push escape to close it.
1. Open a pre-existing file.
2. Make a selection. Let's say it's over the word "function".
3. Push cmd+f.
4. Set the "Find in current buffer" field to "[a-z]", set "replace" field to "a", turn on regex mode and within current selection.
5. Somehow the only thing found is the 'u' in the originally selected word "function".
6. Push escape to close the finder.
7. Make a new selection. I've picked the word "var".
8. Push cmd+f.
9. Change the "Find in current buffer" field back to "[a-z]".
10. Push find. Things seem to work fine. Each individual letter of "var" is matched. Pushing "replace all" makes it into "aaa".
11. Push escape.
12. Make a new selection. Make a second disjoint selection simultaenously by selecting something else while holding command. (Take a few minutes to make many more selections over the file to get the whole experience if you wish.)
13. Push cmd+f. If your last selection spans multiple lines, then you will find that the "aaa" which used to be "var" will be what the finder considers to be your selection even if it's not part of your current selection, and all of the highlights you just spent time doing will be disregarded. Otherwise, only your last selection will be considered by the finder, even though all of your highlights are still visible until you hit find.

**Comment by benogle** [comment]
Closing in favor of #298. Your comment has been added to it as it is very detailed. Thanks
