### ISSUE TITLE
Changing the value of "Replace in project" re-enables a disabled "Replace All" button

### ISSUE THREAD

**Issue by fvsch** [atom/find-and-replace#537]
How to reproduce:

1. Create a empty project
2. Add a `test.txt` with this content: `QUERY_1 / QUERY_2 / QUERY_2`
3. Show the Find in Project pane.
4. Enter `QUERY_1` in Find in project, and hit Enter. (A Project Find Results page is shown, with 1 result found in 1 file.)
5. Enter `REPLACED_1` in Replace in project. (The Project Find Results page is updated.)
6. Change Find in project to `QUERY_2`. Do not hit Enter.
7. Hover then click the Replace All button. Nothing happens (which is good), and the button is shown as disabled.
8. Change the value of Replace in project to `REPLACED_2`. Do not hit Enter.
9. Hover the Replace All button (it is shown as active), and click it.
10. Atom asks: "Are you sure you want to replace all? This will replace 'QUERY_2' with 'REPLACED_2' 1 time in 1 file"
11. Click OK.
12. In `test.txt`, Atom replaced `QUERY_1` with `REPLACED_2`. The final text content is: `REPLACED_2 / QUERY_2 / QUERY_2`. The expected text content was: `QUERY_1 / REPLACED_2 / REPLACED_2`.

There are three issues here:

* In step 8, the Replace All button was re-enabled when the input changed, and not when the *performed search* changed.
* In Step 10, Atoms seems to be using two different kinds of information: the before/after values are the current values from the text inputs, and the number of replacements and files are from the latest performed search. As a result, the two sets of info do not match. (If we were about to replace `QUERY_2` as announced, there would be 2 replacements to announce, not one.)
* In Step 11, Atom performed a replacement using stale search data, and an up-to-date replacement string. (On a large number of files, the results can be catastrophic.)

**Comment by benogle** [comment]
Thanks, I plan to look at and fix all these button disable / tooltip issues soon.

**Comment by benogle** [comment]
Thanks for the detailed repro steps. It highlighted a largish bug

**Comment by swang** [comment]
Hi, is this fix in the latest release of atom? I am currently on atom v1.0.11 and ran into a bug that sounds similar to this one which cost me about an hour of work to properly undo. I would like to test to see if this patch fixes the issue I encountered or if I have to submit a new issue. Thanks.

**Comment by thomasjo** [comment]
@swang The fix has not been released yet in a stable Atom build. If you need this ASAP, consider building Atom from source.

You should update your Atom install by the way, you are behind by 8 releases.

**Comment by swang** [comment]
Yeah I am looking into building it myself now and trying out this bugfix. The reason I haven't updated is that I haven't shutdown my computer and didn't even know I was behind.
