### ISSUE TITLE
Find/Replace drawer doesn't close

### ISSUE THREAD

**Issue by 50Wliu** [atom/find-and-replace#538]
_From @rceee on September 24, 2015 20:21_

On 1.0.12 (OS X) now after opening the Find/Replace drawer/sub-window, it does not close with the Esc button, nor does right-click and Close Pane work.  

It usually only closes after closing an open tab.

_Copied from original issue: atom/atom#8932_

**Comment by 50Wliu** [comment]
I can't reproduce this on Atom 1.0.18, Windows 10.  Can you please try updating to Atom 1.0.18 and see if that fixes it?  If not, does running Atom in safe mode (`atom --safe`) help?

**Comment by rceee** [comment]
Hey, thanks.  I updated to 1.0.18.  At first, I experienced the same problem.  Then I updated my packages.  Still the same problem.  Then I rebuilt two extensions that were failing to rebuild under 1.0.12, and those succeeded; I restarted a third time, and now it works.  I think perhaps that was the problem.  

Much appreciated.

**Comment by 50Wliu** [comment]
Ok, glad to hear that it's working now :smile:.  If it happens again be sure to comment here!

**Comment by ccqgithub** [comment]
i have the same problem, it is like that: i use 'find and replace' in settings panel……

**Comment by rceee** [comment]
@ccqgithub I had a couple of packages whose dependencies were missing/broken (a Linter, if I recall).  Removing those fixed it for me, but have no idea if that was the cause.  I also upgraded to 1.0.18 at the same time (shrug).

**Comment by ccqgithub** [comment]
@rceee tks for your answer，the reason is some package breaking，then i rebuild them，it is ok ！

**Comment by rceee** [comment]
@ccqgithub Awesome, glad to be of help!
