### ISSUE TITLE
Find-and-replace isn't closed correctly

### ISSUE THREAD

**Issue by rm-code** [atom/find-and-replace#544]
Since a few updates ago I can't close find-and-replace by pressing "escape" anymore.

I just noticed that it seems to correctly "detect" the key press, but doesn't react immediately. Closing the file will work and as you can see in the following gif, brining up the save dialogue will update it too:
![foo](https://cloud.githubusercontent.com/assets/11627131/10261963/f8938760-69b3-11e5-93e8-9ac14e926c62.gif)

**Comment by benogle** [comment]
Can you open the keybinding resolver with `cmd-.` and type `escape`?

**Comment by rm-code** [comment]
![screenshot 2015-10-06 00 04 44](https://cloud.githubusercontent.com/assets/11627131/10295001/e7da4ee8-6bbd-11e5-8d42-c10b905fc90e.png)

@benogle You mean like this?

I just noted the git-diff-details package is still active. That's why I have the "Incompatible Packages" Icon in the lower right. I just deactivated the package (the icon still is visible though) and now the escape button works as expected.

**Comment by benogle** [comment]
Yep, closing as it was a package conflict. You can open an issue on the package's repo.
