### ISSUE TITLE
Atom blindly replaces contents of find-view with selection text.

### ISSUE THREAD

**Issue by swang** [atom/find-and-replace#550]
#### Problem: Atom blindly replaces the contents of the find input field

I have a habit of reflexively hitting cmd-f whenever I am doing searches. When I do this in Sublime it causes no problems when I bounce from file to file. I do this to make sure that when I hit enter I am doing a search and not inserting a hard return into the file. 

However atom handles this different by replacing the contents of the find input field.
#### How to reproduce

I am in File A, looking for the word `coffee`. Atom highlights the word `coffee` in File A (and other files).
Then I click on File B's tab, looking for the word `tea`.
I go back to File A's tab. I hit `cmd-f` and the word `tea` has been replaced by the word `coffee`

![out](https://cloud.githubusercontent.com/assets/49867/10389429/47d88e76-6e26-11e5-9084-23fbd957b816.gif)
#### What should happen

Nothing. `tea` should remain in the Find text field and not be replaced by `coffee`
#### Here is how the bug bit me pretty hard.

I was refactoring some code and wanted to change `var i,` to `var` in one file. I realized though that I needed to change this in all files. So I tab to another file to verify something before I went ahead with running the mass replace. 

After looking at this file and confirming that I wanted to do the mass replace, I hit cmd-F (that is, cmd-shift-f) to start a mass replace. I searched, clicked on "Replace All" and blindly hit enter to confirm.

What I didn't know was that I had highlighted `let` in that second file, so the mass replace actually replaced `let` with `var` and _saved_ all the files. This cost me a ton of time to undo as I also didn't realize atom automatically saved the files.

I couldn't undo via git because I was in the middle of changes so I pretty much had to go and manually correct each file. I was also too scared to use find/replace again to fix this problem as I wasn't sure exactly what had happened.

Now you can call me dumb for not verifying that the changes I wanted to make were the changes I actually wanted to do. But this seemed like unexpected behavior to change the contents merely by reactivating the find view (cmd-f/cmd-F). Also it was really difficult to figure out why "Replace All" wasn't activated, so I was focused solely on that until I figured out I needed to click "Find" first and by then "Replace All" lit up so I just clicked that with my mouse and hit enter when the dialog box came up.
#### Two possible solutions
- Copy the same thing Sublime does, which is to only replace the contents of the Find input text field when someone does (ctrl-cmd-g), which multi-selects all instances of a word you've highlighted. 
- Do not replace the contents of find input text with the current file's selected text if the find window is already activated.

I have looked at the code and it seems like maybe an easy fix. I am willing to supply a PR but wanted to know method would be accepted. Personally I would prefer the first solution as that is what Sublime does.

**Comment by swang** [comment]
Sooo any movement on this? Would a PR to change/fix this get merged?

**Comment by benogle** [comment]
Maybe it should only be replaced when the find field is empty? I have a feeling people are relying on the current behavior, though.

**Comment by swang** [comment]
I'm curious why the behavior works like this in atom? Thinking about this more now I don't think atom should behave this way at all because I cannot find an editor that does something similar.

I mean why is selecting a word in the text and hitting ctrl-f amount to the user requesting to search for that word? Wouldn't the user just hit ctrl-f then search for the term they're looking for?

**Comment by ssorallen** [comment]
The current implementation is buggy if you're not used to it and instead do a copy, focus-find, paste quickly. I opened #758 for that.

Sublime Text does not enable this setting by default but does let you enable it with the `find_selected_text` setting:

> If `true`, the selected text will be copied into the find panel when it’s shown.
>
> http://docs.sublimetext.info/en/latest/reference/settings.html
