### ISSUE TITLE
Search doesn’t work in this use-case

### ISSUE THREAD

**Issue by kirkstrobeck** [atom/find-and-replace#554]
http://cl.ly/dWq1

**Comment by kirkstrobeck** [comment]
Literally copy, paste, find across project, no result.

**Comment by benogle** [comment]
You have some crazy stuff in the paths field. Take out all content in the third text field. It'll probably work.

**Comment by kirkstrobeck** [comment]
@benogle it looks like that did fix it, but it shouldn’t.

Why would that change the search feature? That is the string that is on deck to replace the search. This is how it worked in Sublime.

**Comment by kirkstrobeck** [comment]
Ohhh ... I see -- You guys swapped position from Sublime. The bottom is the *where* not the *replace* -- ugh :\

**Comment by kirkstrobeck** [comment]
Might consider labels

![](http://cl.ly/dWEN/Screen%20Shot%202015-10-13%20at%202.05.18%20PM.png)

**Comment by benogle** [comment]
Sorry for the confusion.
