### ISSUE TITLE
Find in project searches the last searched project, not the "currently opened" project

### ISSUE THREAD

**Issue by Tyriar** [atom/find-and-replace#559]
**Repro**

1. Add 2 project folders, `foo` and `bar`
2. Create a `test-file` file in `foo` containing the string `test`
3. Right click on `bar` project and select "Search in Directory"
4. Perform a search
5. Open `test-file` and hit Ctrl+Shift+F to open the search for `test`

**Expected**

Find the instance of `test` in `test-file` since it's the project currently opened

**Actual**

`bar` is searched instead of `foo`

---

Setup projects:

```bash
mkdir foo
mkdir bar
echo "test" > foo/test-file
```

**Comment by lee-dohm** [comment]
<kbd>Ctrl+Shift+F</kbd> reopens the Project Find panel. When you did "Search in Directory" you added `bar` to the File/Directory pattern field. That setting is still there when the Project Find panel is reopened:

<img width="744" alt="napkin 10-19-15 9 21 21 pm" src="https://cloud.githubusercontent.com/assets/1038121/10597795/5ac0a648-76a7-11e5-9138-ac5ce24bf024.png">

Simply delete the `bar` from the File/Directory pattern field and things will work as expected.

**Comment by Tyriar** [comment]
I guess it's just something I need to get used to, thanks Lee.
