### ISSUE TITLE
Introduce "Find All" button

### ISSUE THREAD

**Issue by mlalkaka** [atom/find-and-replace#568]
(This is really a feature request, not technically a defect.)
As a new user to Atom, I recently spent a really long time trying to figure out how to perform the "Find and Replace: Find All" action in Atom. I found the "Find and Replace: Select All" action, but it didn't work for things I typed into the Find and Replace pane, and I just didn't realize there was a different action called "Find and Replace: Find All". 

It would have really been nice to have a "Find All" button in the Find and Replace pane, similar to Sublime Text.

**Comment by simurai** [comment]
This got recently added part of https://github.com/atom/find-and-replace/pull/509. Although it just says "Find". You can already try it in [Atom Beta](https://atom.io/beta), but will eventually also be in Atom stable.

To do a "Find All" without pressing a button and use the keyboard instead, you can type your search term and then hit <kbd>enter</kbd>. "Replace All" would be <kbd>cmd</kbd><kbd>enter</kbd>.

**Comment by mlalkaka** [comment]
Thanks for looking into this @simurai . However, I couldn't figure out how #509 solves the problem. I tried the Atom Beta, and I could only see a "Find" button. Typing a search term and hitting <kbd>enter</kbd> just performed a "Find Next" operation, not a "Find All" operation. Am I missing something? Thanks.

**Comment by simurai** [comment]
Just to be sure, are you trying to do a "Find All" for the current file <kbd>cmd</kbd><kbd>F</kbd> or all files in the entire project <kbd>cmd</kbd><kbd>shift</kbd><kbd>F</kbd>?

**Comment by mlalkaka** [comment]
I'm trying to do a "Find All" (find-and-replace:find-all) in the current buffer/file. The shortcut <kbd>alt</kbd>+<kbd>enter</kbd> exists, but there's no button, which made it difficult to discover as a new user.

**Comment by simurai** [comment]
> in the current buffer/file.

Oh.. sorry. Now I understand. I didn't even know about <kbd>alt</kbd>+<kbd>enter</kbd> which proves your point. :smile: I'll reopen this issue again.

**Comment by mlalkaka** [comment]
Thanks!

**Comment by blakebrauer** [comment]
I'm interested in implementing this feature but I am unsure of where the find all button would fit in the UI. Currently the option buttons take up the space where I think the find all button would make sense. Any suggestions on the layout?

**Comment by blakebrauer** [comment]
Maybe like this:
![find_all_options_on_right](https://cloud.githubusercontent.com/assets/8633174/16530760/38aeac60-3f8f-11e6-9bac-1a96702b9a9c.png)

or this:
![find_all_options_on_left](https://cloud.githubusercontent.com/assets/8633174/16531028/3ef22eac-3f90-11e6-9f81-57230a1585e4.png)

or this:
![find_all_options_on_bottom](https://cloud.githubusercontent.com/assets/8633174/16530377/749648de-3f8d-11e6-9756-91779a3ffffb.png)

**Comment by simurai** [comment]
I kinda like the first version:

1. Type search query.
2. Click find button.
3. In case the results are not what you want/expected, tweak the options.

**Comment by bmperrea** [comment]
This appears to be merged and could probably be closed. 

However, for future reference it would be useful to document the usecases for this feature (I've personally never used it). I guess one could copy a list of results returned by a regex and move them to a document of their own...

**Comment by Ben3eeE** [comment]
Thanks @bmperrea :bowing_man:
