### ISSUE TITLE
I can not search the "^", "$", "(?=pattern)" by [Find in Buffer].

### ISSUE THREAD

**Issue by think49** [atom/find-and-replace#575]
I can not search the **"^", "$", "(?=pattern)"** by [Find in Buffer].
If you do not consume one or more characters in a search word, it does not seem to HIT to search .
Does this behavior will a bug ?

**Comment by nmat** [comment]
https://github.com/atom/find-and-replace/issues/497

seems to be a duplicate of that issue.

**Comment by think49** [comment]
Thanks!
I'll try to check the issue.

**Comment by 50Wliu** [comment]
Closing this issue in favor of #497; thanks @nmat!
