### ISSUE TITLE
Don't show "Find and Replace" UI when using Cmd+E

### ISSUE THREAD

**Issue by frantic** [atom/find-and-replace#584]
When using Cmd+E/Cmd+G in Sublime Text, it doesn't show the "Find and Replace" UI, which saves a lot of vertical space.

Seems like Cmd+F already populates selected token into search field, so we could simply not do that for Cmd+E. What do you think?

**Comment by 75lb** [comment]
agree.. cmd+E and cmd+F currently seem identical, so it wouldn't hurt to give us the TextMate/Sublime behaviour we're used to for cmd+E and keep cmd+F the way it is..

**Comment by 50Wliu** [comment]
Duplicate of #332, please subscribe there for updates.
