### ISSUE TITLE
Option to display result on bottom pane

### ISSUE THREAD

**Issue by mkotechno** [atom/find-and-replace#585]
Expand the current option "Open project find results in right pane" to support opening it also in bottom pane, so:

Open project find results in additional pane = [no OR right OR bottom]

**Comment by benogle** [comment]
This definitely could be an enum. Would need to map the current value to the enum value in the solution.

**Comment by bencolon** [comment]
I'm on it. PR is coming ;)

**Comment by walles** [comment]
Here's a (stale it seems) PR for adding split up / down support to core: https://github.com/atom/atom/pull/7280

AFAIU getting that in is required before it can be done in find-and-replace.

**Comment by lee-dohm** [comment]
Atom already has an API to [open panes in any direction programmatically](https://atom.io/docs/api/latest/Pane#instance-splitDown). And [`atom.workspace.open`](https://atom.io/docs/api/latest/Workspace#instance-open) also has support for splitting panes in any direction.

**Comment by chaos7theory** [comment]
@lee-dohm You should close this issue then if that's the case. I'm not sure on the process of non-members requesting stale / resolved issues to be marked as such!
