### ISSUE TITLE
Recent change broke the matcher

### ISSUE THREAD

**Issue by yamsellem** [atom/find-and-replace#586]
Atom 1.1.0.
Find and Replace 0.181.0.

To reproduce the problem; select a variable named `color`, cmd+d two times.
This will select the string `"color"` and an array named `colors`.

This is not what it's expected from autocomplete.
And this is not how it was working not so long ago (it was just selecting variables of the same name).
Is this the desired behavior?

![text matching](https://cloud.githubusercontent.com/assets/606754/10864247/5f5e3b12-7fe8-11e5-8834-237ade3d7c1a.png)

Does is has something to do with [ternjs](https://github.com/tststs/atom-ternjs)?

**Comment by benogle** [comment]
This was changed in https://github.com/atom/find-and-replace/pull/482 and there is some discussion on https://github.com/atom/find-and-replace/issues/521. You can turn the find and replace whole word option on to enable whole word matches.
