### ISSUE TITLE
Cant search words two times on a row

### ISSUE THREAD

**Issue by No6things** [atom/find-and-replace#589]
The most of the times i cant search two times in a row without have to previously do the next steps(on this order):
delete the word i already found
press escape
move to another line

**Comment by benogle** [comment]
can you paste a gif of the behavior?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/find-and-replace/issues/589#issuecomment-154225210. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
