### ISSUE TITLE
Find and Replace starts with the second result of the search, instead of the first

### ISSUE THREAD

**Issue by nikolaydyankov** [atom/find-and-replace#591]
Example:

> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s

1. Double-click the first word "Lorem" to select it.
2. CMD+F
3. Enter some other text in the "Replace" field
4. Press enter

Result - replaces the SECOND occurrence of the word "Lorem", instead of the one that you selected in step 1.
Expected result - must replace the first word that you originally selected in step 1, and then proceed to highlight the second one.

I don't know if this is intended behaviour, but it felt unnatural to me having to constantly go back to the first result of the search and manually replace it.

Cheers

**Comment by benogle** [comment]
Repro'd on master. It is pretty weird.
