### ISSUE TITLE
I'm feeling lucky search + hotkey

### ISSUE THREAD

**Issue by eyalw** [atom/find-and-replace#601]
This is a heuristic search for "go to definition" (of variable/function/class), that does not use a complex grammar / code tree analysis" but is based on simple heuristic text search.

**How will it work**
. e.g.  "<cursor here>Student" 
- first retrieve whole word the cursor is on - in this case "Student"
- then search for  "Student.(.).{" or "class.*Student" or "var.*Student" in *.js file, or ".Student" in .(s)css and open the first result found. in most cases it will work perfectly!!

What do you think? Do you think I should write this plugin myself? you think its any good?
because there isn't seems to be a good working & stable solution for Jump to definition anywhere.

**Comment by izuzak** [comment]
Thanks for sharing your idea, @eyalw. 

That's a neat suggestion, but I'm not sure if it's the best fit for this packages -- while it is based on searching, it's targeted at something specific (finding symbol definitions). That makes me think this would be a good idea for a package. I'm not sure if such a package exists already, so I'd recommend taking a look at the list of available packages at https://atom.io/packages.
