### ISSUE TITLE
Can atom support more complex regex involvement from find and replace buffer?  

### ISSUE THREAD

**Issue by RomuloPBenedetti** [atom/find-and-replace#604]
for example search **\w    \w**
and replace by **\1    \2** or **$1    $2**

Always I try it replace with literals, would be nice .

**Comment by lee-dohm** [comment]
If I change the search expression to `(\w) (\w)` and use the replace expression of `$1 $2` (with regular expression support turned on, then it behaves as expected. In order for `$*` to work, one must have captures in the search expression (denoted by parens):

<img width="266" alt="screen shot 2015-11-24 at 7 12 36 pm" src="https://cloud.githubusercontent.com/assets/1038121/11387459/89ce6d18-92df-11e5-891b-28984f71fe68.png">

Please let us know if I'm misunderstanding the description of the problem.

**Comment by RomuloPBenedetti** [comment]
Thanks! Yes this is the case. Can you point me where it is specified. Because I missed it doing a search.

**Comment by 50Wliu** [comment]
Well, in regex `$1` means "the first match", and a match is specified by using parentheses.  In your original example there were no matches, so `$1` didn't get mapped to anything.

**Comment by RomuloPBenedetti** [comment]
Ah thanks, I really took the $* expression wrong, and sorry by placing a regex misunderstand problem here anyway.

**Comment by lee-dohm** [comment]
You can refer to this page for some basic information on Regular Expressions:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

Notice here:

<img width="672" alt="screen shot 2015-11-25 at 5 39 14 pm" src="https://cloud.githubusercontent.com/assets/1038121/11413225/857782ba-939b-11e5-9365-28c815199079.png">

**Comment by RomuloPBenedetti** [comment]
Really thanks Lee, next time I will this link to be sure that at first Im using regex correctly. As this was resolved I will close it, thanks again!

**Comment by lee-dohm** [comment]
Glad to hear that it helped! :grinning:
