### ISSUE TITLE
A way to search for files (or combine content with file filters)

### ISSUE THREAD

**Issue by keul** [atom/find-and-replace#610]
A great enhancement will be a find/replace similar to the one implemented by Eclipse.

What I mean: all of the current filters plus a "files" filter (let's call it "Find files").
This way a user will be able to search for a file (with globbing) and not for a content: this is done by leaving empty the "Find in project" field but filling the "Find files" ones.

The finally you can combine both: search for a file contents, but only inside a subset of files.

**Comment by benogle** [comment]
You can search for the file names with quick open `cmd-t`, and you can search content in specific paths with the paths input in project find:

![pathsbox](https://cloud.githubusercontent.com/assets/69169/11570853/46c4cc6c-99ae-11e5-99b1-7fda7d0a40ac.png)

Do these not do what you want?

**Comment by keul** [comment]
Absolutely! I was not aware of this feature.
Thanks!
