### ISSUE TITLE
Odd behavior when replacing with backslashes

### ISSUE THREAD

**Issue by Ingramz** [atom/find-and-replace#615]
When doing a search on string `a b a b a b a`, searching for `b` and then replacing all with regular expression `\\\\\\\\` (four escaped backslashes), we get `a \\\\ a \\ a \ a` - first occurrence gets the desired four backslashes, the next one only two, and the last one a single one.

If there were more `b`-s, these would get also a single backslash.

The last build I have, is with find-and-replace version 0.191.0

**Comment by Ingramz** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1017132/11672168/d64c1c98-9e16-11e5-924f-f84a1ce37147.gif)

**Comment by 50Wliu** [comment]
Fixed by #740.
