### ISSUE TITLE
search is slow

### ISSUE THREAD

**Issue by romanianborg** [atom/find-and-replace#620]
If you start typing a search keyword on a large file, the editor freezes and after a while the first letter of search term is marked on editor. Maybe a limit of number characters, or the search to fire on user action not automatically

**Comment by lee-dohm** [comment]
In the latest versions of the package it does wait for three characters to be typed before it starts searching automatically. And it waits for you to stop typing. There are also performance improvements in the latest versions.

Please include more information. If you have specific expectations for speed on documents of a certain size, please mention them. Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by romanianborg** [comment]
I had 1.0.0 and I manually updated to 1.3.2 and the issue is solved.

Thanks.

**Comment by 50Wliu** [comment]
> I had 1.0.0 and I manually updated to 1.3.2 and the issue is solved.

Great to know!, thanks for the update!

Out of curiosity, what OS are you using?  Just want to make sure that the auto-updater isn't broken :P.

**Comment by romanianborg** [comment]
I use Ubuntu 15.10, all plugins seems to autoupdate fine.

**Comment by 50Wliu** [comment]
Ok.  Auto-updater isn't implemented for Linux yet, but hopefully it'll arrive soon.
