### ISSUE TITLE
Nothing replaced when regex contains ^ or $

### ISSUE THREAD

**Issue by nasht00** [atom/find-and-replace#622]
- I right-click on a folder and chose "Search in directory"
- I wrote my search phrase `^###` (regex)
- I wrote my replace phrase `RR2`
- I clicked find
- `129 results found in 29 files for ^###`
- I clicked replace all
- `This will replace '^### ' with 'RR2' 129 times in 29 files`
- I clicked OK
- Searching ...
- `Nothing replaced`

Indeed, none of my files were modified.

What could lead to such a behavior?

I just checked without the regex option, and it replaces the text correctly (but I need regex here).

**Comment by spudly** [comment]
Same problem here. I can search/replace on individual files just fine but on an entire directory of files, it doesn't replace anything.

**Comment by caseyWebb** [comment]
+1

**Comment by clayzermk1** [comment]
I've found that doing a directory search/replace with case sensitive and whole word on causes the replacer to not work in this way. Turning whole word off seems to make it work correctly (obviously, it's not the same search).

Not working (whole word enabled):
![screen shot 2016-01-20 at 9 50 54 am](https://cloud.githubusercontent.com/assets/1075015/12457770/5d4838b6-bf5b-11e5-9654-06c6d1a8b731.png)

Working (whole word disabled):
![screen shot 2016-01-20 at 9 50 23 am](https://cloud.githubusercontent.com/assets/1075015/12457775/620b8736-bf5b-11e5-8299-807a5e2c572f.png)

**Comment by jimniels** [comment]
I'm seeing an issue that is very much the same.

I do my search (SHIFT + CMD + F):

![screen shot 2016-02-08 at 12 15 47 pm](https://cloud.githubusercontent.com/assets/1316441/12896328/9a0c197c-ce5e-11e5-8b7a-afd840e2da24.png)

Then I click "Replace all" and get a confirmation screen saying 'do you want to ...'

![screen shot 2016-02-08 at 12 15 57 pm](https://cloud.githubusercontent.com/assets/1316441/12896342/a8d7156a-ce5e-11e5-924f-b5e30f3dac68.png)

I click "ok" and then I hear an 'error' beep on the computer and the search screen shows search results where nothing has changed (at the bottom it says "Nothing replaced")

![screen shot 2016-02-08 at 12 16 04 pm](https://cloud.githubusercontent.com/assets/1316441/12896375/d47317f0-ce5e-11e5-9b08-5e0df9661b83.png)

**Comment by dikmax** [comment]
Still reproducible in Atom 1.5.3

**Comment by MattHall** [comment]
@jimniels I just had this same issue - tried without the ^, and it seems to have worked fine.

**Comment by jimniels** [comment]
@MattHall I ended up using sublime text to find/replace what I needed. However, I just tried it again in v1.5.3 and it didn't work, even when I removed the `^`. Same error as I noted before "Nothing replaced."

**Comment by Ryex** [comment]
this is still reproducible. Useing the beginning of line ^ regexp causes replace all to replace nothing. as soon as it is removed replaces work

search: ^(use\s.+;)
replace: // $1
scope: file pattern

fails until the ^ is remoced

**Comment by maaarghk** [comment]
Reproduced here when trying to tidy up some legacy code -
![screen shot 2016-03-28 at 15 50 57](https://cloud.githubusercontent.com/assets/3168648/14080440/0a034aa6-f4fd-11e5-88be-507258fa1004.png)

**Comment by javiercbk** [comment]
Same error here trying to replace with regexp and group capture.
```
log\.Info\("(.*)\)$
```
with
```
log.Info(fmt.Sprintf("$1))
```
I'm using the latest version (1.6.0)
![atom-replace-error](https://cloud.githubusercontent.com/assets/1448426/14087140/e8e8c632-f4fe-11e5-886e-1794f80e0e3e.gif)

**Comment by subfuzion** [comment]
Strange, this actually worked at one point because I would use `;$` to remove all my trailing semi-colons as I converted Node.js projects to not use them. I can confirm it's not working now, however, with v1.8.0.

**Comment by memob** [comment]
+1

**Comment by woodyrew** [comment]
I experienced this in `v1.10.2` with search `^something`

**Comment by glennpratt** [comment]
I have the same behavior with `$`, not just `^`. It appears others do as well.

Could someone fix the title?

**Comment by mcdado** [comment]
I experienced the same problem, on some files the regexp would work, on (most) other would not (for reference, one or two did, about thirty others did not).
`^\{shop_name\} \[\{shop_url\}\]$` => `{shop_url}`

Removing both the `^` and the `$` solves the problem. In my case I switched to Sublime to accomplish what I was trying to do.

**Comment by PaulMorel** [comment]
I have experience this with v1.14.0 on OSX. When I run the find and replace, I get the OSX alert sound.

Search: `^#{4} (S(?:e|é)nate? ?:?)$`
Replace: `### $1`

Like others, removing both the `^` and the `$` solves the problem, but is not ideal.

**Comment by ffxsam** [comment]
Wow, this has been a bug for a very very long time. 😕

**Comment by kevin1kevin1k** [comment]
Same here.

Regex: [ \t]$

Also nothing replaced.

**Comment by macrozone** [comment]
super annoying. Atom highlights the search results properly, but when i hit "replace all", just a beep and nothing happens

**Comment by micahscopes** [comment]
This is happening for me right now.

**Comment by aherman** [comment]
This is happening for me as well. Atom correctly finds and identifies the regex criteria, but when I hit "Replace All" it returns with "Nothing Replaced"

**Comment by youbastard** [comment]
Happening to me as well when using ^ or $

Atom v1.16.0 on Mac v10.12.4

**Comment by woodyrew** [comment]
If you have this problem, could you :+1: the issue: https://github.com/atom/find-and-replace/issues/622#issue-122467682

**Comment by aymericfraise** [comment]
It's happening to me in v1.18.0 using the following regex : `"schema": {(.|\n)*?(?=\n[ \t]+"type")`
This works though : "schema": {(.|\n)*?(\n[ \t]+"type")
So the issue seems to be the lookahead in this case

**Comment by Rockster160** [comment]
Super annoying issue. I found a (slight) workaround. If the file is open in one of your tabs, the replace works successfully. So my work around is to individually open each file, (Usually ~30 at a time otherwise my computer starts to struggle) then global find and replace. Close all files, rinse and repeat. Still though. Please fix. 😞

**Comment by 50Wliu** [comment]
This seems to be because of a missing `m` regex flag when replacing files that aren't open in Atom.  Will create a PR and test things out.

**Comment by 50Wliu** [comment]
Sorry for the poor experience everyone.  Project-wide find-and-replace with the `^` and `$` anchors should start working properly when Atom 1.21.0 is released.

**Comment by sposhe** [comment]
I'm on 1.25.0 for Mac and this is still an issue.

**Comment by katy-sadowski** [comment]
I'm having the same issue - I'm on 1.37.0.

My regex string is `[^n^0-9]\K,` - it has many hits within the document and when I click replace all, it flashes briefly to "No Results", as if it has worked, but then nothing actually happens. 

Any idea if there's still a bug?

**Comment by 50Wliu** [comment]
@katy-sadowski can you please open a new issue for that? Yours doesn't seem related to this one since the carets are appearing within character classes.
