### ISSUE TITLE
Multiple results in one line are displayed as multiple lines in the result list

### ISSUE THREAD

**Issue by dbkaplun** [atom/find-and-replace#623]

**Comment by mnquintana** [comment]
That's so you can jump to the exact column location of the particular occurrence of the search result – if they were all on the same line, you'd only be able to jump to one occurrence.

What were you expecting instead?

**Comment by dbkaplun** [comment]
I was expecting more a Sublime-like interface where multiple matches in one line are highlighted but only rendered as one line in the results pane. I guess I see the reasoning behind the current UI but I would prefer a more compact, easily readable list of results.

**Comment by mnquintana** [comment]
What do you think about instead updating the UI so it renders only one line in the results view, but each occurrence is tokenized so you can click on each one separately to go to that column location?

**Comment by lee-dohm** [comment]
Another use case to consider are files that have really long lines, for example minified JS.

**Comment by swrobel** [comment]
Here's a screenshot showing the behavior. I'd expect to see just one instance of line 39 in the results, with both instances of `.organization` highlighted on that same line.
<img width="918" alt="screenshot 2016-03-09 16 15 55" src="https://cloud.githubusercontent.com/assets/157270/13655165/510adfd0-e612-11e5-8d88-b747268b65f1.png">

**Comment by sbaker7** [comment]
it could be enabled/disabled from the settings, or enabled on a language basis. I think it'd be great to have the option. Obviously adds complexity though.

**Comment by lee-dohm** [comment]
I opened a new Issue to fully spell out the problem and hopefully get some discussion going around pros and cons of various options. See #681.

Thanks for bringing this up everyone!
