### ISSUE TITLE
Default Ignore File/Directory Pattern

### ISSUE THREAD

**Issue by AnthonyBobsin** [atom/find-and-replace#624]
Hello,

It would be very convenient for there to be an option in settings that allows for a default file/directory pattern that gets applied to all searches. Additionally, it would be ideal for there to be a checkbox to avoid VCS ignored files for all searches. This setting would be very similar to fuzzy-finder's "Ignored Names" config setting. I apologize if there is already a way to configure find-and-replace this way, I've had no luck in finding how to do so.

**Comment by rm-code** [comment]
I just wanted to suggest the same. We already have the ```Ignored Names``` in the settings which are used by tree-view and fuzzy finder. I think find-and-replace could use them as well to determine which folders to exclude while searching.

**Comment by lee-dohm** [comment]
> Additionally, it would be ideal for there to be a checkbox to avoid VCS ignored files for all searches.

This already exists in the main settings view:

<img width="714" alt="screen shot 2016-01-04 at 8 34 58 am" src="https://cloud.githubusercontent.com/assets/1038121/12094582/19104638-b2be-11e5-9ea4-3512cad61613.png">

> We already have the Ignored Names in the general Atom settings which are used by tree-view and fuzzy finder. I think find-and-replace could use them as well

The project find function uses the same `atom.workspace.scan` function to search through the project's directories and files. It applies both the "Exclude VCS Ignored Files" and "Ignored Names" settings:

https://github.com/atom/atom/blob/b11d0c25851d9d784abccd7e9d0c96c2fa25eee3/src/workspace.coffee#L925-L931

If you have repro steps that show this isn't working as expected, please open a new Issue.

**Comment by rm-code** [comment]
> If you have repro steps that show this isn't working as expected, please open a new Issue.

https://github.com/atom/find-and-replace/issues/635
