### ISSUE TITLE
Opening panel puts selected text in wrong box

### ISSUE THREAD

**Issue by svivian** [atom/find-and-replace#626]
To reproduce: select some text in your document, then open the find/replace panel (I used Cmd+Alt+F on Mac, I assume it's Ctrl+H on Windows).

Expected: the highlighted text to be placed in the first ('Find') input field.

Actual: it's placed in the second box ('Replace').

Using latest version (1.3.2) on a Macbook.

**Comment by rm-code** [comment]
As far as I can tell this is intended. ```cmd-f``` will do what you want.

You can change the keybindings to suit your needs:
```
'.platform-darwin':
  'alt-cmd-f': 'find-and-replace:show-replace'
'.platform-darwin':
  'cmd-f': 'find-and-replace:show'
```

Best wishes
Robert

**Comment by svivian** [comment]
OK I didn't realise that the "Find" dialog also included the Replace part. So yes, `Cmd+F` does what I want. Thanks.
