### ISSUE TITLE
Searching in directory includes ignored VCS paths

### ISSUE THREAD

**Issue by rm-code** [atom/find-and-replace#635]
Searching in a project folder includes the .git repository although it should be ignored based on the preferences (as far as I can tell):
![pref](https://cloud.githubusercontent.com/assets/11627131/12132039/44259d68-b418-11e5-973c-b1ada9956e68.png)

**Reproduction Steps:**

1. Right-Click on Project Folder in Tree View
2. Click on Search in Directory
3. Enter a search-term
4. Result: 

![meh](https://cloud.githubusercontent.com/assets/11627131/12132077/a3f62816-b418-11e5-9fe7-1fc6fd756b9e.png)

**Atom version:** 1.4.0-beta3
**OS and version:** OSX 10.11.2

**Installed packages:**

├── Zen@0.16.3
├── base-16-ocean-dark-ui-theme@1.5.5
├── base16-ocean-dark-syntax-theme@0.1.7
├── external-open@0.6.1
├── file-icons@1.6.13
├── language-lua@0.9.4
├── language-moonscript@1.7.1
├── linter@1.11.3
├── linter-javac@1.4.0
├── linter-lua@1.0.1
├── linter-moonscript@0.1.2
├── linter-shellcheck@1.1.0
├── love-atom@2.1.0
├── merge-conflicts@1.3.7
├── pigments@0.19.5
├── project-manager@2.6.5
└── vim-mode@0.64.0

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Atom: Yes (I think)
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by lee-dohm** [comment]
Search in Directory is a feature of tree-view and doesn't work the same way as Find in Project. It is intentional that Search in Directory acts differently, since you can view ignored files in tree-view even when the rest of Atom ignores them.

**Comment by rm-code** [comment]
Argh ... okay then I'll use Find in Project in the future instead. 

Thanks Lee.

**Comment by lee-dohm** [comment]
You're welcome. Sorry it is so confusing :( If you've got suggestions on how it can be improved, let us know!

**Comment by rm-code** [comment]
> You're welcome. Sorry it is so confusing :( If you've got suggestions on how it can be improved, let us know!

In hindsight it makes sense that "Search in Directory" would include all folders in the search :grin: 

It's pretty late here, so maybe I'm just not thinking straight, but ⇧⌘F is the "Find In Project" you were talking about, right? Because that search still shows me .git paths:
![screenshot 2016-01-06 04 19 58](https://cloud.githubusercontent.com/assets/11627131/12134151/c4e2c5ac-b42c-11e5-9f2e-ed1601f4d2f8.png)

**Comment by lee-dohm** [comment]
Yes, <kbd>⇧⌘F</kbd> is the Find in Project I was talking about. And yes, it will show you paths that are in ignored directories if "Exclude VCS Ignored Paths" is unchecked:

<img width="721" alt="screen shot 2016-01-06 at 12 01 52 am" src="https://cloud.githubusercontent.com/assets/1038121/12137831/bc8ffc5e-b408-11e5-8834-f6166b4b0825.png">

**Comment by rm-code** [comment]
Ok. I think it actually is a different issue altogether. 

 ```Exclude VCS Ignored Paths``` is checked in preferences:
![foo](https://cloud.githubusercontent.com/assets/11627131/12132039/44259d68-b418-11e5-973c-b1ada9956e68.png)

** Steps to reproduce **
1. Restart Atom
2. Open project and use ⇧⌘F (Find in Project) to search for a certain word
3. Close Project Find Results
4. Click on project folder and use Search in Directory
5. Close Results tab
6. Use ⇧⌘F (Find in Project)

** Results **
The first time we use ⇧⌘F it ignores the paths as expected, but after using ```Search in Directory``` all the following ⇧⌘F-Searches won't ignore paths anymore.

**Comment by lee-dohm** [comment]
Would you mind opening a new Issue for that? Then we can investigate it.

**Comment by rm-code** [comment]
Done #636
