### ISSUE TITLE
"Close Project Find Panel After Search" option producing strange behaviour

### ISSUE THREAD

**Issue by mamartins** [atom/find-and-replace#638]
Hi guys,

on OSX, and with atom 1.3.2 if I have the "Close Project Find Panel After Search" toggle turned on, for every char I try to insert in the "Replace in project" input make the find panel close. I also cannot use the "Replace All" when the same toggle is on because the button is grayed out.

**Comment by amytruong** [comment]
I was able to reproduce this. Def a bug. 
Thanks @mamartins!

**Comment by mamartins** [comment]
you're welcome :)

**Comment by Ben3eeE** [comment]
https://github.com/atom/find-and-replace/issues/612

**Comment by 50Wliu** [comment]
Closing as a duplicate of #612 - feel free to subscribe there for updates.
