### ISSUE TITLE
Cannot find asterisks in current buffer

### ISSUE THREAD

**Issue by logicmason** [atom/find-and-replace#639]
I have a file open with 118 asterisks, and the cmd-f find returns zero results for `*`.

**Comment by mnquintana** [comment]
Do you have Regex mode enabled?

**Comment by logicmason** [comment]
Not that I know of. `/\*/` also returns zero results.

**Comment by lee-dohm** [comment]
I was unable to reproduce this on Atom v1.5.0-dev-4ee6b3a on Mac OS X 10.11.2. Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by logicmason** [comment]
I'm also on Mac OS X 10.11.2, using atom 1.3.3.

Starting with the --safe flag did resolve the issue though!

**Comment by lee-dohm** [comment]
I was also unable to reproduce this in Atom v1.3.3 on Mac OS X 10.11.2.

![find-asterisk](https://cloud.githubusercontent.com/assets/1038121/12250829/f772f086-b87e-11e5-87b2-d72b0c115ec0.gif)

**Comment by lee-dohm** [comment]
Sorry, I missed the Safe flag thing. It is most likely a package that you have installed that is causing the issue then. You may want to use the [package-cop package](https://atom.io/packages/package-cop) to track down which one is causing the issue.

**Comment by logicmason** [comment]
Thanks! Will do.
