### ISSUE TITLE
Results are not sorted

### ISSUE THREAD

**Issue by kevinsawicki** [atom/find-and-replace#64]
Results for files under `node_modules` are not sorted by their folder, jasmine-focused, then underscore-plus, then grunt.  Would have expected the results from the grunt folder be first.

![screen shot 2013-10-31 at 10 29 18 am](https://f.cloud.github.com/assets/671378/1448110/23e29dba-4252-11e3-8f58-45331a60ec6b.png)
.

**Comment by bronson** [comment]
Yes, the results are ALMOST sorted on my system, which is worse than being completely random.  It really looks like all results in /lib are grouped together, and all results in /spec are grouped together so, even though I know they're not, I'll often miss a result when it ends up in the middle of something else.

I'd take slowness over bizarre sort.  If speed is an issue, shelling out to a native program is an option?
