### ISSUE TITLE
scroll to keybinding results

### ISSUE THREAD

**Issue by mehmetalisavas** [atom/find-and-replace#646]
I know the scroll problem works as well while using `cmd+f` to find words. Its solved with [this PR](https://github.com/atom/find-and-replace/commit/7f3715739d1afc6aaa380a0e931ff77d5c67c707) ..
But while searching functions (symbols) with `cmd+r` , search result appears at the bottom of the screen.(not at the center of the screen)
I'm talking about this keybinding.
```
'.platform-darwin atom-text-editor':
  'cmd-r': 'symbols-view:toggle-file-symbols'
```

Same problem occurs while using go-to-line..
```
'.platform-darwin, .platform-win32, .platform-linux':
  'ctrl-g': 'go-to-line:toggle'
```

**Comment by 50Wliu** [comment]
@mehmetalisavas Can you please open separate issues for these on the [symbols-view](https://github.com/atom/symbols-view) and [go-to-line](https://github.com/atom/go-to-line) repositories?  Thanks!
