### ISSUE TITLE
Search doesn't work when same search term is entered

### ISSUE THREAD

**Issue by bobber205** [atom/find-and-replace#654]
I use the Quick Project switcher all the time.
If I search for say myVariable in Project A then switch to Project B and keep the search term the say, whether that's leaving that field alone or retyping it, nothing is searched.

I think it'd be a handy thing to have it always research when I press search, maybe as a setting?

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/find-and-replace/issues/654#issuecomment-175302666. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
