### ISSUE TITLE
Replace preview does not translates matching groups

### ISSUE THREAD

**Issue by roolo** [atom/find-and-replace#656]
I found out, that when I use regex matching groups in both Find in project and Replace in project, the matching group is not translated in the preview (see picture). Anyway it looks like the actual replacement works fine.

![project_find_results](https://cloud.githubusercontent.com/assets/173141/12732116/4d8d5fb8-c934-11e5-8bbd-bb759c33deaa.png)

**Comment by benogle** [comment]
I think this is a regression. What version are you on?

**Comment by roolo** [comment]
RE https://github.com/atom/find-and-replace/issues/656#issuecomment-178209109:

@benogle: 1.4.1

**Comment by roolo** [comment]
I just got 1.4.2 and it seems to work now
