### ISSUE TITLE
find in files will not find certain valid regex patterns, but works inside the file

### ISSUE THREAD

**Issue by nikmartin** [atom/find-and-replace#658]
given this regex:
```
\s*enum:\s*\[\r*\n*\s*\d
```
A file with this text is a match:
```
   enum:[
          9917001,
          9917003,
```
but will not be returned in a Find in FIles, BUT this regex WILL return this file:
```
\s*enum:\s*\[\r*\n*\s*
```
but only matches up to:
```
   enum:[
         
```
But if I then open the file all the matches that include the \d in the regex will be highlighted

Find in files with \d:
![screenshot from 2016-02-02 13-31-08](https://cloud.githubusercontent.com/assets/1226452/12761627/5145adcc-c9b1-11e5-96d1-e9401662ba59.png)

and a file showing the match:
![screenshot from 2016-02-02 13-32-33](https://cloud.githubusercontent.com/assets/1226452/12761655/6f973fde-c9b1-11e5-942c-8ea848a9aeee.png)

**Atom version:** 1.5.0-beta2-a01dc47
**OS and version:** Arch Linux x86_64

**Installed packages:**

angularjs      
atom-ternjs
language-ejs        
package-cop                     
zentabs
atom-beautify  
auto-copyright  
linter              
rest-client
atom-ctags     
fonts           
linter-js-standard  
standard-formatter
atom-terminal  
git-plus        
minimap             
Sublime-Style-Column-Selection

**Additional information:**

* Problem can be reproduced in safe mode: [Yes]
* Problem started happening recently, didn't happen in an older version of Atom: [Unknown]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Unknown]

**Comment by benogle** [comment]
Thanks for the detailed reproduction steps. This is because project find doesn't handle multi-line regular expressions at this time: https://github.com/atom/scandal/issues/5

**Comment by adamkdean** [comment]
@benogle Is this still the case more than three years on?
