### ISSUE TITLE
Cannot use Project Find and Replace on files in ssfhs-mounted drive

### ISSUE THREAD

**Issue by breschke** [atom/find-and-replace#661]
See also [here](https://github.com/atom/atom/issues/5439):

While I can edit files on an ssfhs-mounted drive, I cannot use Project Find and Replace to modify files unless I give global read, write, and execute permissions on the host Linux machine.

**Comment by lee-dohm** [comment]
Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/find-and-replace/issues/661#issuecomment-180065967. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
