### ISSUE TITLE
"Find in Project" is slow and unstable

### ISSUE THREAD

**Issue by lwchkg** [atom/find-and-replace#665]
As title. See the movie at https://www.youtube.com/watch?v=b2vo1i8MRYY&feature=youtu.be for details.

**Comment by arthurcgusmao** [comment]
Hi, I have this same issue. The problem I'm facing is that whenever I try to run "Find in Project" in a very large project, the whole operating system lags (Ubuntu 16.04), and if I wait too much to kill atom the PC becomes unusable.
