### ISSUE TITLE
Clicking on result doesn't scroll to the result when file wasn't open

### ISSUE THREAD

**Issue by adambuczynski** [atom/find-and-replace#669]
OS X Atom 1.5.3

Steps to reproduce:
- Close any files
- Do a search in project for something
- Click or double click on the the results (not the first one if there are multiple)

Expected:
- File opens in tab and scrolls down the where the clicked result is

Actual:
- File opens but doesn't scroll down

Notes:
- Once the file is already open in a tab, clicking on a result *does* take you straight to the result location in the file.

Demo:

(sorry cursor doesn't show up, but i'm clicking on the line 250 result in both cases)

![ss](https://www.dropbox.com/s/svwo2xj8xpxo0s7/find-in-project-error.gif?dl=1)

**Comment by lee-dohm** [comment]
I was unable to reproduce this using Atom v1.7.0-dev-989b546 on Mac OS X 10.11.3. Here's what I did:

1. Launch Atom in my atom/atom repository
1. Ensure all files are closed
1. Launch Find in Project with <kbd>Shift+Cmd+F</kbd>
1. Type `atom` in the search field
1. Press <kbd>Enter</kbd>
1. Scroll down to `build/tasks/build-task.coffee`
1. Single click on the *second* result for line 188

**Expected and Actual:** The file opens, scrolls line 188 into view and highlights the second occurrence of the word `atom` on that line as the active search result

**Comment by adambuczynski** [comment]
I've just restarted Atom in safe mode, and could not reproduce. Then started normally again, and could not reproduce either anymore.

But I have seen this happen more than once. Normally, I will only raise an issue like this if I am positive that it's a bug and that it's been happening enough times for it to annoy me ;)

Not sure why it happened yesterday and not today, and not sure how to further investigate this...

**Comment by lee-dohm** [comment]
It could be some sort of race condition. If I was sure it wasn't a bug, I would have closed the Issue :grinning: I'm going to see if one of our tame test wizards can poke at this a bit.

**Comment by adambuczynski** [comment]
Cheers thanks :)

**Comment by adambuczynski** [comment]
Have been experiencing this again today, quite consistently. Happens only with files that aren't already open in a tab.

**Comment by lee-dohm** [comment]
I just tried it using Atom v1.5.3 on Mac OS X 10.11.3 and still wasn't able to reproduce it using my steps above. Does it repro more consistently when you single- or double-click?

**Comment by adambuczynski** [comment]
Doesn't seem to matter how I click, happens in both cases. The only thing that matters is whether or not the tab is open already. For what it's worth, I also don't have any other Atom windows open.

**Comment by adambuczynski** [comment]
Seems to be fixed now in 1.10.0-dev-672cf6d
