### ISSUE TITLE
Increase find/replace line character limit independently from preferred line length

### ISSUE THREAD

**Issue by danielbayley** [atom/find-and-replace#670]
It looks like the number of characters that can be typed in the find/replace fields is currently limited to the preferred line length (or is at least coincidentally set to 80), before they cut off from display.

Could this be increased instead to a certain percentage (maybe 80/90%) of the width of the find/replace fields? Perhaps with `padding-right`?

**Comment by lee-dohm** [comment]
I can't reproduce this using Atom v1.5.3 on Mac OS X 10.11.3. Here's what I did:

1. Launch Atom in Safe Mode
1. Open the `README.md`
1. Open the find-and-replace panel by pressing <kbd>Cmd+F</kbd>
1. Type `1234567890` ten times
1. Type more random characters

**Expected and Actual:** At no point do characters stop displaying

**Comment by lee-dohm** [comment]
This may be a duplicate of https://github.com/atom/tree-view/issues/473.

**Comment by danielbayley** [comment]
> This may be a duplicate of atom/tree-view#473.

I think it was, and the fix in that thread works 👍
