### ISSUE TITLE
When `Only Inelection` is checked, first `Replace All` doesn't work correctly in specific situation.

### ISSUE THREAD

**Issue by sftd** [atom/find-and-replace#675]
Atom 1.6.0-beta7: When using `Replace All` when `Only in Selection` is checked it doesn't work correctly when used for the first time. It only replaces FIRST occurrence. When used for the second time it works and replaces ALL occurrences. 

Unfortunately I can't find out what are the exact steps to reproduce (as sometimes it works correctly):

![atom_file-search_bug](https://cloud.githubusercontent.com/assets/3073859/13554775/38850cbe-e3b1-11e5-9792-d5b6327cf7b0.gif)

**Comment by lee-dohm** [comment]
This is the intended behavior. If you notice in your image (thanks for that, by the way) it shows `1 result found for 'apple'` and `1 found` in the find text field when you click Replace All. When you click Replace All, it will only replace whatever it found the last time you clicked Find. If you want to update the search results for the new selection, you need to click Find again.

**Comment by sftd** [comment]
I'm sorry but I will have to bother you with one follow up question.

Is there a way to `Replace All` in selection with "one click"?

From what you said I would expect I would be able to:
`"select" part of code` => `find all the result in "selected" section` => `replace all of them`

The problem is that after performing "search" every selection seems to be unselected.

It's unimportant from practical point of view, but I'm just curious about the logic behind it :).

**Comment by lee-dohm** [comment]
Actually, it appears that you've uncovered a bug. I've filed it as https://github.com/atom/find-and-replace/issues/677.
