### ISSUE TITLE
Selection doesn't update when only in selection is enabled and Find is clicked again

### ISSUE THREAD

**Issue by lee-dohm** [atom/find-and-replace#677]
### Repro Steps
1. Launch Atom
2. Open a new file using <kbd>Cmd+N</kbd>
3. Enter the text:
   
   ```
   apple, banana,
   apple, banana,
   apple, banana
   ```
4. Select the first instance of `apple` with the mouse
5. Open the find-and-replace panel with <kbd>Cmd+F</kbd>
6. Ensure "Only in Selection" is enabled
7. Click the "Find" button
8. Ensure that `1 result found for 'apple'` is shown above the find text box
9. Select all text using the mouse
10. Click the "Find" button

**Expected:** New search is executed with the updated selection

**Actual:** Continues to display `1 result found for 'apple'`

Reproduced using Atom v1.7.0-dev-b08e293 on Mac OS X 10.11.3.

**Comment by halicki** [comment]
Is anyone is working on this issue? It affects my workflow heavily.

**Comment by aprice** [comment]
Find in selection is badly broken, and has been for years, going back to pre-1.0 versions of Atom. #298 was opened for multiple serious issues with find in selection, and it was closed after one small part was fixed, but the feature remains unreliable to the point of being nearly unusable. Various issues are open for find in selection, and there are comments stating that it's "not a high priority for the core team". It's not clear what their priorities are, though.

**Comment by halicki** [comment]
I find "find in selection" one of main features of a text editor. I don't know what other issues can be more important than being able to edit a text file.

**Comment by 50Wliu** [comment]
> It's not clear what their priorities are, though.

Since I'm the one who both opened and closed #298, here's my take on this:
I closed that issue so that more specific ones could be opened in its place, which seems to have happened for the most part.  Some of the Atom team's priorities right now are improving performance and fixing regressions (I can't really comment on exactly what they are, since I'm only a volunteer).

@halicki Issues where Atom crashes on opening large text files (just a random example) are arguably more important than this one.  That being said, PRs are always welcome.

**Comment by kolbma** [comment]
- The selection (searched on) gets only updated when disabling and re-enabling the "only in selection" option.
- or you change the search string

Should also work if you change the selected text in buffer without changing search string or changing search options.

**Comment by philgyford** [comment]
> The selection (searched on) gets only updated when disabling and re-enabling the "only in selection" option.

The selection does get updated then, but gets updated to a single line, rather than the original selection. Infuriating. (v 1.17.2)

**Comment by Josh-West-Bose** [comment]
This is still an issue with 1.23.1

**Comment by chbk** [comment]
Please fix this 🙏

**Comment by 50Wliu** [comment]
@chbk please file a new issue for that.

**Comment by PotatoPope** [comment]
I've had similar issues with find and replace in selection, atom would only replace one of the found instances of a word. This was fixed for me by installing this package: https://atom.io/packages/find-and-replace-fix
