### ISSUE TITLE
Find panel close icon

### ISSUE THREAD

**Issue by depperm** [atom/find-and-replace#683]
There have been previous issues that mention this (#164, #215, #219, #201, #204) and a few related ones about it not closing with ctrl-f. I believe a GUI close button could be added by modifying find-view.coffee
Adding lines about:
line 32: `@span class: 'icon icon-x pull-right', style: 'padding-left:5px', outlet: 'closeFindPanel'`
line 156: `@handleCloseEvents()`
line 192: `handleCloseEvents: ->`
`@closeFindPanel.on 'click', (e) => @panel?.hide()`

**Comment by lee-dohm** [comment]
Thanks very much for the feedback. We've listened to the requests and we're not interested in adding a close button to the find-and-replace panel.
