### ISSUE TITLE
Search bar switches to previous search after pressing ctrl+c and ctrl+f on another word

### ISSUE THREAD

**Issue by bziemons** [atom/find-and-replace#684]
With the current version beta version of atom (1.7.0-beta0), I am getting problems when copying and searching for a word. After copying (ctrl+c) and then searching the very same work (ctrl+f), the search bar shortly shows the word, but then switches it out for the word previously searched.

I am on a Windows 7 PC and have a german keyboard layout.
I can reproduce the issue every time and in safe mode. Also I have disabled all packages to reproduce the issue, just to be sure.

**Reproduction Steps:**

1. Mark a word, click ctrl+f and keep the search bar open
2. Then mark another word and click ctrl+c and then ctrl+f

**Expected behavior:**

I would expect the word, which I just pressed ctrl+f on to appear in the search bar.

**Screenshots and GIFs**

![animation](https://cloud.githubusercontent.com/assets/10897837/13917571/028d5a32-ef62-11e5-9c4a-ed629166420d.gif)

**Atom version:** 1.7.0-beta0
**OS and version:** Windows 7

**Installed packages:**

find-and-replace package:

    Built-in Atom Packages (89)
    ...
    ├── find-and-replace@0.197.4
    ...

other packages:

    > apm list --installed
    Community Packages (7) C:\Users\...\.atom\packages
    ├── atom-beautify@0.28.26
    ├── autocomplete-python@1.7.2
    ├── git-plus@5.13.0
    ├── hyperclick@0.0.35
    ├── keyboard-localization@1.4.15
    ├── MagicPython@0.5.8
    └── minimap@4.21.0
    
    └── (empty)

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by Ben3eeE** [comment]
Closing in favor of https://github.com/atom/find-and-replace/issues/758 which has more discussion.
