### ISSUE TITLE
Use Oniguruma instead of the JS regex engine

### ISSUE THREAD

**Issue by alexchandel** [atom/find-and-replace#698]
The JavaScript regex syntax is crippled. It lacks simple things like lookbehinds (#571), atomic groups (#667), and possessive groups (#667), and well as more complex features like document anchors ('\A', '\Z', '\z'). It should not be used.

Atom grammars use Oniguruma, a better regex engine with support for modern syntax. Find and replace needs to use this too.

**Comment by Alhadis** [comment]
100% agreed. I'm rather surprised it's not used already, to be quite honest.

**Comment by spencerthayer** [comment]
PRETTY PLEASE! It's painful to use Javascript regex syntax.

**Comment by alexchandel** [comment]
@JesseLeite this appears to be a popular request.

**Comment by lee-dohm** [comment]
Duplicate of #571.
