### ISSUE TITLE
Substitute same number of repeated characters with others using Regex

### ISSUE THREAD

**Issue by thorade** [atom/find-and-replace#727]
I have a rst file, where I want to replace some characters used for making a section with a different character. So, I want to find a line like `========` and replace it with a line `--------`.
For finding, I successfully used `(^==*$)`, even though I do not full yunderstand it (it expected that I have to use only one `=`). To find that expression, I used https://regex101.com/
For replacing, I need something like `length($1)` but I was not able to find a working solution. Is some operator like `length()` allowed/supported?

Also see:
https://discuss.atom.io/t/regex-find-and-replace-same-number-of-repeated-characters/29255
http://stackoverflow.com/q/21846765/874701

**Comment by lee-dohm** [comment]
There isn't a `length` operator in regular expression substitutions, no. For things like that, you would need to use code like was described in the Discuss topic you linked.
