### ISSUE TITLE
Keybinding ctrl-f to toggle rather than show

### ISSUE THREAD

**Issue by JimmySevere** [atom/find-and-replace#770]
Hi,

In the find dropdown menu it says that ctrl-f should toggle "Find in Buffer", but in my experience this only shows and does not hide.

Since looking through your source code, I have found that your key bindings are only set to `show`. 

Through a little trial and error, I found I can attain the toggle behaviour of ctrl-f by using:

```
'.platform-darwin':
  'cmd-F': 'project-find:toggle'
  'cmd-f': 'find-and-replace:toggle'

'.platform-win32, .platform-linux':
  'ctrl-F': 'project-find:toggle'
  'ctrl-f': 'find-and-replace:toggle'

```

in my keybindings file (~/.atom/keymap.cson - on linux).

Cheers.

**Comment by 50Wliu** [comment]
`project-find:toggle` does not have a keybinding by default.  At least on Windows, Ctrl+F is bound to `find-and-replace:show` and listed as `Find in Buffer`.

It is intentional for the default ctrl/cmd+f keybinding to only toggle focus to the find-and-replace panel.  https://github.com/atom/find-and-replace/issues/164#issuecomment-44226984

**Comment by JimmySevere** [comment]
Hi @50Wliu 

It seems you have missed the actual issue here. It is not on whether the key bindings _**should**_ be set to toggle or not, it is that the Find dropdown menu explicitly states that it _**is**_ set to toggle. I proposed one solution (my preferred one as esc key - or, at least, my esc key - on debian jessie doesn't seem to work in the same way as on windows - i.e., works with some programs and not with others, and atom being one it doesn't work with). Another solution would be to remove keybinding advisements for the toggle functions in the dropdown menu, or use "Ctrl+F/Esc" instead.

For this reason, **I feel this issue should be reopened**.

Cheers.

P.S. As an aside, with respect to the linked comment, if that's the only reason to have it not as toggle, I think it's a pretty poor one. Not to say the other side of the argument is compelling, but anyone who thinks double tap over single tap in uncommon cases (that of reattaining focus) is damaging to workflow is far too set in their ways. What's more, as is mentioned in the comment, esc is close for so many things, so to be sure esc will work properly, the find panel needs to be in focus. Ergo, Ctrl+f and then Esc - even slower workflow.

**Comment by 50Wliu** [comment]
Here is my Find menu dropdown in safe mode (`atom --safe`):
![find-menu-dropdown](https://cloud.githubusercontent.com/assets/2766036/18225663/d61be428-71c5-11e6-8f3e-718d83afe663.png)

As you can see only `Find in Buffer` has a keybinding associated with it, and not `Toggle Find in Buffer`.

**Comment by JimmySevere** [comment]
Hi,

Here's the latest from my Debian Jessie LXDE amd64:

![image](https://cloud.githubusercontent.com/assets/3275049/19818343/50ef60ce-9d47-11e6-94f2-4a5e54af9524.png)

and in safe mode:

![image](https://cloud.githubusercontent.com/assets/3275049/19818414/97674c92-9d47-11e6-866d-b48f42b20431.png)


As you can see, the label persists.

Cheers,
Joe
