### ISSUE TITLE
Can't exit find and replace using the escape key

### ISSUE THREAD

**Issue by rahultrivedy** [atom/find-and-replace#773]
cmd+f opens the find and replace pane but escape key does not close it. So, I am not able to close the find and replace pane.

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by rahultrivedy** [comment]
I am using OS X El Capitan v. 10.11.4 and atom 1.9.9. I uninstalled atom and reinstalled it. Everything's working fine now. Thnks anyways.
