### ISSUE TITLE
Make (foo|bar|) an invalid Regex

### ISSUE THREAD

**Issue by DallasO** [atom/find-and-replace#778]
There are times when I am searching for foo or bar, and realize I need a third. Adding a pipe suddenly matches every character and with a large file and a slow system, my computer gets crippled.

**Comment by eddiemonge** [comment]
That is valid regex though. You would have to change how JavaScript works

**Comment by 50Wliu** [comment]
Yeah, I'm :-1: on this as well.  Now that there is syntax highlighting within find-and-replace I'm closing this as a wontfix.
