### ISSUE TITLE
Problem with emmet

### ISSUE THREAD

**Issue by fnoceda** [atom/find-and-replace#790]
I have installed plugins on my atom editor, Emmet & Find, When i use the shortcut (Ctrl+e) atom show me the option "Find & Replace" and when i use the shortcut (Ctrl+f)  it show me the same option, how can i fix that? i want to use the shortcut (Ctrl+e) for generate code abreviations.
Thanks a lot!

**Comment by 50Wliu** [comment]
This, as you noticed, is a problem with Emmet.  Please report this issue to them instead.

**Comment by fnoceda** [comment]
Hi
I disabled emmet and pres Ctrl+e or Ctrl+f and find and replace show the
inputs for search. That is the problem
In the atom setings keybindings show

Why find-and-replace show the inputs for search if Ctrl+f is configured?


KeystrokeCommandSourceSelector
ctrl-f native! Core body .native-key-bindings

KeystrokeCommandSourceSelector
ctrl-e emmet:expand-abbreviation Emmet atom-text-editor:not([mini])

Thanks a lot.
Francisco
