### ISSUE TITLE
Let me toggle all results' fold state

### ISSUE THREAD

**Issue by henrebotha** [atom/find-and-replace#797]
Sometimes I search for something which appears only in one or two places in a project. Then the default-open search results make sense.

Other times, I search for an extremely common term which appears in 40+ files. Then I don't want to immediately see the detailed results for each occurrence. I want to get an overview of files, and then choose the ones I want to expand.

A command palette action to toggle all results folded or unfolded would be ideal.

**Comment by Ben3eeE** [comment]
There is a PR for this under review https://github.com/atom/find-and-replace/pull/768.
