### ISSUE TITLE
Add select previous

### ISSUE THREAD

**Issue by Ryan1729** [atom/find-and-replace#800]
Given I have a word selected like so:

One word, two word, red word, blue `word`

I would like a keyboard shortcut that adds the immediately prior instance of that word to the selection, so the state after hitting that shortcut would be:

One word, two word, red `word`, blue `word`

This would be the opposite of the current `find-and-replace:select-next` feature.

Issue #324 seems to suggest that this feature was available at one point but since there is not a reference to it in the current [menu](https://github.com/atom/find-and-replace/blob/e4fca61c9ec8b339c76686c4efa76aae5e9840a1/menus/find-and-replace.cson) or [keymap](https://github.com/atom/find-and-replace/blob/e4fca61c9ec8b339c76686c4efa76aae5e9840a1/keymaps/find-and-replace.cson) cson files, it seems to have been removed at some point? Or was that referring to the distinct feature `find-and-replace:find-previous` that is currently bound by default to `cmd-shift-g`?

Using that feature in from my initial example state results in the following:

 One word, two word, red `word`, blue word

which is not what I want.

**Comment by UziTech** [comment]
@sadick254 this should be closed based on https://github.com/atom/find-and-replace/pull/1112#issuecomment-756297777
