### ISSUE TITLE
"Endless scroll" behaviour on project search

### ISSUE THREAD

**Issue by BlaM** [atom/find-and-replace#811]
I don't know how you guys call that recently introduced feature that when I do a project search that it only starts to show as many results as it can fit on the page, but when you scroll down it will un-pause the search and add more results.

I'd love to be able to disable that.

a) The scroll bar does not reflect the actual number of results
b) If there are many results and I want to go to one close to the bottom I need to press and hold "End" until  I get to the place I'm looking for - and it's still slower than it was before.

Is there any chance we can get a checkbox on the settings page to make it search ALL results immediately - just like it was doing before?

**Comment by BlaM** [comment]
Huh? Is it gone again? Seems to show all results again...

**Comment by 50Wliu** [comment]
Yeah, I don't recall us ever implementing this 😅.  If it happens again can you try following the steps in the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/) and then create a new issue?  Thanks!

**Comment by BlaM** [comment]
Okay, back... I see this strange behaviour in one project: 

![find](https://cloud.githubusercontent.com/assets/176011/20562084/28fca80c-b182-11e6-92ed-94f8e7d2f006.gif)

Every time the results move I press "End" to scroll to the bottom. Notice how the scroll bar on the right side gets smaller and smaller each time.

**Comment by 50Wliu** [comment]
Whoa.  Does it happen in safe mode (`atom --safe`)?

**Comment by BlaM** [comment]
I just tried - and yes, same behaviour with atom --safe.

I just don't know why it happens here and not in other projects. It's an almost pure JavaScript project with minified files in the project folder. Not sure if that has anything to do with it.

**Comment by Ben3eeE** [comment]
@BlaM What is your output of `atom --version`?

**Comment by BlaM** [comment]
It's the latest auto-update version in Windows 8.1

    Atom    : 1.12.5
    Electron: 1.3.9
    Chrome  : 52.0.2743.82
    Node    : 6.5.0

**Comment by Ben3eeE** [comment]
My guess is that this is because <kbd>Home</kbd> and <kbd>End</kbd> are [not bound to anything](https://github.com/atom/find-and-replace/blob/master/keymaps/find-and-replace.cson) which means that [this function](https://github.com/atom/find-and-replace/blob/master/lib/project/results-view.coffee#L50) doesn't run and these buttons only do the native scrolling action which scrolls to the current end which triggers rendering of more results.

![image](https://cloud.githubusercontent.com/assets/1058982/20705540/97958d9c-b623-11e6-9433-0df2fb1bd52c.png)

**Comment by BlaM** [comment]
It's not just these two buttons. I can see the same behaviour when I use the cursor keys, mouse wheel or "mouse-grab" the scrollbar.

**Comment by BlaM** [comment]
The issue is gone since I stopped using [Seti UI](https://github.com/jesseweed/seti-ui) theme.

I'll close this ticket. It's probably caused by the theme.
