### ISSUE TITLE
Project search with regex seems not to work

### ISSUE THREAD

**Issue by tiagomacarios** [atom/find-and-replace#813]
Steps:
1 - create a folder (project) with two files "a", "b".
2 - add text below to both files:
```
#ifdef __cplusplus
};

```
3 - do a single file search Ctrl+f with `#ifdef __cplusplus\n};` and regex enabled. It will work on both files.
4 - switch to project search Ctrl+Shift+f with the same regex as above Atom will not match any of the files in the project.

**Comment by ramification** [comment]
I've exactly the same problem.

OSX Sierra
Atom 1.12.2

**Comment by 50Wliu** [comment]
The project search regexes are restricted to single line matches only.  See #218 for more information.
