### ISSUE TITLE
incremental search, character class regex gives errors while being typed

### ISSUE THREAD

**Issue by plbowers** [atom/find-and-replace#816]
When using incremental search, a regex with a character class gives errors as the character class is typed in but before it is completely typed in

EXAMPLE:
I want to find either single-quote or double-quote followed by foo

`CTRL-SHIFT-F` (to find in all project)
`[` 
`['` 
`['"` <-- error
`['"]` <-- no more errors - character class is complete and forms a good regex
`/['"]foo` <-- finds what I'm looking for

**Comment by 50Wliu** [comment]
Closing in favor of #809.
