### ISSUE TITLE
'find-and-replace:use-selection-as-find-pattern' no longer works on OSX

### ISSUE THREAD

**Issue by rm-code** [atom/find-and-replace#820]
OSX 10.11.6
Atom 1.13.0-beta6

```
'.platform-darwin atom-text-editor':
  'cmd-e': 'find-and-replace:use-selection-as-find-pattern'
```

`cmd-e` doesn't do anything for me since a few updates. I tried it with a different keybinding, but the search dialog never shows up.

**Comment by Ben3eeE** [comment]
This is intentional https://github.com/atom/find-and-replace/pull/796. I believe `find-and-replace:show` bound to `cmd-f` by default works as `cmd-e` did previously.

**Comment by rm-code** [comment]
@Ben3eeE Ok, thanks for the quick reply.

 It feels really strange that there is no visual feedback at all when you press cmd-e.

**Comment by Ben3eeE** [comment]
It is amazing once you get used to it you can quickly select a word and search for it without opening a panel that steals focus.

@simurai Maybe there should be some indication in the `TextEditor` of what the current find pattern is?

**Comment by rm-code** [comment]
I meant for some reason I am missing the outlines that this gif shows: ![](https://camo.githubusercontent.com/ff85ab0168424fb7874227c79af41e350c3fb681/687474703a2f2f672e7265636f726469742e636f2f484d744e3154694a47722e676966)

When I press cmd-e there is no indicator at all:
![screenshot 2016-11-29 19 22 17](https://cloud.githubusercontent.com/assets/11627131/20723039/367fc9b4-b669-11e6-8bca-401ffb34e8c1.png)

When I press cmd-g it just shows me the next occurence:
![screenshot 2016-11-29 19 22 25](https://cloud.githubusercontent.com/assets/11627131/20723053/454604ae-b669-11e6-8bb4-c9e267d7abe4.png)

I'll try with a different theme.

**Comment by Ben3eeE** [comment]
I believe that is the [highlight-selected](https://atom.io/packages/highlight-selected) package. At least that is what I am using to highlight selected words.

**Comment by rm-code** [comment]
Ok I see. May I suggest highlighting all occurrences directly in the `find-and-replace` package?

**Comment by 50Wliu** [comment]
See #138.

**Comment by simurai** [comment]
You could show the find-results of `cmd-e` by adding the following to your `styles.less`:

```less
atom-text-editor::shadow,
atom-text-editor {
  .find-result {
    display: block;
  }
}
```

![e](https://cloud.githubusercontent.com/assets/378023/20749639/76786166-b736-11e6-93a9-09502fafa81b.gif)

But you can't hide them anymore. :sob: Using [highlight-selected](https://atom.io/packages/highlight-selected) seems nicer. I'll see if the styling can be matched with `cmd-f`.

**Comment by rm-code** [comment]
@simurai That would be great :+1:

**Comment by simurai** [comment]
> I'll see if the styling can be matched with cmd-f.

Unfortunately I couldn't get it to match. Would require some changes to the `highlight-selected` package. So for now, it's just [blue underlines](https://github.com/atom/one-dark-syntax/pull/83), at least that matches the bracket matcher.
