### ISSUE TITLE
Find in project shows files with .gitignore

### ISSUE THREAD

**Issue by paddotk** [atom/find-and-replace#853]
Using Atom 1.8.0 and Find and Replace 0.199.0.

Whenever I search within my project, anything that should be hidden according to the .gitignore files, are being displayed. In Atom's core settings the 'exclude VCS ignored paths' option is checked.

**Comment by 50Wliu** [comment]
Please upgrade to the latest Atom version, currently Atom 1.13.1 but soon to be Atom 1.14.0.  If you are still able to reproduce the issue, then file a new issue with the issue template filled out.  Thanks!

**Comment by paddotk** [comment]
Whoops, I thought it was the most recent version... When I try to update Atom the terminal says 'Atom is already the newest version (1.8.0)'.. But I got it fixed, thanks.
