### ISSUE TITLE
"Select Next" no longer works with multiline selections

### ISSUE THREAD

**Issue by isiahmeadows** [atom/find-and-replace#854]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

"Select Next" no longer works with multiline selections

### Steps to Reproduce

1. Enter the following text:
```
aa
aa

aa
aa
```
2. Select the first two aa's
3. Trigger `find-and-replace:select-next` (via command panel, Ctrl+D, etc.)

**Expected behavior:** The second set of aa's to be selected.

**Actual behavior:** Nothing.

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom: v1.14.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Last version I remember working was 1.12.7, but I just updated yesterday.

**Comment by isiahmeadows** [comment]
This is a productivity killer for me, because I used that extensively. It makes refactoring far easier.

**Comment by 50Wliu** [comment]
Confirmed on Atom 1.15.0-dev-ae6a7a0.

**Comment by isiahmeadows** [comment]
The break happened between 1.13.1 and 1.14.0-beta0, from some manual
bisecting I did in spare time using fresh versions. Problem is, I can't
repro it at all in Atom 1.13.1, even after upgrading its package
(find-and-replace@0.204.5) to the version in Atom 1.14.0-beta.0
(find-and-replace@0.205.1). So it has to be an issue with another package,
likely Atom Core itself.

-----

Isiah Meadows
me@isiahmeadows.com

**Comment by isiahmeadows** [comment]
If it happens to be in core (neither text-buffer nor event-kit had any
changes to likely cause problems), it's probably no earlier than this
commit, and in this file:
https://github.com/atom/atom/commit/5ee3dbe7e0e71392a4057ce4807339765efd9ede

Just an educated guess.

-----

Isiah Meadows
me@isiahmeadows.com

**Comment by maxbrunsfeld** [comment]
Sorry about this, folks. The fix will go out today in v1.14.1 and v1.15.0-beta1.

**Comment by nathansobo** [comment]
This is fixed in [1.14.1](https://github.com/atom/atom/releases/tag/v1.14.1), which I just published.

**Comment by kidbrax** [comment]
So should we just be able to copy and paste multiline segments into the find dialog? Or do we need to explicitly add in the newline codes? It doesn't seem to work either way for me.  Anyway you could provide a simple sample?

**Comment by 50Wliu** [comment]
This issue was referring to the `find-and-replace:select-next` command, ctrl/cmd-d by default.  Basically like an inline find-and-replace.
