### ISSUE TITLE
Atom hangs while performing searches, causing data loss if it never finishes

### ISSUE THREAD

**Issue by alexchandel** [atom/find-and-replace#856]
Whenever complicated searches, possibly matching thousands of strings in a large document, are typed, Atom hangs as find-and-replace evaluates them. This can severely impede typing long searches, where the beginning of the regex matches most of the document up to the last few characters.

The fundamental problem is that find-and-replace performs its searches synchronously on the same thread that responds to GUI interaction.

This is the source of the hangs in #557, #627, likely #603, and pretty much every hang experienced while find-and-replace is operating on a large document.

Often, when a user is performing a search that is taking extremely long (which find-and-replace is wont to do), the user may wish to cancel it. No option exists short of killing Atom, which invariably results in the loss of unsaved data. A good text editor would allow this, and even allow you to edit the `Find` text field while the search is taking place, cancelling it and beginning a new one.

If Atom didn't hang while performing searches, perhaps by performing search asynchronously or on a separate thread, then the user would be free to simply clear the `Find in current buffer` text field, assumedly cancelling the search.

This behavior needs to stop, and is one of the last truly nasty "Gotcha!"s remaining in Atom.

### Versions
```
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by lee-dohm** [comment]
Thank you for your submission!

I have passed along the information to the maintainers team. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.
