### ISSUE TITLE
Regex \s no longer matches ends of line in Atom 1.14.1.

### ISSUE THREAD

**Issue by garretwilson** [atom/find-and-replace#858]
I have this HTML on Windows (with CRLF line endings):

```html
					<th><br />
					</th>
```

(They are indented.)

I'm practically positive I used to be able to turn on regex and search for `<th><br />\s*</th>`, but this doesn't work anymore. Interestingly, neither does `<th><br />.*</th>`.

The only way I can get it to work is if I use `<th><br />\r\n\s*</th>`. (This is not only cumbersome, I have to know which EOL type is in use.) This leads me to believe that Atom is no longer matching CR and LF with `\s`.

(Sorry, I don't have time to try safe mode, etc. right now. I hope this bug post is helpful.)

**Comment by 50Wliu** [comment]
@garretwilson I hope you mean Atom 1.14.1?

At any rate, I can reproduce this on Atom 1.16.0-dev-4494fb5.

**Comment by maxbrunsfeld** [comment]
Yep, this regressed in 1.14. Thanks for the heads up @garretwilson and @50Wliu. Fixing now!

**Comment by garretwilson** [comment]
> I hope you mean Atom 1.14.1?

Haha, yes. Glad you were able to reproduce it.
