### ISSUE TITLE
command + F key invalid

### ISSUE THREAD

**Issue by tiansn** [atom/find-and-replace#872]
### Description

[when I use atom search content,  atom only find one,Actually the centent has more than one]

### Steps to Reproduce

1. Open Atom
2. Press Cmd + F to search in opened file
3. Enter in a string
4. click 'Find' button or press 'enter' key

**Expected behavior:** [focus to first key word and highlight all key word]

**Actual behavior:** [only find one and not any highlight]

### Versions

macOS Sierra v10.12.3
atom v1.15.0 x64
apm v1.15.3

### Additional Information

like following img:
<img width="993" alt="qq20170315-135032 2x" src="https://cloud.githubusercontent.com/assets/4652939/23935889/be60ca04-0989-11e7-873d-400171827054.png">

**Comment by 50Wliu** [comment]
That's because you're searching within the current selection, which does not contain the second EmojiObj.
