### ISSUE TITLE
[Feature Request] Use ripgrep

### ISSUE THREAD

**Issue by Stanzilla** [atom/find-and-replace#878]
VS Code recently [switched](https://github.com/Microsoft/vscode/commit/62ec995019e86074c5aa24003d2f960bd9282d90) to [ripgrep](https://github.com/BurntSushi/ripgrep) for search and it might be worth investigating doing the same in Atom. It is really fast. ⚡️ 

* https://github.com/roblourens/vscode-ripgrep
* https://github.com/Microsoft/vscode/issues/19983

**Comment by 50Wliu** [comment]
Please add your suggestion to #571.  Thanks!
