### ISSUE TITLE
Search in Directory context menu missing

### ISSUE THREAD

**Issue by robertkern** [atom/find-and-replace#887]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Prior to Atom `1.17.0-beta2` the `Search in Directory` context menu in tree-view was shown. Since that version, the option is missing.

### Steps to Reproduce

1. Open a project
2. Right click on a directory

**Expected behavior:** [What you expect to happen]

Expect to see `Search in Directory` option

**Actual behavior:** [What actually happens]

The `Search in Directory` option is not shown

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

`1.17.0-beta2` and `1.17.0-beta3`

**Comment by rsese** [comment]
I can repro in beta3 as well on macOS - I don't think this was intentional /cc @maxbrunsfeld @nathansobo, related to docks work?

**Comment by karli2000** [comment]
I can repro in beta3 on Windows x64.
Please fix it!

**Comment by pjconnors** [comment]
Can be reproduced in 1.17.0-beta4 (MacOS 10.11.6).

**Comment by Dayjo** [comment]
Any idea when this will be released?

**Comment by Ben3eeE** [comment]
@Dayjo This will be released in the next beta hotfix release `1.17.0-beta5`.

**Comment by Dayjo** [comment]
@Ben3eeE  Thanks

**Comment by EvNaverniouk** [comment]
Oh no! It's disappeared again in 1.18.0-beta0. @Ben3eeE

**Comment by Dayjo** [comment]
As @EvNaverniouk has stated, I just updated and it's gone again :(

**Comment by GioLogist** [comment]
Gone for me as well on 1.18.0-beta0!

**Comment by Ben3eeE** [comment]
I can not reproduce this using Atom 1.19.0-beta7. If you still don't see the Search in Directory context menu item when right clicking on a folder in the tree-view then please file a new issue.
