### ISSUE TITLE
Add AST support?

### ISSUE THREAD

**Issue by kentcdodds** [atom/find-and-replace#894]
Hi there :wave:
I've been toying around with this idea of using ASTs as a mechanism for doing find/replace. I particularly like the visitor API exposed by babel and would like to develop a plugin to allow users to do find/replace using a babel plugin essentially. I have the very beginnings of something [here](https://github.com/kentcdodds/ast-find-replace-atom).

The more I work on it, the more I realize that it would actually reuse a ton of the same stuff that this plugin does. I'm curious whether ya'll would be interested in me working on this as a pull request to this project. I think it could be really useful! I kind of envision it being something like:

<img width="161" alt="screen shot 2017-05-12 at 11 38 20 pm" src="https://cloud.githubusercontent.com/assets/1500684/26022863/1cf87c5e-376d-11e7-9dfd-d58283155f73.png">

When you click that tree you get a new editor with:

<img width="387" alt="screen shot 2017-05-12 at 11 39 45 pm" src="https://cloud.githubusercontent.com/assets/1500684/26022864/2741ac44-376d-11e7-9002-d5ecfa69a8b3.png">

Where you can write out your babel plugin to do find/replace.

I can do all the AST-related work, but the Atom APIs are pretty foreign to me (including the CoffeeScript stuff in this codebase which I'm getting used to). I could really use some direction for a good way to approach this. Any help is appreciated. ASTs are way more powerful than regex and I think that if we get this support, people will be able to do much more complex and useful things with find-and-replace.

Thanks a bunch for your time and this plugin. It's great!

**Comment by kentcdodds** [comment]
Note: For the start this would only support JavaScript that can be parsed by Babel, but I don't see any reason why this couldn't support everything. For example, [ASTExplorer.net](https://astexplorer.net/) supports several languages:

<img width="165" alt="screen shot 2017-05-12 at 11 53 52 pm" src="https://cloud.githubusercontent.com/assets/1500684/26022916/4b20293c-376e-11e7-8f5d-ac64fef301ba.png">

**Comment by kentcdodds** [comment]
It may even be made more generic and you could just plug in arbitrary JavaScript where your new editor just exports a function that receives the source and filename and you return the new source. That'd be royally flexible (maybe too much)...

But I think it'd be good to keep this scoped down and not get ahead of ourselves :)

**Comment by suchipi** [comment]
I would use this (though it's admittedly pretty niche). Maybe find-and-replace could support providers for this use case (similarly to how autocomplete-plus works)?

**Comment by kentcdodds** [comment]
I would be cool with that 👍

**Comment by Qix-** [comment]
Any thoughts on project-level support? For example, if I have an AST that can resolve fully qualified symbols and I want to rename something in one file, then all identifiers in the project that have that identifier are refactored? Similar to Eclipse/IntelliJ refactoring for Java.

Not sure if that's scope creep.

**Comment by kentcdodds** [comment]
Unsure what you mean @Qix-, but my thinking is that the scope of the files changed would be determined the exact same way the current find/replace functionality determines it.
