### ISSUE TITLE
"Find in project" output does not show matching lines in all cases

### ISSUE THREAD

**Issue by sbromberger** [atom/find-and-replace#896]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Ref https://github.com/atom/atom/issues/14430

Using `1.18.0-beta0` downloaded today, I attempted to do a Find In Project. Two files matched; only a portion of the first file's lines were displayed, and none of the second file's lines were displayed. See screenshot.

### Steps to Reproduce
1. Open project
2. Find -> Find in Project -> enter search term
3. Expand all results.

**Expected behavior:** [What you expect to happen]

Results should display the instances of the found text.

**Actual behavior:** [What actually happens]

Results do not display all instances of the found text.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% when the found text is in a comment block.

### Versions
1.18.0-beta0

### Additional Information

see screenshot.

<img width="676" alt="screen shot 2017-05-16 at 12 39 40" src="https://cloud.githubusercontent.com/assets/941359/26124847/d802f7b2-3a34-11e7-8efd-6ebb2a4ba13e.png">

The comment block that does not get displayed is in https://github.com/JuliaGraphs/LightGraphs.jl/blob/4928bc05eaaad75a6d05a1390be9f5840c68705e/src/centrality/katz.jl

**Comment by rsese** [comment]
Thanks again for re-opening this @sbromberger - I was unable to reproduce after either just copying the 2 files (https://github.com/JuliaGraphs/LightGraphs.jl/blob/13b25bb30c6ed2fbb248ec34b6fe370811855000/LICENSE.md and https://github.com/JuliaGraphs/LightGraphs.jl/blob/4928bc05eaaad75a6d05a1390be9f5840c68705e/src/centrality/katz.jl) or by cloning the whole repo.  In both cases, I ran a project find for "arising" and I see all results:

![results](https://github-slack.s3.amazonaws.com/monosnap/Project_Find_Results__tmpLightGraphs.jl_2017-05-16_18-33-10.png)

I tried in 1.18.0-beta on macOS 10.12.4 and on 1.17.0.

Out of curiosity, what theme are you using?

**Comment by sbromberger** [comment]
Thanks. This is 1.18.0-beta on 10.12.4 as well.

UI Theme is "Native", syntax theme is "One Light". I'll try changing them.

**Comment by rsese** [comment]
Ahhh thanks for confirming, I thought it was slightly interesting that 1 result was missing from both files :v:
