### ISSUE TITLE
Regex replacement does not work as expected

### ISSUE THREAD

**Issue by gvdgdo** [atom/find-and-replace#900]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The regex  replace pattern $$1 produces $1, instead of $replacement. 

### Steps to Reproduce

1. Search for the regex:  (\w+)
2. Replace with the pattern $$1

**Expected behavior:** [What you expect to happen]

Given the text:

test

the regex (\w+),  and replacement $$1

the outcome should be 

$test

**Actual behavior:** [What actually happens]

$1

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always, 100%

### Versions

`atom --version`

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

`apm --version`

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Different regex online testers give different results on this

https://regex101.com 

gives the expected result

http://www.regextester.com
http://regexr.com

return the unexpected result.

**Comment by pixilz** [comment]
@gvdgdo This is technically expected result based on implementation. When you use "$$" in many regex implementations (.NET, JavaScript, VBScript, XRegExp, PCRE2, and std::regex) with replacement text the second dollar sign escapes the first. What you would need to do for what you want to use is

`Find: (\w+)`  `replace with: $$$1`

Php doesn't use this implementation. Anyway, if this would need to be fixed we would need to change the implementation. If we are using the "native" regex implementation (which I believe we are) then it is definitely working as expected. With different languages I can definitely understand why it is confusing in some regards. 

This article gives great information about the different implementations of regex.
[http://www.regular-expressions.info/replacecharacters.html](http://www.regular-expressions.info/replacecharacters.html)
