### ISSUE TITLE
'Find in current buffer' returns no results

### ISSUE THREAD

**Issue by borremosch** [atom/find-and-replace#901]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Find in current buffer is returning no results at all in many cases. It is hard to pinpoint when it's not working, but it seems that it is having trouble when opening a file that has not been opened for a while, and does after re-opening a couple of times.

### Steps to Reproduce

1. Launch Atom in your local atom repository
1. Single-click `README.md` in the Tree View
1. Open find-and-replace with <kbd>Cmd+F</kbd>
1. Type `atom` in the search box

**Expected behavior:** ~90 results found

**Actual behavior:** No search results are found

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.17.1
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.13.0
```

**Original:** Using Windows 10 x64, all updates installed

**Reproduced on:** Mac OS X 10.12.5

### Additional Information

'Only in selection' toggle is off, but all options may be on or off, all combinations produce the same bug. 
I have deleted Atom, removed ~/.atom and re-installed Atom, the problem persisted.
Bug is reproducable in safe mode.

If you can give me some pointers I will probably be able to debug this on my own system.

This screencast shows what happens when searching for single characters, that are definitely in the file:

![screencast](https://cloud.githubusercontent.com/assets/1812579/26317853/2a87337a-3f19-11e7-8189-2381585f6cea.gif)

**Comment by swrobel** [comment]
What packages do you have installed? I realized I had an ancient package, [synced-sidebar](https://github.com/peterdotjs/atom-synced-sidebar/issues/33), installed and that was causing this issue for me.

**Comment by borremosch** [comment]
I have tried running atom using --safe and the bug is still there, so it probably shouldn't be caused by one of the dependencies I have installed, right?

**Comment by EsrefDurna** [comment]
+1 same problem

**Comment by pixilz** [comment]
Do either of you have an editor in your docks when this is occurring? 
@EsrefDurna Does `atom --safe` fix the problem for you?

If you put your mouse into the editor and then click back into the search bar does it fix the problem?
(My reason for this question has to do with how it saves the editor you are currently in)

For @borremosch you mentioned being able to debug on your system. If you take a look at `find-and-replace/lib/buffer-search.js` you can see `this.editor` I would start with checking the `setEditor` function to see when it is going off and what it is setting it to. From there I might take a look at how it is using the search function. If nothing interesting turns up my next guess would either to go from what I had or take a look at the `find-and-replace/lib/find-view.js` file. From there my first guess would be to check out the `search` function. 

Hopefully some of that amounts to something.

**Comment by EsrefDurna** [comment]
today it happen again, typed on the document then it star working again
its so random
yes linter ui default (Eslint) is show always at the bottom of the window,
project view is on left,

**Comment by EsrefDurna** [comment]
I found the problem,
Reproducing the issue step by step

1) Project Tree View should be docked to Left
2) Click to a file open the file on the main window
3) on the open the 'Find in current buffer'
4) type a word in the file example: hello world (found 10 results)
5) click to Tree view again to the same file
6) AND Look to the Search it will tell you " No result"
7) click to change the world hello world to > hello or anything you will see no result
8) click to file content then find result will change and tell you (found 10 result)

**Comment by EsrefDurna** [comment]
and plus +
now even clicking file content wont fix it,.....

**Comment by borremosch** [comment]
@EsrefDurna is right. Whenever the treeview is focused, I am unable to find and replace.

@pixilz I have added logging to the setEditor function. It seems that every time I click in the tree view, setEditor is called with editor == null. This is very annoying, as often times I click a file in the tree view, then immediately press Ctrl+F to search, and this will always yield no results. Actively adding focus to the text editor window will solve the problem, but this adds an unnecessary click to my workflow.

setEditor seems to be called from outside of find-and-replace, so I'm not sure where to continue. Any suggestions?

**Comment by pixilz** [comment]
@borremosch I have been able to reproduce this, it seems to have to do with the new dock update (could be wrong). The simplest solution is going to probably be checking if the selected view is an editor and verifying the previous editor is still visible upon the setting of that variable.

**Comment by simistern** [comment]
+1 same issue for me, I have tried several of the steps above with little result. Is there a patch on the way?

**Comment by pixilz** [comment]
I have a little bit of a crazy weekend (graduation time for family) but I can take a look when I have some free time if no one else has.

**Comment by lee-dohm** [comment]
I've updated this with a very simple set of repro steps. Thanks @EsrefDurna for helping to narrow it down!

**Comment by pixilz** [comment]
The proposed solution may lead to problems with having editors inside of docks. (If that becomes a common occurrence) 
Otherwise, glad it is getting fixed. ^.^

**Comment by nathansobo** [comment]
@pixilz Yeah, that crossed my mind. It's not something I care a bunch about supporting right now such that it's worth thinking through all the implications of falling back to the center if the dock item isn't an editor. If it becomes common we should revisit.

**Comment by pixilz** [comment]
@nathansobo  
A solution that recently came to mind was to potentially add two things. 

In the editor settings of Atom have an option that basically sets it either to where it was previously to where your fix will put it now. (Either forcing middle editor to be the only active or no enforcement)

Then add a config to packages to allow packages to turn off the ability for their pane items to be marked as a the "active editor."
