### ISSUE TITLE
text Search isn't working at

### ISSUE THREAD

**Issue by rsese** [atom/find-and-replace#903]
*From @EsrefDurna on May 23, 2017 17:12*

### Description

text Search isn't working at 

### Steps to Reproduce

1. at any normal document control+f 
2. type any text which is in the document to the search area,
3. see that there is no results,
4. close the document, re-open it, try again and its working,

**Expected behavior:** [What you expect to happen]
search should work,

**Actual behavior:** [What actually happens]
not working,
**Reproduces how often:** [What percentage of the time does it reproduce?]
so frequently,

### Versions
1.17.0 at windows,

*Copied from https://github.com/atom/atom/issues/14599*

**Comment by rsese** [comment]
*From @pixilz on May 23, 17:45*

@EsrefDurna If you open up the keybinding resolver (`ctrl+.` by default) and press `ctrl+f` in these instances can you see what is causing the error and/or send in a screenshot of the results? (After which we may need to see your installed packages)

**Comment by rsese** [comment]
> (After which we may need to see your installed packages)

Along these lines, can you reproduce in safe mode (`atom --safe`)?

**Comment by borremosch** [comment]
This looks to me like it's the same problem as #901

**Comment by EsrefDurna** [comment]
Yes its exavtlu the same problem,

**Comment by rsese** [comment]
Thanks @borremosch, closing as a dupe.
