### ISSUE TITLE
Uncaught TypeError: Cannot read property 'leadingContextLines' of undefined

### ISSUE THREAD

**Issue by axelson** [atom/find-and-replace#909]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.208.3

### Stack Trace

Uncaught TypeError: Cannot read property 'leadingContextLines' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-view.js:279

TypeError: Cannot read property 'leadingContextLines' of undefined
    at ResultsView.positionOfSelectedResult (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-view.js:279:1)
    at ResultsView.scrollToSelectedMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-view.js:458:1)
    at ResultsView.moveDown (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-view.js:353:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:16.3.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:15.3.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:15.2.0 vim-mode-plus:move-to-beginning-of-line (input.hidden-input)
     -0:14.9.0 core:save (input.hidden-input)
     -0:14.6.0 core:close (input.hidden-input)
  3x -0:13.7.0 core:move-down (div.results-view.focusable-panel)
     -0:10.7.0 core:confirm (div.results-view.focusable-panel)
     -0:10.1.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:09.7.0 vim-mode-plus:move-to-previous-word (input.hidden-input)
     -0:09.5.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:08.5.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:08.3.0 vim-mode-plus:move-to-beginning-of-line (input.hidden-input)
     -0:08.0 core:save (input.hidden-input)
     -0:06.5.0 core:close (input.hidden-input)
     -0:03.6.0 core:move-down (div.results-view.focusable-panel)
     -0:02.3.0 core:close (div.results-view.focusable-panel)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.26 
atom-jade 0.3.0 
atom-ternjs 0.18.3 
busy-signal 1.4.1 
color-picker 2.2.5 
cursor-history 0.11.1 
editorconfig 2.2.2 
goto 1.8.3 
highlight-selected 0.13.1 
intentions 1.1.2 
language-elixir 0.18.0 
linter 2.1.4 
linter-elixirc 1.6.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.0 
pigments 0.39.1 
react 0.16.2 
react-snippets 0.7.4 
redux-snippets 0.2.2 
tab-control 0.6.10 
tabs-to-spaces 1.0.3 
vim-mode-plus 0.93.0 
wordpress-api 1.2.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by dirk-thomas** [comment]
In version 0.208.3 the referenced line number 279 is [empty](https://github.com/atom/find-and-replace/blob/v0.208.3/lib/project/results-view.js#L279). Can you please double check the version of this package you are using.

**Comment by sbkmmi** [comment]
1. Search Directory
2. Select Copy Path when right-clicking on File Path of search results

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [find-and-replace](https://github.com/atom/find-and-replace) package 0.208.3

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At ~\AppData\Local\atom\app-1.18.0\resources\app\node_modules\find-and-replace\lib\project\results-view.js:437

ReferenceError: path is not defined
    at ResultsView.copyPath (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/find-and-replace/lib/project/results-view.js:437:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```
### Commands
```
     -0:27 project-find:show-in-current-directory (span.name.icon.icon-repo)
     -0:10.3.0 find-and-replace:copy-path (span.path-name.bright)
```
### Non-Core Packages
```
activate-power-mode 2.0.0 
apex-ui 0.2.1 
language-salesforce 0.6.0 
minimap-find-and-replace 4.5.2 
qolor 0.4.2 
```

**Comment by dirk-thomas** [comment]
In version 0.208.3 the referenced line number [437](https://github.com/atom/find-and-replace/blob/v0.208.3/lib/project/results-view.js#L437) seems to not contain a variable `path`. Can you please double check the version of this package you are using as well as the exact content of that line on your system.

I tried to reproduce the right-clicking on file path of search results and it worked for me (while I only tested it with a custom branch that branch shouldn't have any changes in that area).

**Comment by 50Wliu** [comment]
That error shouldn't have been directed here.  But it seems like stacktraces are incorrect - it should be pointing to [this line](https://github.com/atom/find-and-replace/blob/v0.208.3/lib/project/results-view.js#L424) instead.

**Comment by axelson** [comment]
I haven't been able to reproduce, it kept happening during one session of Atom (at least 5 times so I finally reported it). But after restarting I haven't been able to reproduce at all. I'm fine if it is closed.

**Comment by OmeGak** [comment]
Happening to me as well.

**Comment by axelson** [comment]
Okay just ran into this again and it triggered my memory. Here are the steps to reproduce:

Have a file `long.txt` with the contents:
```
long
long
long
long
```

Have a file `short.txt` with the contents:

```
long
```

1. Do a global search for "long"
2. Press "enter" to go to the first file that has a match (ideally this is long.txt)
3. Press "cmd+shift+\" to locate that file in the tree view
4. Press "delete" to delete that file (Running "Tree View: Remove" would probably work as well)
5. Press "enter" to take the "Move to Trash" action
6. Press "ctrl+0" to switch back to the code editor tabs
7. You should now be back on the search results page
  a. Note that the file that you deleted is still shown! This is a bug that has been annoying me (but it's not part of this project, although it quite likely to be related to this bug)
8. Press "down" a couple times
9. Press "enter" to go to the already deleted long.txt
10. Switch back to the previous tab (I press "cmd+shift+[")
11. You are now back on the search results page but the deleted long.txt is now gone
12. Press "down"
13. Get the error

My guess as to what is happening:
1. The cursor position on the search results window is being persisted within the `find-and-replace` module
2. The cursor position is not on the first line (say it is at index 2)
3. On step 9 we go to the deleted file which causes atom to re-read the file and update the search results, thus removing the already deleted file from the search results
4. `find-and-replace` is not aware that the file (long.txt) has been removed from the search results
5. Once we go back to the search results and try to go further down, the cursor position is now invalid (since short.txt only has one instance of the search string).

Right now I was refactoring some code and removing a module completely so it was easy to get the scenario where my cursor ended up on a now non-existant line. That was probably what I was doing when I first ran into this issue as well. This is now reproducible 100% based on my above steps (although I'm sure you could shorten them if you want). Hope this helps track down the 🐛 !

**Comment by Ben3eeE** [comment]
Thanks for the steps to reproduce @axelson :bowing_man: I can reproduce both this and https://github.com/atom/find-and-replace/issues/883 using your steps.

For step 11, to get the deleted `long.txt` to disappear from the project find results I had to make changes to `long.txt` after opening it from the project find results in step 9.

To reproduce https://github.com/atom/find-and-replace/issues/883 I had a single file named `long.txt` and did the same steps, because I missed the step to create `short.txt`

I was outside of safe mode when reproducing and never tested in safe mode.

/cc: @maxbrunsfeld

**Comment by dirk-thomas** [comment]
Thanks you for the detailed example how to reproduce the problem. Since I contributed the context lines logic recently I took a look if that was related. It turns out that the results view doesn't "know" that the result has been removed and therefore contains invalid indices for the currently selected result / match. The error message is just one symptom of these wrong indices. Please see #926 which makes sure that the indices are updated to stay valid when results are added or removed (as in your example).
