### ISSUE TITLE
Select next does not respect reversed orientation of initial selection

### ISSUE THREAD

**Issue by nathansobo** [atom/find-and-replace#928]
When you hit `cmd-d` to select the next piece of text matching the current selection, the new selection does not match the orientation of the initial selection.

![cmd-d-directionality](https://user-images.githubusercontent.com/1789/28127416-bc31a8f8-66e9-11e7-8ebb-09eecb9b4320.gif)

## Repro Steps

1. Launch Atom
1. Open a new editor using <kbd>Cmd+N</kbd> on macOS or <kbd>Ctrl+N</kbd> on other platforms
1. Enter the text `test\ntest\ntest\n`
1. Using the mouse, select the first instance of the word `test` **from right to left** so that the cursor lands at the beginning of the word
1. Press <kbd>Cmd+D</kbd> twice to select the other two occurrences of the word

**Expected:** The cursor should be at the beginning of the selection in all three instances

**Actual:** The cursor remains at the beginning for the first selection but is at the end of the selection in the latter two selections

Reproduced using Atom v1.20.0-dev-a38b43833 on Mac OS X 10.12.6

/cc @rsese @ungb for prioritization

**Comment by iolsen** [comment]
@nathansobo @ungb can't repro this on master. Do you remember what version you saw it on?

**Comment by lee-dohm** [comment]
This also reproduces when cursor navigation keys are used to perform the selection from right to left.
