### ISSUE TITLE
Vim Mode Plus binding for ctrl-f masks search function in vanilla Atom

### ISSUE THREAD

**Issue by cspoleta** [atom/find-and-replace#934]
If I comment out line 113 from ~/.atom/packages/vim-mode-plus/keymaps/vim-mode-plus.cson will it have the effect of restoring the original meaning of 'ctrl-f' by unmasking it from the vim-mode-plus binding?

Like this:

```
--- /old/vim-mode-plus/keymaps/vim-mode-plus.cson	2017-07-23 22:16:37.820417233 -0400
+++ /new/vim-mode-plus/keymaps/vim-mode-plus.cson	2017-07-23 22:25:03.781091855 -0400
@@ -110,7 +110,7 @@
  'ctrl-u': 'vim-mode-plus:scroll-half-screen-up'
   'ctrl-b': 'vim-mode-plus:scroll-full-screen-up'
   'ctrl-d': 'vim-mode-plus:scroll-half-screen-down'
-  'ctrl-f': 'vim-mode-plus:scroll-full-screen-down'
+  ## 'ctrl-f': 'vim-mode-plus:scroll-full-screen-down'
   'ctrl-e': 'vim-mode-plus:scroll-down'
   'ctrl-y': 'vim-mode-plus:scroll-up'

``` 
NB: vim-mode-plus is the only package that has been added to my original Atom installation on Linux.  

Everything about this package is great, but I don't need a command to scroll down one window, and I DO need a 'search this buffer' command that uses the find/replace options mini-window.

**Comment by 50Wliu** [comment]
@cspoleta you should report this to the vim-mode-plus package.
