### ISSUE TITLE
Combine multiple results on one line into one result

### ISSUE THREAD

**Issue by johnbillion** [atom/find-and-replace#935]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When a "Project Find" search results in more than one match on the same line, multiple results are shown. Ideally, these results should be combined into one result with two highlights on the same line.

### Steps to Reproduce

1. Perform a "Project Find" for a simple phrase which appears multiple times on a line, for example the letter `e`.
2. Note that a search result is shown for each occurrence, despite multiple occurrences per line.

**Expected behavior:**

I'd expect that multiple occurrences of a result on a line would be presented as one result.

Mockup screenshot:

<img width="695" alt="after" src="https://user-images.githubusercontent.com/208434/28891195-91b48094-77c1-11e7-9e20-de22524ec1be.png">

**Actual behavior:**

Each occurrence is presented as an individual result:

Actual screenshot:

<img width="695" alt="before" src="https://user-images.githubusercontent.com/208434/28891229-b6f46dec-77c1-11e7-93a2-e5cdebd0749a.png">

### Versions

Atom    : 1.19.0-beta5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

OS: macOS 10.12.3

**Comment by HebaruSan** [comment]
This would be great to have.
In addition, if you use the newer context feature to show lines before and after a hit, it would be nice if it combined overlapping hits to avoid showing the same line multiple times as in:

![image](https://user-images.githubusercontent.com/1559108/30391950-db0b5896-9880-11e7-9259-278d8b14cea7.png)
