### ISSUE TITLE
There is no way to insert a tab (\t) in "Find in current buffer" 

### ISSUE THREAD

**Issue by alexandernst** [atom/find-and-replace#940]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There is no way to insert a tab (\t) in "Find in current buffer" 

### Steps to Reproduce

1. `Ctrl + F` to open the "Find in Current Buffer" tool 
2. Hit `TAB`
3. I'd expect the `tab` character to be inserted. Instead, the next input field gets the focus.

**Comment by matias-lopez-mauro** [comment]
You have to enable Regex (the `.*` Option on top-right of Find-and-Replace dialog), then use the regex `\t` in "Find in current buffer" to match TAB chars.
It is expected that `TAB` keystroke moves between focusable elements on the dialog.

**Comment by lesar** [comment]
This issue have to be reopen: the problem is back in **Atom 1.41.0 on Ubuntu 19.10**  

If I insert a `tab` in the document text and then  

1. open find-and-replace dialog  
1. enable regex
1. type **\t** in find dialog
1. hit find button

nothing was find
best regards,  
Leonardo
