### ISSUE TITLE
Last result in Project Find Results is not clickable due to scrollbar

### ISSUE THREAD

**Issue by adamreisnz** [atom/find-and-replace#943]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When doing a find in project which generates a lot of results (enough to fill the window), you can't click on the last result because the (invisible) scrollbar is overlapping it.

### Steps to Reproduce
1. Search in project
2. Scroll to bottom to see last result
3. Click on result

**Expected behavior:**
Go to result

**Actual behavior:**
Nothing happens.

**Reproduces how often:**
100%

### Versions

OS X

Atom    : 1.20.0-dev-cb08c1b
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.3
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.1

### Additional Information
It looks like the problem is twofold: there is an (invisible) horizontal scrollbar, which is not needed in this case, and it overlaps the last result, making it unclickable.

Only seems to happen when you have this setting enabled in OS X:

![image](https://user-images.githubusercontent.com/490562/29499348-14349b26-8663-11e7-93ff-d61a2a795ff7.png)

When you set it to "Always", a smaller, dark atom themed horizontal scrollbar appears in the search results, but it sits below the results as expected.

When the option is set to "When scrolling", you can observe two different horizontal scrollbars, depending on where you are with your mouse when scrolling left/right. The normal one appears when you're scrolling the results, but an ugly, grey scrollbar appears when you scroll while hovering over the last result.

I've tried to capture this in a GIF:

https://www.dropbox.com/s/pk636pllc8p71o6/scrollbars.gif?dl=0

If you click just above the scrollbar, on the last result, there's about a 2 pixel capture area which does allow you to click on the last result.

**Comment by Ben3eeE** [comment]
Can you please pull from latest master and give this another try? We have fixed several editor regressions recently and your version is a bit old.

/cc: @rsese This and https://github.com/atom/atom/issues/15350 sounds a bit similar. Can you try to reproduce these two issues on macOS with the additional information? Or try to reproduce https://github.com/atom/atom/issues/15350 on Linux with the additional information we got there.

**Comment by adamreisnz** [comment]
Still the same issue in latest build off master

**Comment by ungb** [comment]
I am able to repro this on mac only when `when scrolling` is set in mac scrolling preferences

see screenshot:
![image](https://user-images.githubusercontent.com/5624870/29548099-0d2a25da-86b3-11e7-8511-8528163c6a46.png)

**Comment by maxbrunsfeld** [comment]
I see that the last search result is not clickable when the large scrollbar is showing. I think that is normal. I also see that the large scrollbar sometimes stays there after you mouse away from it. I'm not sure what is causing that.

It seems like you can always get the large scrollbar to go away just by scrolling vertically a little bit. Just so I understand the severity of this problem, is anybody getting into a situation where it's hard to make the scrollbar go away?

**Comment by adamreisnz** [comment]
@maxbrunsfeld I think you misunderstand. The scrollbar is not visible at all for me under normal circumstances, and I can *not* get rid of it by scrolling vertically.

I actually ran into this again today, where I could not click the last result because it was "hidden" by the invisible scrollbar.

Are you on a Mac yourself?

**Comment by maxbrunsfeld** [comment]
Yeah I’m on a Mac and have enabled scroll bars when scrolling in system preferences. Thanks for clarifying; I haven’t yet been able to reproduce the situation you’re describing with the invisible scroll bar, but it does sound like a bad situation

**Comment by adamreisnz** [comment]
So the scrollbar only appears when you scroll left and right, it's invisible otherwise, just like any scrollbar on Mac when you have the setting enabled as follows:

![image](https://user-images.githubusercontent.com/490562/31356607-2351361e-ad9b-11e7-8bdd-7411c6e1e00e.png)

When you stop scrolling, the scrollbars disappear again.

So the problem, imo, is that there is a scrollbar at all. There shouldn't be one when there is no horizontal overflow.

When I make my search results window more narrow, as to force the content to overflow, then I see two horizontal scrollbars.

So one of them is clearly there in error, and it's probably just a CSS issue.

**Comment by adamreisnz** [comment]
It's this element which doesn't have a class and gets assigned inline-style `overflow: auto`. (Why inline? I can't override it now easily with my custom stylesheet.)

![image](https://user-images.githubusercontent.com/490562/31357351-dc4bb1a6-ad9d-11e7-8149-89f8595bd323.png)

This is the following div:

![image](https://user-images.githubusercontent.com/490562/31357370-e7f2e556-ad9d-11e7-8677-1d69780e2595.png)

Changing that overflow instruction to `overflow-y: auto` instead fixes the horizontal scrollbar.

**Comment by nathansobo** [comment]
@simurai could you help us figure out why the content always seems to overflow horizontally even if it's not really necessary? It seems to have something to do with a 10px padding that's getting added to the `list-tree` class, but I'm having trouble understanding why. With your CSS expertise you'd probably come to a conclusion faster.

**Comment by simurai** [comment]
>  It seems to have something to do with a 10px padding that's getting added to the `list-tree` class

Yes, that's right. And the scrollbar is caused because those child `<div>`s have `width: 100%` which doesn't account for the `list-tree` padding. Causing it to overflow. I made a PR where the padding gets moved to the children: https://github.com/atom/find-and-replace/pull/992

**Comment by simurai** [comment]
Ok, I found another way to reproduce it even with the "move padding to child" fix in #992.

1. Make sure you expand a result that wider and adds a horizontal scrollbar.
2. Try to click on the last item.

![find](https://user-images.githubusercontent.com/378023/35076415-b1179f4e-fc3b-11e7-9580-75718266dc5a.gif)

Not sure how to fix that, because a horizontal scrollbar is needed to read long lines. The only thing that I can think of is just adding some padding at the bottom, so the scrollbar never covers the last item?

**Comment by maxbrunsfeld** [comment]
> The only thing that I can think of is just adding some extra padding at the bottom, so the scrollbar never covers the last item.

👍   Seems ok to me.

**Comment by simurai** [comment]
Actually, if I test this case in an isolated place: https://codepen.io/simurai/pen/1c5e61337ba4f81ae22519ce80ebf700. I can click "through" the horizontal scrollbar as soon as it disappears.

![find](https://user-images.githubusercontent.com/378023/35076777-6829ce0e-fc3d-11e7-8f8c-520fc86744ec.gif)

So there still must be "something" that prevents clicks in Atom's case.

**Comment by adamreisnz** [comment]
Yeah, I've analysed this problem a fair bit. See a few comments back. I
think the culprit is an applied inline style.
