### ISSUE TITLE
Regex Replace Fails Silently

### ISSUE THREAD

**Issue by Swivelgames** [atom/find-and-replace#964]
Project-wide Regex Replace Fails Silently

### Setup 
Finding With Options: `Regex, Case Insensitive`
Find In Project: `^const isEmptyString.+$`
Replace In Project: `import { isEmptyString } from '../utils/utils.js';`

### Steps to Reproduce
1. `<Cmd><Shift><F>` to open up "Find In Project" drawer
2. Fill out form with items in "Setup" section above
3. Choose "Find All"
4. Notice all results show
   * Find results highlighted in Red
   * Replaced version highlighted in Green
5. Click "Replace All"

Obvious expected result is that the Red is replaced with the Green in the respective files.

### Actual Result
Find In Project pane reloads, but no changes take place to the files. This happens consistently.

### Potentially Unrelated Console Error

`<Cmd>+<Shift>+<i>` reveals the following error. However, the error is not always shown when reproducing this issue, so I believe it's unrelated.

```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at atom.workspace.open.then.editor (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/project/results-view.js:473:58)
```

**Comment by kylebarron** [comment]
I'm unable to reproduce this with Atom version 1.22.1. If I open a project, create a file named `test.js`, and include the text
```
const isEmptyString   
```
And do project find-and-replace with the regex term `^const isEmptyString.+$` and replace with `import { isEmptyString } from '../utils/utils.js';`, it works perfectly for me. Note that if the `g` of `isEmptyString` is ever the end of the line, you'll need to use `^const isEmptyString.*$`.
```
> atom -v    
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by Swivelgames** [comment]
@kylebarron This is quite an old issue, compared to the number of releases that have happened since the issue was opened (4 `find-and-replace` releases, and Atom itself has had 5 releases + 5 beta releases).

I will try to reproduce this again, but it may have been inadvertently fixed. I will reopen if the issue surfaces.
