### ISSUE TITLE
Multiple searches on one line should fold into one result

### ISSUE THREAD

**Issue by gjtorikian** [atom/find-and-replace#97]
I believe this should result in one result, not two.

![screen shot 2013-12-11 at 4 06 47 pm](https://f.cloud.github.com/assets/64050/1731366/7ff38fd8-6304-11e3-8e93-7086be3b664c.png)

**Comment by focusaurus** [comment]
I would prefer one line. A common workflow for me is to click each line, make some change, then return to the results to move down to the next line. This causes me to visit the same line twice. I'm editing well-formatted source code the vast majority of the time, so far-right matches on long lines don't commonly happen for me.

**Comment by focusaurus** [comment]
A few more pleas for single result, although I realize this is most likely moot and I'll stop after this last comment.

- This violates the conceptual integrity of the "line" as an entity programmers use to think about source code
- This is inconsistent with many previous tools including at least grep, egrep, ack, ag. Programmers have been searching files for patterns and getting a list of matching lines without duplicates for decades.

**Comment by nadim** [comment]
Can we have an option?

Are you accepting PR's?

+Nadim
