### ISSUE TITLE
Replace '\n' with something works incorrect

### ISSUE THREAD

**Issue by livace** [atom/find-and-replace#977]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When you trying to replace line ends with something it works not as expected

### Steps to Reproduce

1. Use Regex
2. Find: \n
3. Replace: something

**Expected behavior:** Atom replaces \n with 'something'

**Actual behavior:** Atom adds 'something' after \n

**Reproduces how often:** Everytime

### Versions

Windows 10

Atom    : 1.23.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.10

### Additional Information

There's no additional information

**Comment by 50Wliu** [comment]
Cannot reproduce.  Can you please share a GIF with your reproduction steps, similar to the one I have attached below?
![eol-replace](https://user-images.githubusercontent.com/2766036/33280011-f554af3a-d3a0-11e7-9db4-988402e14257.gif)

**Comment by livace** [comment]
I googled some and I think I know the reason. In Windows line ending is \r\n, so when replace \n it works not as I expected. So it's not bug.

Here is gif:
![gif](https://user-images.githubusercontent.com/6574709/33280355-d6968822-d3b2-11e7-81f6-703d85b4545a.gif)

**Comment by 50Wliu** [comment]
Thanks for the quick response @livace :zap:.  You can determine what line endings the file is using by looking at the `CRLF`/`LF` indicator in the status bar (`CRLF` indicates `\r\n`; `LF` indicates `\n`).  You'll notice that in my example I'm using LF line endings while you're using CRLF :).
