### ISSUE TITLE
Give an option in the package settings to auto enable "Only In Selection" when text is highlighted before invoking find.

### ISSUE THREAD

**Issue by JosephTLyons** [atom/find-and-replace#979]
<!--
### Description
As the title suggests, it would be nice to have an option in the package settings that when checked, would cause the option "Only In Selection" to be auto enabled when invoking the find feature.  It seems redundant to high text, command+f to invoke find, then manually have to select the option "Only In Selection," because chances are, if I have text highlighted and I command+f, I want to search inside of that selection only.  Giving the user the option to turn this on and off would be beneficial to those who don't like this sort of behavior.

### Versions

macOS 10.12.6
Atom 1.23.1
Find and Replace 0.215.0

**Comment by jedwards1211** [comment]
@50Wliu please?  This is standard behavior in many text editors.

**Comment by 50Wliu** [comment]
@jedwards1211 I think I forgot to comment on this issue before closing it.  It was closed because it lacked the issue template, which is required on all new issues.  Feel free to create a new issue and we'll take a look!

**Comment by jedwards1211** [comment]
@50Wliu ah, gotcha!
