### ISSUE TITLE
Project-wide regex search using \n does not find any matches

### ISSUE THREAD

**Issue by Conduitry** [atom/find-and-replace#995]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Regular expressions containing newlines (`\n`) do not find any matches when doing a project-wide search.

### Steps to Reproduce

1. Create a file in a project containing at least one newline (with unix line endings to avoid CR/LF confusion).
2. Start up project-wide search, in regex mode.
3. Type in `\n` and confirm that the newlines in the file are highlighted (as the automatic current-file search runs).
4. Press enter to perform the search across the entire project.

**Expected behavior:** All instances of the regex should be found.

**Actual behavior:** No instances of the regex are found.

**Reproduces how often:** Every time.

### Versions

Atom 1.25-beta0, Windows 10, x64 - although this is not the first version it occurred in. I'm not sure when/if this was ever working.

**Comment by 50Wliu** [comment]
This is a consequence of #218 - project-wide searches currently search line-by-line.  Feel free to subscribe to that issue for updates.
