### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

### ISSUE THREAD

**Issue by rsese** [atom/find-and-replace#998]
*@rsese edit to add repro steps /cc https://github.com/atom/find-and-replace/issues/998#issuecomment-378643806*

1. Open atom/atom `atom --safe .`
2. `Find and Replace: Show`
3. Enable `Only in Selection` 
4. `Project Find: Show`
5. Search for `aa` and run the search
6. While still in the Project Find Results, run`Find and Replace: Show`
7. Run a search

---

_From @joshvera on March 7, 2018 18:56_

[Enter steps to reproduce:]

1. Start a project search in a very large repository.
2. Start another project search while that project search is running.

**Atom**: 1.25.0-beta2 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:101

TypeError: Cannot read property 'getSelectedBufferRange' of null
    at BufferSearch.search (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/buffer-search.js:101:76)
    at FindView.liveSearch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:356:31)
    at findEditor.onDidStopChanging (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-view.js:291:56)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1773:26)
    at later (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -0:25.4.0 core:copy (input.hidden-input)
     -0:25.1.0 project-find:show (input.hidden-input)
     -0:24.8.0 core:paste (input.hidden-input)
     -0:24.3.0 core:confirm (input.hidden-input)
     -0:21 core:copy (input.hidden-input)
     -0:20.7.0 project-find:show (input.hidden-input)
     -0:20.6.0 core:paste (input.hidden-input)
     -0:20.3.0 core:confirm (input.hidden-input)
     -0:14.7.0 core:copy (input.hidden-input)
     -0:14.4.0 project-find:show (input.hidden-input)
     -0:14.2.0 core:paste (input.hidden-input)
     -0:13.9.0 core:confirm (input.hidden-input)
     -0:07.1.0 core:copy (input.hidden-input)
     -0:06.8.0 find-and-replace:show (input.hidden-input)
     -0:06.6.0 core:paste (input.hidden-input)
     -0:06.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

This happens in safe mode.

_Copied from original issue: atom/atom#16898_

**Comment by rsese** [comment]
Heyo @joshvera :wave:, thanks for reporting this!

> in a very large repository.

About how large is the repository?

**Comment by joshvera** [comment]
@rsese 👋 about 10k files. I don't think the size has too much to do with it, but if it's a race it might help.

**Comment by brandinarsenault** [comment]
`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedBufferRange' of null

```
At C:\Users\Brandin\AppData\Local\atom\app-1.25.0\resources\app\node_modules\find-and-replace\lib\buffer-search.js:101

TypeError: Cannot read property 'getSelectedBufferRange' of null
    at BufferSearch.search (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/find-and-replace/lib/buffer-search.js:101:76)
    at FindView.liveSearch (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/find-and-replace/lib/find-view.js:356:31)
    at findEditor.onDidStopChanging (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/find-and-replace/lib/find-view.js:291:56)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1773:26)
    at later (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
 23x -1:11.8.0 core:undo (input.hidden-input)
     -1:09.7.0 core:save (input.hidden-input)
     -1:08.8.0 core:undo (input.hidden-input)
     -1:06.4.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:06.2.0 core:copy (input.hidden-input)
     -1:06.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:05.9.0 editor:newline (input.hidden-input)
     -1:05.7.0 core:paste (input.hidden-input)
  4x -1:03.0 core:move-right (input.hidden-input)
  5x -1:02.2.0 editor:select-to-end-of-word (input.hidden-input)
     -1:00.8.0 core:backspace (input.hidden-input)
     -0:59.3.0 core:save (input.hidden-input)
  3x -0:39.3.0 core:copy (input.hidden-input)
     -0:37.8.0 project-find:show (input.hidden-input)
     -0:37.6.0 core:paste (input.hidden-input)
     -0:37.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
php-cs-fixer 4.1.1 
```

`
Here is a link to the repo:
https://github.com/mudmin/UserSpice43dev

**Comment by rsese** [comment]
Did you also try multiple project searches when you saw the error @brandinarsenault?

**Comment by brandinarsenault** [comment]
Hi @rsese ! The issue seemed to resolve itself after that one search-was not persistent, however I did want to comment on the issue to hopefully aid some insight! Not sure if this is a genuine problem-or just a one-off! Brandin.

**Comment by rsese** [comment]
Ahh ok, thanks for clarifying @brandinarsenault :+1:

**Comment by ariasuni** [comment]
I found how to reproduce this bug:

- Open «Find and Replace» panel (Ctrl+F) and enable «Only in selection»
- Open «Project Find and Replace» (Ctrl+Maj+F), change the text and launch the search

When in the «Project Find Results» tab, trying to do a Find (Ctrl+F) also triggers this bug (which seems logic: we can’t select text in this view). However, I don’t understand why this bug is also triggered by «Project Find and Replace».

**Comment by rsese** [comment]
I couldn't reliably reproduce with the first set of steps without having to go back and forth a bit but @Ben3eeE helped me repro with the second set of steps so I'll update the issue body with those steps.

**Comment by duanefields** [comment]
FWIW I too can reproduce the issue @ariasuni describes

**Comment by jag10** [comment]
For me I see this exception when I use commas while performing a search in a project:
- Open «Project Find and Replace» (Ctrl+Maj+F), input "a,a" and launch the search
- Exception is triggered

Reproducible in latest release (1.27.0)

**Comment by ariasuni** [comment]
I did more testing and thinking today.

There are really two separate issues:

- `FindView.liveSearch()` is called in Project Find «mode», but according to its name it shouldn’t. I guess it’s a bug that does nothing usually, but crash while trying to get the current selection.
- A file search can be triggered in a non-file pane. The find button should probably be disabled in this case, like the Replace and Replace All buttons when there’s no result (actually, we might also want to disable the Find and Find All button when the Find field is empty, as a matter of consistency).

Thought or pointers?

**Comment by timlesallen** [comment]
I routinely get this.  Fairly large repo too.
```bash
$ du -h -d 1
 29M    ./.git
376K    ./app
  0B    ./coverage
1.1M    ./data
332K    ./migrations
232M    ./node_modules
 12K    ./scripts
  0B    ./seeds
260K    ./test
263M    .
```

**Comment by mvancanneyt** [comment]
I can reproduce the issue exactly as @ariasuni describes. 
Disabling the 'search in selection' before doing a full project search gets rid of the error.
Size of the project does not seem to matter, I get this on a small project of 50 files or so.

**Comment by aknuds1** [comment]
I also get this if _Only in selection_ is enabled in file search before I perform a project wide search. Ironically I hadn't even enabled _Only in selection_, it sometimes gets enabled without my wanting to.

**Comment by jefflab** [comment]
I was also having this problem on every search. As a workaround, `atom --clear-window-state` seemed to make the error go away.

**Comment by kharthigeyan** [comment]
I am facing this problem...

```
atom -v
Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by cbfx** [comment]
same issue here. can't shake it.

```
atom -v
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
